
:toc:


===== St. Francis Prayer
[verse]
____
Lord, make me an instrument of Thy peace;
Where there is hatred, let me sow love;
Where there is injury, pardon;
Where there is error, truth;
Where there is doubt, faith;
Where there is despair, hope;
Where there is darkness, light;
And where there is sadness, joy. 
  
O Divine Master, Grant that I may not so much seek
To be consoled as to console;
To be understood as to understand;
To be loved as to love.
For it is in giving that we receive;
It is in pardoning that we are pardoned;
And it is in dying that we are born to eternal life.
____


===== Ulysses by Alfred Lord Tennyson
[verse]
____
It little profits that an idle king,
By this still hearth, among these barren crags,
Match'd with an aged wife, I mete and dole
Unequal laws unto a savage race,
That hoard, and sleep, and feed, and know not me.
I cannot rest from travel: I will drink
Life to the lees: All times I have enjoy'd
Greatly, have suffer'd greatly, both with those
That loved me, and alone, on shore, and when
Thro' scudding drifts the rainy Hyades
Vext the dim sea: I am become a name;
For always roaming with a hungry heart
Much have I seen and known; cities of men
And manners, climates, councils, governments,
Myself not least, but honour'd of them all;
And drunk delight of battle with my peers,
Far on the ringing plains of windy Troy.
I am a part of all that I have met;
Yet all experience is an arch wherethro'
Gleams that untravell'd world whose margin fades
For ever and forever when I move.
How dull it is to pause, to make an end,
To rust unburnish'd, not to shine in use!
As tho' to breathe were life! Life piled on life
Were all too little, and of one to me
Little remains: but every hour is saved
From that eternal silence, something more,
A bringer of new things; and vile it were
For some three suns to store and hoard myself,
And this gray spirit yearning in desire
To follow knowledge like a sinking star,
Beyond the utmost bound of human thought.
	
This is my son, mine own Telemachus,
To whom I leave the sceptre and the isle,—
Well-loved of me, discerning to fulfil
This labour, by slow prudence to make mild
A rugged people, and thro' soft degrees
Subdue them to the useful and the good.
Most blameless is he, centred in the sphere
Of common duties, decent not to fail
In offices of tenderness, and pay
Meet adoration to my household gods,
When I am gone. He works his work, I mine.

There lies the port; the vessel puffs her sail:
There gloom the dark, broad seas. My mariners,
Souls that have toil'd, and wrought, and thought with me—
That ever with a frolic welcome took
The thunder and the sunshine, and opposed
Free hearts, free foreheads—you and I are old;
Old age hath yet his honour and his toil;
Death closes all: but something ere the end,
Some work of noble note, may yet be done,
Not unbecoming men that strove with Gods.
The lights begin to twinkle from the rocks:
The long day wanes: the slow moon climbs: the deep
Moans round with many voices. Come, my friends,
'T is not too late to seek a newer world.
Push off, and sitting well in order smite
The sounding furrows; for my purpose holds
To sail beyond the sunset, and the baths
Of all the western stars, until I die.
It may be that the gulfs will wash us down:
It may be we shall touch the Happy Isles,
And see the great Achilles, whom we knew.
Tho' much is taken, much abides; and tho'
We are not now that strength which in old days
Moved earth and heaven, that which we are, we are;
One equal temper of heroic hearts,
Made weak by time and fate, but strong in will
To strive, to seek, to find, and not to yield.
____


===== Heaven—Haven: A nun takes the veil by Gerard Manley Hopkins
[verse]
____
I have desired to go
Where springs not fail,
To fields where flies no sharp and sided hail
And a few lilies blow.

And I have asked to be 
Where no storms come,
Where the green swell is in the havens dumb,
And out of the swing of the sea.
____


===== i carry your heart with me by E.E. Cummings
[verse]
____
i carry your heart with me (i carry it in
my heart) i am never without it (anywhere
i go you go, you go, my dear; and whatever is done
by only me is your doing, my darling)
	
i fear 
no fate (for you are my fate, my sweet) i want
no world (for beautiful you are my world, my true)
and it's you are whatever a moon has always meant
and whatever a sun will always sing is you

here is the deepest secret nobody knows
(here is the root of the root and the bud of the bud
and the sky of the sky of a tree called life; which grows
higher than soul can hope or mind can hide)
and this is the wonder that's keeping the stars apart

i carry your heart (i carry it in my heart)
____


===== Do Not Go Gentle Into That Good Night by Dylan Thomas
[verse]
____
Do not go gentle into that good night,
Old age should burn and rave at close of day;
Rage, rage against the dying of the light.

Though wise men at their end know dark is right,
Because their words had forked no lightning they
Do not go gentle into that good night.

Good men, the last wave by, crying how bright
Their frail deeds might have danced in a green bay,
Rage, rage against the dying of the light.

Wild men who caught and sang the sun in flight,
And learn, too late, they grieved it on its way,
Do not go gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Rage, rage against the dying of the light.

And you, my father, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not go gentle into that good night.
Rage, rage against the dying of the light. 
____


===== Ozymandias by Percy Bysshe Shelley
[verse]
____
I met a traveler from an antique land
Who said: 'Two vast and trunkless legs of stone
Stand in the desert. Near them, on the sand,
Half sunk, a shattered visage lies, whose frown,
And wrinkled lip, and sneer of cold command,
Tell that its sculptor well those passions read
Which yet survive, stamped on these lifeless things,
The hand that mocked them and the heart that fed.
And on the pedestal these words appear --
"My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!"
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.'
____

===== Desert Places by Robert Frost
[verse]
____
Snow falling and night falling fast, oh, fast
In a field I looked into going past,
And the ground almost covered smooth in snow,
But a few weeds and stubble showing last. 
	
The woods around it have it - it is theirs.
All animals are smothered in their lairs.
I am too absent-spirited to count;
The loneliness includes me unawares. 
	
And lonely as it is, that loneliness
Will be more lonely ere it will be less -
A blanker whiteness of benighted snow
With no expression, nothing to express. 
	
They cannot scare me with their empty spaces
Between stars - on stars where no human race is.
I have it in me so much nearer home
To scare myself with my own desert places. 
____


===== King James Bible, Corinthians 1 Ch. 13
[verse]
____
Though I speak with the tongues of men and of angels, and 
  have not charity, I am become as sounding brass, or a tinkling cymbal.
And though I have the gift of prophecy, and understand all mysteries, 
  and all knowledge; and though I have all faith, so that I could remove 
  mountains, and have not charity, I am nothing.
And though I bestow all my goods to feed the poor, and though I give 
  my body to be burned, and have not charity, it profiteth me nothing.
Charity suffereth long, and is kind; charity envieth not;  charity 
  vaunteth not itself, is not puffed up,
Doth not behave itself unseemly, seeketh not her own, is not easily
  provoked, thinketh no evil;
Rejoiceth not in iniquity, but rejoiceth in the truth;
Beareth all things, believeth all things, hopeth all things, 
  endureth all things.

Charity never faileth: but whether there be prophecies, 
  they shall fail; whether there be tongues, they shall cease; 
  whether there be knowledge, it shall vanish away.
For we know in part, and we prophesy in part.
But when that which is perfect is come, then that which
  is in part shall be done away.
When I was a child, I spake as a child, I understood as 
  a child, I thought as a child: but when I became a man, 
I put away childish things.
For now we see through a glass, darkly; but then face to 
  face: now I know in part; but then shall I know even as 
  also I am known.
And now abideth faith, hope, charity, these three; but 
  the greatest of these is charity.
____


===== King James Bible, Mark Ch. 8, 35-37
[verse]
____
For what shall it profit a man, if he shall gain the whole world, and lose his own soul?
Or what shall a man give in exchange for his soul?
____


===== No matter where, of comfort no man speak, Richard II by William Shakespeare
[verse]
____
No matter where; of comfort no man speak:
Let’s talk of graves, of worms, and epitaphs;
Make dust our paper and with rainy eyes
Write sorrow on the bosom of the earth,
Let’s choose executors and talk of wills:
And yet not so, for what can we bequeath
Save our deposed bodies to the ground?
Our lands, our lives and all are Bolingbroke’s,
And nothing can we call our own but death
And that small model of the barren earth
Which serves as paste and cover to our bones.
For God’s sake, let us sit upon the ground
And tell sad stories of the death of kings;
How some have been deposed; some slain in war,
Some haunted by the ghosts they have deposed;
Some poison’d by their wives: some sleeping kill’d;
All murder’d: for within the hollow crown
That rounds the mortal temples of a king
Keeps Death his court and there the antic sits,
Scoffing his state and grinning at his pomp,
Allowing him a breath, a little scene,
To monarchize, be fear’d and kill with looks,
Infusing him with self and vain conceit,
As if this flesh which walls about our life,
Were brass impregnable, and humor’d thus
Comes at the last and with a little pin
Bores through his castle wall, and farewell king!
Cover your heads and mock not flesh and blood
With solemn reverence: throw away respect,
Tradition, form and ceremonious duty,
For you have but mistook me all this while:
I live with bread like you, feel want,
Taste grief, need friends: subjected thus,
How can you say to me, I am a king?
____


===== The Road Not Taken by Robert Frost
[verse]
____ 
Two roads diverged in a yellow wood, 
And sorry I could not travel both 
And be one traveler, long I stood 
And looked down one as far as I could 
To where it bent in the undergrowth; 
	
Then took the other, as just as fair, 
And having perhaps the better claim, 
Because it was grassy and wanted wear; 
Though as for that the passing there 
Had worn them really about the same, 
	
And both that morning equally lay 
In leaves no step had trodden black. 
Oh, I kept the first for another day! 
Yet knowing how way leads on to way, 
I doubted if I should ever come back. 

I shall be telling this with a sigh 
Somewhere ages and ages hence: 
Two roads diverged in a wood, and I— 
I took the one less traveled by, 
And that has made all the difference.
____


===== From 'Citizenship in a Republic', by Theodore Roosevelt
[verse]
____
It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat.
____


===== Girder by Nan Cohen 
[verse]
____
The simplest of bridges, a promise
that you will go forward,

that you can come back.
So you cross over.

It says you can come back.
So you go forward.

But even if you come back
then you must go forward.

I am always either going back
or coming forward. There is always

something I have to carry,
something I leave behind.

I am a figure in a logic problem,
standing on one shore

with the things I cannot leave,
looking across at what I cannot have. 
____


===== Ernest Hemingway
[verse]
____
The world breaks everyone and afterward many are strong at the broken places. But those that will not break it kills. It kills the very good and the very gentle and the very brave impartially. If you are none of these you can be sure it will kill you too but there will be no special hurry.
____


===== What if you slept ...  by Samuel Coleridge
[verse]
____
What if you slept 
And what if 
In your sleep 
You dreamed 
And what if 
In your dream 
You went to heaven 
And there plucked a strange and beautiful flower 
And what if 
When you awoke 
You had that flower in you hand 
Ah, what then? 
____


===== about competition by Charles Bukowski
[verse]
____
the higher you climb
the greater the pressure.

those who manage to
endure
learn
that the distance
between the 
top and the 
bottom
is 
obscenely
great.

and those who
succeed
know 
this secret:
there isn't
one.
____


===== Nothing is Lost by Noel Coward
[verse]
____
Deep in our sub-conscious, we are told
Lie all our memories, lie all the notes
Of all the music we have ever heard
And all the phrases those we loved have spoken,
Sorrows and losses time has since consoled,
Family jokes, out-moded anecdotes
Each sentimental souvenir and token
Everything seen, experienced, each word
Addressed to us in infancy, before
Before we could even know or understand
The implications of our wonderland.
There they all are, the legendary lies
The birthday treats, the sights, the sounds, the tears
Forgotten debris of forgotten years
Waiting to be recalled, waiting to rise
Before our world dissolves before our eyes
Waiting for some small, intimate reminder,
A word, a tune, a known familiar scent
An echo from the past when, innocent
We looked upon the present with delight
And doubted not the future would be kinder 
And never knew the loneliness of night. 
____


===== Notebooks (1951-1959) by Albert Camus
[verse]
____
Find meaning. Distinguish melancholy from sadness. Go out for a walk. It doesn’t have to be a romantic walk in the park, spring at its most spectacular moment, flowers and smells and outstanding poetical imagery smoothly transferring you into another world. It doesn’t have to be a walk during which you’ll have multiple life epiphanies and discover meanings no other brain ever managed to encounter. Do not be afraid of spending quality time by yourself. Find meaning or don’t find meaning but 'steal' some time and give it freely and exclusively to your own self. Opt for privacy and solitude. That doesn’t make you antisocial or cause you to reject the rest of the world. But you need to breathe. And you need to be.
____

	
===== Ars Poetica with Bacon by Terrence Hayes
[verse]
____
Fortunately, the family, anxious about its diminishing 
food supply, encountered a small, possibly hostile pig
along the way. The daughter happened upon it first
pushing its scuffed snout against something hidden 
at the base of a thornbush: a blood-covered egg, maybe, 
or small rubber ball exactly like the sort that snapped
from the paddle my mother used to beat me with 
when I let her down. At the time the father and mother 
were tangled in some immemorial dispute about cause 
and effect: who’d harmed whom first, how jealousy
did not, in fact, begin as jealousy but as desperation. 
When the daughter called out to them, they turned 
to see her lift the pig, it was no heavier than an orphan,
from the bushes and then set it down in their path. 
They waited to see whether the pig might idle forward 
with them until they made camp or wander back toward 
the home they’d abandoned to war. Night, enclosed 
in small drops of rain, began to fall upon them. 
“Consequence” is the word that splintered my 
mind.Walking a path in the dark is about something 
the way a family is about something. Like the pig, 
I too, wanted to reach through the thorns for the egg 
or ball, believing it was a symbol of things to come. 
I wanted to roll it in my palm like the head 
of a small redbird until it sang to me. I wanted 
to know how my mother passed her days having 
never touched her husband’s asshole, for example. 
Which parts of your body have never been touched, 
I wanted to ask. I’d been hired to lead the family 
from danger to a territory full of more seeds than bullets, 
but, truth was, in the darkness there was no telling 
what was rooting in the soil. Plots of complete silence, 
romantics posing in a field bludgeoned by shame. 
The heart, biologically speaking, is ugly as it pumps 
its passion and fear down the veins. Which is to say, 
starting out we have no wounds to speak of 
beyond the ways our parents expressed their love. 
We were never sure what the pig was after or whether 
it was, in fact, not a pig but some single-minded soul 
despair turned into a pig, some devil worthy of mercy. 
Without giving away the enigmatic ending, I will say, 
when we swallowed the flesh, our eyes were closed. 
____


===== Part One: Life, XXII by Emily Dickinson
[verse]
____
I had no time to hate, because
The grave would hinder me,
And life was not so ample I
Could finish enmity.

Nor had I time to love; but since            
Some industry must be,
The little toil of love, I thought,
Was large enough for me.
____


===== Part Four: Time and Eternity XXIII by Emily Dickinson
[verse]
____
I reason, earth is short,
And anguish absolute.
And many hurt;
But what of that?

I reason, we could die:        
The best vitality
Cannot excel decay;
But what of that?

I reason that in heaven
Somehow, it will be even,           
Some new equation given;
But what of that?
____


===== Part One: Life, XXVII, Compensation by Emily Dickinson
[verse]
____
For each ecstatic instant
We must an anguish pay
In keen and quivering ratio
To the ecstasy.

For each beloved hour
Sharp pittances of years,
Bitter contested farthings
And coffers heaped with tears.
____


===== Part Two: Life, XXXIII by Emily Dickinson
[verse]
____
I took my power in my hand.
And went against the world;
'T was not so much as David had,
But I was twice as bold.
I aimed my pebble, but myself
Was all the one that fell.
Was it Goliath was too large,
Or only I too small?
____


===== King James Bible, Matthew Ch. 11, 28-30
[verse]
____
Come unto me, all ye that labour and are heavy laden, and 
  I will give you rest
Take my yoke upon you, and learn of me; for I am meek and 
  lowly in heart: and ye shall find rest unto your souls.
For my yoke is easy, and my burden is light.
____


===== The Author Observes His Birthday by John Updike
[verse]
____
My life, my life with children, was a sluice
that channeled running water to my pan;
by tilting it, and swirling lightly, I
at end of day might find a fleck of gold.
____


===== Second Spring by John Henry Newman
[verse]
____
WE have familiar experience of the order, the constancy, the perpetual renovation of the material world which surrounds us. Frail and transitory as is every part of it, restless and migratory as are its elements, never-ceasing as are its changes, still it abides. It is bound together by a law of permanence, it is set up in unity; and, though it is ever dying, it is ever coming to life again. Dissolution does but give birth to fresh modes of organization, and one death is the parent of a {164} thousand lives. Each hour, as it comes, is but a testimony, how fleeting, yet how secure, how certain, is the great whole. It is like an image on the waters, which is ever the same, though the waters ever flow. Change upon change—yet one change cries out to another, like the alternate Seraphim, in praise and in glory of their Maker. The sun sinks to rise again; the day is swallowed up in the gloom of the night, to be born out of it, as fresh as if it had never been quenched. Spring passes into summer, and through summer and autumn into winter, only the more surely, by its own ultimate return, to triumph over that grave, towards which it resolutely hastened from its first hour. We mourn over the blossoms of May, because they are to wither; but we know, withal, that May is one day to have its revenge upon November, by the revolution of that solemn circle which never stops—which teaches us in our height of hope, ever to be sober, and in our depth of desolation, never to despair.
____


===== Manfred by Lord George Gordon Byron
[verse]
____
Sorrow is knowledge: they who know the most
Must mourn the deepest o’er the fatal truth,
The Tree of Knowledge is not that of Life.
____


===== Childe Harold’s Pilgrimage by Lord George Gordon Byron
[verse]
____
There is a rapture on the lonely shore,
There is society, where none intrudes,
By the deep Sea, and music in its roar:
I love not Man the less, but Nature more,
From these our interviews, in which I steal
From all I may be, or have been before,
To mingle with the Universe and feel
What I can ne’er express, yet can not all conceal.
____


===== King James Bible, Luke Ch. 6, 37
[verse]
____
Judge not, and ye shall not be judged: condemn not, 
  and ye shall not be condemned: forgive, and ye shall be forgiven: 
Give, and it shall be given unto you; good measure, pressed down, 
  and shaken together, and running over, shall men give into your bosom.  
  For with the same measure that ye mete withal it shall be measured to you again.
____


===== Little Gidding by T.S. Elliot
[verse]
____
We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
____


===== William Carlos Williams
[verse]
____
It is difficult to get the news from poems yet men die miserably every day for lack of what is found there.
____


===== To Those Who Follow in Our Wake by Bertolt Brecht
[verse]
____
I
Truly, I live in dark times!
An artless word is foolish. A smooth forehead
Points to insensitivity. He who laughs
Has not yet received
The terrible news.

What times are these, in which
A conversation about trees is almost a crime
For in doing so we maintain our silence about so much wrongdoing!
And he who walks quietly across the street,
Passes out of the reach of his friends
Who are in danger?

It is true: I work for a living
But, believe me, that is a coincidence. Nothing
That I do gives me the right to eat my fill.
By chance I have been spared. (If my luck does not hold,
I am lost.)

They tell me: eat and drink. Be glad to be among the haves!
But how can I eat and drink
When I take what I eat from the starving
And those who thirst do not have my glass of water?
And yet I eat and drink.

I would happily be wise.
The old books teach us what wisdom is:
To retreat from the strife of the world
To live out the brief time that is your lot
Without fear
To make your way without violence
To repay evil with good —
The wise do not seek to satisfy their desires,
But to forget them.
But I cannot heed this:
Truly I live in dark times!

II

I came into the cities in a time of disorder
As hunger reigned.
I came among men in a time of turmoil
And I rose up with them.
And so passed
The time given to me on earth.

I ate my food between slaughters.
I laid down to sleep among murderers.
I tended to love with abandon.
I looked upon nature with impatience.
And so passed
The time given to me on earth.

In my time streets led into a swamp.
My language betrayed me to the slaughterer.
There was little I could do. But without me
The rulers sat more securely, or so I hoped.
And so passed
The time given to me on earth.

The powers were so limited. The goal
Lay far in the distance
It could clearly be seen although even I
Could hardly hope to reach it.
And so passed
The time given to me on earth.

III

You, who shall resurface following the flood
In which we have perished,
Contemplate —
When you speak of our weaknesses,
Also the dark time
That you have escaped.

For we went forth, changing our country more frequently than our shoes
Through the class warfare, despairing
That there was only injustice and no outrage.

And yet we knew:
Even the hatred of squalor
Distorts one’s features.
Even anger against injustice
Makes the voice grow hoarse. We
Who wished to lay the foundation for gentleness
Could not ourselves be gentle.

But you, when at last the time comes
That man can aid his fellow man,
Should think upon us
With leniency.
____


===== Sometimes the father almost sees looking by Terrence Hayes
[verse]
____
Sometimes the father almost sees looking
At the son, how handsome he'd be if half
His own face was made of the woman he loved.
He almost sees in his boy's face, an openness
Like a wound before it scars, who he was
Long before his name was lost, the trail
To his future on earth long before he arrived.
To be dead & alive at the same time.
A son finds his father handsome because
The son can almost see how he might
Become superb as the scar above a wound.
And because the son can see who he was
Long before he had a name, the trace of
His future on earth long before he arrived.
____


===== When Dean Young Talks About Wine by Tony Hoagland
[verse]
____
The worm thrashes when it enters the tequila.
The grape cries out in the wine vat crusher.

But when Dean Young talks about wine, his voice is strangely calm.
Yet it seems that wine is rarely mentioned.

He says, Great first chapter but no plot.
He says, Long runway, short flight.
He says, This one never had a secret.
He says, You can't wear stripes with that.

He squints as if recalling his childhood in France.
He purses his lips and shakes his head at the glass.

Eight-four was a naughty year, he says,
and for a second I worry that California has turned him
into a sushi-eater in a cravat.

Then he says,
This one makes clear the difference
between a thoughtless remark
and an unwarranted intrusion.

Then he says, In this one the pacific last light of afternoon
stains the wings of the seagull pink
at the very edge of the postcard.

But where is the Cabernet of rent checks and asthma medication?
Where is the Burgundy of orthopedic shoes?
Where is the Chablis of skinned knees and jelly sandwiches?
with the aftertaste of cruel Little League coaches?
and the undertone of rusty stationwagon?

His mouth is purple as if from his own ventricle
he had drunk.
He sways like a fishing rod.

When a beast is hurt it roars in incomprehension.
When a bird is hurt it huddles in its nest.

But when a man is hurt,
he makes himself an expert.
Then he stands there with a glass in his hand
staring into nothing
as if he were forming an opinion.
____


===== The Parable of Perfect Silence by Christian Wiman
[verse]
____
Today I woke and believed in nothing.
A grief at once intimate and unfelt,
like the death of a good friend’s dog.

Tired of the mind reaching back in the past for rescue
I praise the day.
I don’t mean merely some mythical, isolate instant
like the mindless mindfulness specialist
who at the terminal cancer convention
(not that it was called that)
exhorted the new year’s crop of slaughters
(ditto)
to “taste” the day, this one unreplicable instant of being alive.
(The chicken glistened.)
Nor do I mean a day devoid of past and future
as craved that great craze of minds and times Fernando Pessoa,
who wanted not “the present” but reality itself,
things in their thingness rather than the time that measures them.
Time is in the table at which I sit and in the words I type.
In the red-checked shirt my father’s mother used to wear
when she was gardening and which I kept
because it held her smell (though it does no longer)
there is still plenty of time.

Two murderers keep their minds alive
while they wait to die.
They talk through slots in their doors
of whatever mercy or misery
the magazine has ordained for the day — 
the resurgence of the Taliban in Afghanistan, say,
ten signs that a relationship is on the rocks.
When their communion flags, as communions will,
they rekindle it with personal revelations, philosophical digressions,
humor. This is a true story,
one of them says sometimes by way of preface,
as if that gave the moment more gravity,
asked of the listener a different attention,
at once resisted and reinforced an order
wherein every hour has its sound, every day its grace,
and every death is by design.

“Love is possible for anyone,” I hear the TV talk-show host say,
which is true in the way most things in this life are true,
which is to say, false,
unless and until the nullifying, catalyzing death is felt.
Love is possible for anyone
because it is equally impossible for everyone.
To be is to be confronted with a void,
a blankness, a blackness that both appeals and appalls.
Once known — known by the void, I mean — one has three choices.
Walk away, and unlearn the instinct of awe.
Walk along, and learn to believe that awe asks nothing of you.
Are you with me, love?

(For love read faith.)

Naked once and after a rat, my father cried, “Die, vermin, die!”
banging the broomstick over and over on the floor
so incorrigibly dirty it might as well have been the earth itself.
This is my mother’s story, though I was there, I’m told,
and no small part of the pandemonium.
We were five souls crammed into one life,
and so incorrigibly poor — or was that fear? — we all slept in one room
and shared one great big chester drawers, as we called it,
and not with irony but in earnest ignorance,
just as like meant lack, as in
“How much do you like bein’ done with your chemo?”
and just as I and every other child I knew,
before we tucked into our lemon meringue pie,
solemnly wiped the calf slobbers off.
Ah, local color, peasant levity, the language fuming and steaming
rich as the mist of rot that rises off the compost heap
(“kitchen midden,” you might hear an old Scot still say).
When do we first know? That there’s a world
to which we’ve been, not oblivious, exactly,
but so inside we couldn’t see it, who now see nothing else?
Heaven is over. Or hell.
Did you forget the rat?
It thumps and thrashes like a poltergeist inside
the chest of drawers but somehow, though my father is fast,
and though his rage is becoming real, every drawer he opens
is empty. What happens when we die,
every child of every father eventually asks.
What happens when we don’t
is the better question.

To kill a wasp on water is the peak of speed.
My brother who is other has a mind of lead.
I with my stinging griefs watch from away.
How can it be there are no adults left?
What matters here is timing, not time.
His hand is high and white above the blue.
A wasp is also atom and urge, hover and touch.
Even wings are not a clean distinction.
Down comes the slap like a rifle shot.
What vengeance can there be on blank necessity?
My brother who is other has a way.
His hand is high and white. And then it’s not.

Once when my father’s mother’s health was failing
and she found it more and more difficult to tend
to the tiny family plot at Champion, Texas,
which is less town than time at this point,
a blink of old buildings and older longings the rare driver
flashes past, I took it upon myself to salt the graves
as I must have read somewhere would work for unwanted growths.
As indeed it did.
In the months after, every Sunday when we spoke,
she thanked me for the blankness, the blackness,
(my words, of course)
this new ease I had allowed her mind.
Until one day leaning over with flowers the leached earth
opened and my eighty-year-old grandmother
tumbled right down among the bones
of the woman from whom she’d first emerged.
To see that image you have to be that sky.
It has to happen in you, that crushing calling viewless blue
that is so deeply in you that it is not you.
“O, Law’, honey, I like to died.”

You don’t climb out of poverty so much as carry it with you.
Some shell themselves with wealth.
Some get and spend, get and spend, skimming existence like a Jesus lizard.
But for those whose souls have known true want
— whose souls perhaps are true want — 
money remains, in some sense, permanently inert,
like an erotic thought that flashes through a eunuch’s brain.
In 1980 my father bought his first airplane,
a scream-proof four-seater we crammed five inside,
which he considerately slammed into a sorghum field alone.
Unkillable, he killed the next ten years with work and wives,
then bought another, and brought it down in the solitary fire
that was his aspect and atmosphere. Homes, schemes,
thirty years of savings plowed into a sign company (!)
that did not, it turned out, exist.
A hole is hard to carry.

People ask if I believe in God and the verb is tedious to me.
Not wrong, not offensive, not intrusive, not embarrassing.
Tedious.
Today I saw a hawk land on Elizabeth’s chimney.
It sat with its bone frown and banker’s breast
above the proud houses of Hamden.
Are you with me? Then see,
too, a lump of animate ash rising from the flue
(or so it seems) to be a pigeon
fluttering dumbly down
next to that implacable raptor,
suddening a world of strange relations
wherein there is no need for fear, or far,
or meat.

There was a man made of airplane parts,
one of which was always missing.
He wandered the hospital grounds in search of a rudder,
an aileron, or some other fragment
that would let him fly from this place
where he was not meant to be.
There was a woman who emitted invective
ceaselessly, dispassionately, an obscenity machine.
One timid gentleman saved Saran wrap for five full years
and every night wrought an ever-more-solid ball
with which, it turned out, he planned to bash the skull
of the first soul he saw the dawn God blessed his weapon.
(A success story, alas.)
Another man with anvil hands sat six months of nights in faith
that there would come occasion of darkness, unguardedness, and vision
sufficient to rip from its socket one of my father’s bright blue eyes.
(Ditto.)
My father moved among them like a father.
He attended and pacified, he instructed and consoled.
Late to the trade, he worked too much,
and trusted his heart, no doubt, more than he should,
but was, by all accounts, at this one thing, and despite the end, good.

For love read faith
into these lines that so obviously lack it.
For love let words turn to life
in the way life turns to world
under the observer’s eye, the swirl
of particles with their waves and entanglements,
their chance and havoc, resolving
into some one thing:
a raptor on a rooftop, say.
No power on earth can make it stay.
But is it lost or released into formlessness
when we look away?

To be is to believe
that the man or woman
who inscribed with an idiosyncratic but demanding calligraphy
Fuck da money — Trust no one
on the rough blanket of the residential motel
where my father spent the last two years of his rough residential life
intended the note of defiant, self-conscious (da!) humor
that left my father, whom I had not seen in years,
and I, whom years had seen grow sere, far even from myself,
erupting in laughter until we cried.

Before my good friend’s good dog died
ten times a day she pressed her forehead to his
“to confirm the world and her place in it.”
Now she won’t even say his name.
Strange how the things that burn worst in one heart
one must keep silent to keep.

Ten to one you thought of men.
The murderers, I mean.
But no. This is a true story.
There is another cell, you see,
in which a woman I have known since childhood,
and since childhood have known to be
suspended on a wire of time but nimble-witted nonetheless,
lies on the cold stone floor.
She is even more naked than they have made her.
She has killed no one not even herself.
Punishment, perhaps, or some contagion of fate, finds her here,
her hair shorn, both wrists wrapped, her eyes open,
pondering the parable of perfect silence.

Remember, he said, memory is a poor man’s prison.
Make to have and to love one live infinitive,
then blessed my brow with the sign of the cross.
I woke without a chance to ask the obvious:
But what if all our songs are songs of loss?

I felt nothing when you died, Father.
(As if I ever called you that.)
It is a long cold seep, this grief.
The day itself was hot enough to make the devil sweat,
as more than one person, with less than one mind, muttered to me.
What I remember: two children, too tan
and “clad in famine” (Dahlberg), look up
from their parched front yard,
their sad little sprinkler like a flower of hell.
I don’t mean I saw them, though I did.
I mean they are what I remember, fleshed.
That town. A hint of new prison business,
and the Square’s been rewhitened,
but mostly it’s beastly, a blast site,
our old house less house than nest,
and even the undertaker, a friend
from high school, has graduated to heroin.
You would have been right at home,
and I guess in a ghoulish way you were,
overdressed, overdosed, over.
Hard wind at the graveside. Hard lives hardly there.
The canopy whipped and flapped.
A bouquet skipped over the graves like a strange elation.
Something stuck, and an ageless Indian
(he might have been Mom’s long-dead granddad)
nimbled over the casket’s contraptions to make it go. You go
into the ground again, and the silence assaults
like heat, and the clumps of would-be grievers unclump
and head for cars, and Mom cracks
a tallboy and two jokes before we’re on the highway.
The first I forget, and of the second I recall only a nakedness, and wild crying,
and a rat.

When the doctor said I’d likely die I thought of my father
telling me he’d learned to read a cancer look,
that some people had it before they had it, so to speak.
When the young guard demanded to unwrap the Snickers
I’d bought for my sister my father scoffed:
“All this energy expended on candy when you could take this can”
— he held her Coke up in front of our eyes — “and cut a throat.”
When my sister, chewing her chocolate with ravenous indifference,
paused and stared balefully off at the even more baleful brown
beyond the barbed wire, it did not occur to me
that it was inspiration. When I began writing these lines
it was not, to be sure, inspiration but desperation,
to be alive, to believe again in the love of God.
The love of God is not a thing one comprehends
but that by which — and only by which — one is comprehended.
It is like the child’s time of pre-reflective being,
and like that time, we learn it by its lack.
Flashes and fragments, flashes and fragments,
these images are not facets of some unknowable whole
but entire existences in themselves, like worlds
that under God’s gaze shear and shear and, impossibly, are:
untouching, entangled, sustained, free.
If all love demands imagination, all love demands withdrawal.
We must create the life creating us, and must allow that life to be — 
and to be beyond, perhaps, whatever we might imagine.
I, too, am more (and less)
than anything I imagine myself to be.
“To know this,” says Simone Weil, “is forgiveness.”

It is an air you enter, not an act you make.
It is the will’s frustration, and is the will’s fruition.
It is to wade a blaze one night that I once crossed
— a young man, and lost — 
to find a woman made of weather
sweeping the street in front of her shack.
It is another country.
It is a language I don’t know.
La por allá, la por allá, I repeat in my sleep.
The over there.

Tired of the mind reaching back in the past for rescue
I praise the day
my father woke in the motel room where all five of us were sleeping,
which is not even past but a flame as I say it,
and see it, the little lighter now he is using to find his clothes.
I who have not slept in forty-five years am awake for the first time
rising carefully out of my pallet on the floor
and feeling my way beyond the bodies of my brother and sister
toward the shade that is my father
to stand in this implausible light where to whisper would be too much,
and anyway what’s next is known, Dad, and near,
the nowhere diner, hot chocolate and the funny pages,
and the consolation that comes when there is nothing to console.
____


===== Childhood’s Retreat by Robert Duncan
[verse]
____
It’s in the perilous boughs of the tree
out of blue sky    the wind
sings loudest surrounding me.

And solitude,   a wild solitude
’s reveald,   fearfully,   high     I’d climb
into the shaking uncertainties,

part out of longing,   part     daring my self,
part to see that
widening of the world,   part

to find my own, my secret
hiding sense and place, where from afar
all voices and scenes come back

—the barking of a dog,   autumnal burnings,
far calls,   close calls—   the boy I was
calls out to me
here the man where I am   “Look!

I’ve been where you
most fear to be.”
____


===== As Planned by Frank O'Hara
[verse]
____
After the first glass of vodka
you can accept just about anything
of life even your own mysteriousness
you think it is nice that a box
of matches is purple and brown and is called
La Petite and comes from Sweden
for they are words that you know and that
is all you know words not their feelings
or what they mean and you write because
you know them not because you understand them
because you don't you are stupid and lazy
and will never be great but you do
what you know because what else is there?
____


===== Comfort Animal by Joy Ladin
[verse]
____
A voice says, “Your punishment has ended.”
You never listen to that voice. You really suck
at being comforted.

Another voice says, “Cry.”
That voice always gets your attention,
keeps you thinking

about withered flowers and withering grass
and all the ways you’re like them.
Hard to argue with that.

Death tramples you, an un-housebroken pet
trailing prints and broken stems,
pooping anxiety, PTSD, depression.

It’s better to be animal than vegetable
but best of all is to be spirit
flying first or maybe business class

with your emotional support animal, your body,
curled in your lap, soaring with you
above the sense of loss you’ve mistaken

for the closest to God you can get.
You want to cry? Cry about that.
Who do you think created

the animals to whom you turn for comfort,
dogs, miniature horses, monkeys, ferrets,
hungers you know how to feed,

fears you know how to quiet?
I form them, fur them,
it’s my warmth radiating from their bodies,

my love that answers
the love you lavish upon them.
Your deserts and desolations

are highways I travel,
smoothing your broken places,
arranging stars and constellations

to light your wilderness.
Sometimes I play the shepherd;
sometimes I play the lamb;

sometimes I appear as death,
which makes it hard to remember
that I am the one who assembled your atoms,

who crowned your dust with consciousness.
I take you everywhere,
which is why, wherever you go, I’m there,

keeping you hydrated, stroking your hair,
laughing when you chase your tail,
gathering you to my invisible breasts

more tenderly than any mother.
You’re right—you never asked for this. I’m the reason
your valleys are being lifted up,

the source of your life laid bare.
Mine is the voice that decrees—
that begs—your anguish to end.

When you suffer, I suffer.
Comfort me
by being comforted.
____


===== Thinking by Rocket Caleshu
[verse]
____
I am thinking that
to make thinking new again
is torch-lit work, subterranean

and exalted. Antarctica, Goethe,
Methuselah. Seven hills of Rome.
An advertisement for a summer farming gig

on a homestead in Alaska puzzles me:
imagine harvesting kale through days
of unrepentant 24-hour sunlight,

covered in mosquitoes. How do you do
the things in the dark when there is no dark?
I want now to tell you abt my love

for my whip, for killing the engine and sitting
in the garage. This is also an ancient
practice.
____


===== Silhouettes by Kien Lam
[verse]
____
A crow perches inside me.

Actually, it is a whale. It is hard to tell
by touch alone. Nothing I own ever looks
me properly in the eye. Sometimes

a loud caw at dusk feels
like the largest mammal on Earth.

A deep breath out the blowhole

into my stomach. One second it swims
and the next it is a small extension
of a tree. This is a kind of beginning—

a finger puppet show. The light
dancing around my hands.

Me dancing alone on a stem.

A persimmon blooms.
A boy learns a song and plants it
in an orchard. Inside of me

the large creatures change their shapes
to fit. A blackbird. An organ.

Animals with no names. I send them off
into the world daily. Little sadness
takes flight. Love is a brave child.

These things take the shape
of their containers.

I don’t have to do anything
to hold them.
____


===== i haven’t masturbated in five days for fear of crying by Eloisa Amezcua
[verse]
____
because we know distance too well
because the blood bank didn’t have enough blood for nana & her new knee
because i see your car a car like yours parked across the street from my apartment
because the same night awaits us all
because arizona & the drought & i was seven when it started
because nana used to sleep with a belt tied around her waist so tight to wake like an hourglass
because i wait on you
because i want to know the antonym to every word
because we speak to each other in our sleep
because i do my best thinking in the shower so i take long showers
because you kiss the parts of my body i hate most
because you can love someone & not remember their birthday
because sometimes i want the wind & it is impossible
because from the airplane i can see both oceans & where they meet
____


===== Honeymoon by Brenda Shaughnessy
[verse]
____
It’s so flat here you can see everything. It’s not romantic. Nobody can slip in or out in secret, and who among us has pumped the last worry through her heart?

Collapsing into shade, I wish for more sons, endless daughters: a higher ratio of my people to other people. Why not want what I want; since we used all the air conditioning it’s become impossible to think things through.

Can you believe your ears? All the electric music in the world has been turned into handbells. I wish I had a cushion for my knees instead of gloves to keep the handbells pure. We can get used to anything. That doesn’t mean we should.

I went to a wedding where everything was outrageous but trying to act  modest by including very goofy elements, such as people in bear costumes and gold nuggets descending from the ceiling, only to be jerked back up out of reach when people tried to grab them.

Long ago, a matrimonial family collected a few eggs from each household in the village to contribute to the wedding cake. A pig for the dinner: a gift from a rich great-uncle. Shortly after, there was a period of department store gift services and electro-synth harps for hire.

But now we pick dandelions to make wine, and pluck chickens to make fine the groom’s cloak. He wants large brown wings; he wants wolf pelt for his loins. He wants he wants he wants. There is no end to that.

The bride is someone who has only ever served. No use asking someone who’s once had a true taste of freedom, whose eyes widened and whose pelvis thrust up unbidden. Better she be someone who might never know what she lost.

It is as it ever was. How many centuries have brides been made and used in this way?

How few centuries have let women be girls first, swirling as long as they wanted into their sweetness and sharpening to ripeness, only becoming women once full heavy love was their desire inside and out. Maybe one. Maybe not quite one full century.
____


===== Among Every Three Fathers, One Will by Jennifer Tseng
[verse]
____
It is a hall of patience. For eyes. For ears. Now it is dark and the urge I have had so often to turn the pictures toward the wall has vanished. The dark takes care of everything. I am a girl who plays piano for seven hours with a metronome clacking behind the tune like a clock, so that when at last the dark comes, I am tired. My back is tired of straightening, my feet are tired of pedaling, and my hands, my tiny horses, have galloped for miles. If I said  hall  I meant tunnel. If I said  play I meant  pray. If I said  father  I meant  memory. If I said God  I meant world, I meant will.
____


===== The Snow Man by Wallace Stevens
[verse]
____
One must have a mind of winter
To regard the frost and the boughs
Of the pine-trees crusted with snow;

And have been cold a long time
To behold the junipers shagged with ice,
The spruces rough in the distant glitter

Of the January sun; and not to think
Of any misery in the sound of the wind,
In the sound of a few leaves,

Which is the sound of the land
Full of the same wind
That is blowing in the same bare place

For the listener, who listens in the snow,
And, nothing himself, beholds
Nothing that is not there and the nothing that is.
____


===== Let America Be America Again by Langston Hughes
[verse]
____
Let America be America again.
Let it be the dream it used to be.
Let it be the pioneer on the plain
Seeking a home where he himself is free.
 
(America never was America to me.)
 
Let America be the dream the dreamers dreamed—
Let it be that great strong land of love
Where never kings connive nor tyrants scheme
That any man be crushed by one above.
 
(It never was America to me.)
 
O, let my land be a land where Liberty
Is crowned with no false patriotic wreath,
But opportunity is real, and life is free,
Equality is in the air we breathe.
 
(There's never been equality for me,
Nor freedom in this "homeland of the free.")
 
Say, who are you that mumbles in the dark?
And who are you that draws your veil across the stars?
 
I am the poor white, fooled and pushed apart,
I am the Negro bearing slavery's scars.
I am the red man driven from the land,
I am the immigrant clutching the hope I seek—
And finding only the same old stupid plan
Of dog eat dog, of mighty crush the weak.
 
I am the young man, full of strength and hope,
Tangled in that ancient endless chain
Of profit, power, gain, of grab the land!
Of grab the gold! Of grab the ways of satisfying need!
Of work the men! Of take the pay!
Of owning everything for one's own greed!
 
I am the farmer, bondsman to the soil.
I am the worker sold to the machine.
I am the Negro, servant to you all.
I am the people, humble, hungry, mean—
Hungry yet today despite the dream.
Beaten yet today—O, Pioneers!
I am the man who never got ahead,
The poorest worker bartered through the years.
 
Yet I'm the one who dreamt our basic dream
In the Old World while still a serf of kings,
Who dreamt a dream so strong, so brave, so true,
That even yet its mighty daring sings
In every brick and stone, in every furrow turned
That's made America the land it has become.
O, I'm the man who sailed those early seas
In search of what I meant to be my home—
For I'm the one who left dark Ireland's shore,
And Poland's plain, and England's grassy lea,
And torn from Black Africa's strand I came
To build a "homeland of the free."
 
The free?
 
Who said the free?  Not me?
Surely not me?  The millions on relief today?
The millions shot down when we strike?
The millions who have nothing for our pay?
For all the dreams we've dreamed
And all the songs we've sung
And all the hopes we've held
And all the flags we've hung,
The millions who have nothing for our pay—
Except the dream that's almost dead today.
 
O, let America be America again—
The land that never has been yet—
And yet must be—the land where every man is free.
The land that's mine—the poor man's, Indian's, Negro's, ME—
Who made America,
Whose sweat and blood, whose faith and pain,
Whose hand at the foundry, whose plow in the rain,
Must bring back our mighty dream again.
 
Sure, call me any ugly name you choose—
The steel of freedom does not stain.
From those who live like leeches on the people's lives,
We must take back our land again,
America!
 
O, yes,
I say it plain,
America never was America to me,
And yet I swear this oath—
America will be!
 
Out of the rack and ruin of our gangster death,
The rape and rot of graft, and stealth, and lies,
We, the people, must redeem
The land, the mines, the plants, the rivers.
The mountains and the endless plain—
All, all the stretch of these great green states—
And make America again! 
____
