
:toc:
:toclevels: 4 

==== Poems

===== St. Francis Prayer
[verse]
____
Lord, make me an instrument of Thy peace;
Where there is hatred, let me sow love;
Where there is injury, pardon;
Where there is error, truth;
Where there is doubt, faith;
Where there is despair, hope;
Where there is darkness, light;
And where there is sadness, joy. 
  
O Divine Master, Grant that I may not so much seek
To be consoled as to console;
To be understood as to understand;
To be loved as to love.
For it is in giving that we receive;
It is in pardoning that we are pardoned;
And it is in dying that we are born to eternal life.
____


===== Ulysses by Alfred Lord Tennyson
[verse]
____
It little profits that an idle king,
By this still hearth, among these barren crags,
Match'd with an aged wife, I mete and dole
Unequal laws unto a savage race,
That hoard, and sleep, and feed, and know not me.
I cannot rest from travel: I will drink
Life to the lees: All times I have enjoy'd
Greatly, have suffer'd greatly, both with those
That loved me, and alone, on shore, and when
Thro' scudding drifts the rainy Hyades
Vext the dim sea: I am become a name;
For always roaming with a hungry heart
Much have I seen and known; cities of men
And manners, climates, councils, governments,
Myself not least, but honour'd of them all;
And drunk delight of battle with my peers,
Far on the ringing plains of windy Troy.
I am a part of all that I have met;
Yet all experience is an arch wherethro'
Gleams that untravell'd world whose margin fades
For ever and forever when I move.
How dull it is to pause, to make an end,
To rust unburnish'd, not to shine in use!
As tho' to breathe were life! Life piled on life
Were all too little, and of one to me
Little remains: but every hour is saved
From that eternal silence, something more,
A bringer of new things; and vile it were
For some three suns to store and hoard myself,
And this gray spirit yearning in desire
To follow knowledge like a sinking star,
Beyond the utmost bound of human thought.
	
This is my son, mine own Telemachus,
To whom I leave the sceptre and the isle,—
Well-loved of me, discerning to fulfil
This labour, by slow prudence to make mild
A rugged people, and thro' soft degrees
Subdue them to the useful and the good.
Most blameless is he, centred in the sphere
Of common duties, decent not to fail
In offices of tenderness, and pay
Meet adoration to my household gods,
When I am gone. He works his work, I mine.

There lies the port; the vessel puffs her sail:
There gloom the dark, broad seas. My mariners,
Souls that have toil'd, and wrought, and thought with me—
That ever with a frolic welcome took
The thunder and the sunshine, and opposed
Free hearts, free foreheads—you and I are old;
Old age hath yet his honour and his toil;
Death closes all: but something ere the end,
Some work of noble note, may yet be done,
Not unbecoming men that strove with Gods.
The lights begin to twinkle from the rocks:
The long day wanes: the slow moon climbs: the deep
Moans round with many voices. Come, my friends,
'T is not too late to seek a newer world.
Push off, and sitting well in order smite
The sounding furrows; for my purpose holds
To sail beyond the sunset, and the baths
Of all the western stars, until I die.
It may be that the gulfs will wash us down:
It may be we shall touch the Happy Isles,
And see the great Achilles, whom we knew.
Tho' much is taken, much abides; and tho'
We are not now that strength which in old days
Moved earth and heaven, that which we are, we are;
One equal temper of heroic hearts,
Made weak by time and fate, but strong in will
To strive, to seek, to find, and not to yield.
____


===== Heaven—Haven: A nun takes the veil by Gerard Manley Hopkins
[verse]
____
I have desired to go
Where springs not fail,
To fields where flies no sharp and sided hail
And a few lilies blow.

And I have asked to be 
Where no storms come,
Where the green swell is in the havens dumb,
And out of the swing of the sea.
____


===== i carry your heart with me by E.E. Cummings
[verse]
____
i carry your heart with me (i carry it in
my heart) i am never without it (anywhere
i go you go, you go, my dear; and whatever is done
by only me is your doing, my darling)
	
i fear 
no fate (for you are my fate, my sweet) i want
no world (for beautiful you are my world, my true)
and it's you are whatever a moon has always meant
and whatever a sun will always sing is you

here is the deepest secret nobody knows
(here is the root of the root and the bud of the bud
and the sky of the sky of a tree called life; which grows
higher than soul can hope or mind can hide)
and this is the wonder that's keeping the stars apart

i carry your heart (i carry it in my heart)
____


===== Do Not Go Gentle Into That Good Night by Dylan Thomas
[verse]
____
Do not go gentle into that good night,
Old age should burn and rave at close of day;
Rage, rage against the dying of the light.

Though wise men at their end know dark is right,
Because their words had forked no lightning they
Do not go gentle into that good night.

Good men, the last wave by, crying how bright
Their frail deeds might have danced in a green bay,
Rage, rage against the dying of the light.

Wild men who caught and sang the sun in flight,
And learn, too late, they grieved it on its way,
Do not go gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Rage, rage against the dying of the light.

And you, my father, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not go gentle into that good night.
Rage, rage against the dying of the light. 
____


===== Ozymandias by Percy Bysshe Shelley
[verse]
____
I met a traveler from an antique land
Who said: 'Two vast and trunkless legs of stone
Stand in the desert. Near them, on the sand,
Half sunk, a shattered visage lies, whose frown,
And wrinkled lip, and sneer of cold command,
Tell that its sculptor well those passions read
Which yet survive, stamped on these lifeless things,
The hand that mocked them and the heart that fed.
And on the pedestal these words appear --
"My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!"
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.'
____

===== Desert Places by Robert Frost
[verse]
____
Snow falling and night falling fast, oh, fast
In a field I looked into going past,
And the ground almost covered smooth in snow,
But a few weeds and stubble showing last. 
	
The woods around it have it - it is theirs.
All animals are smothered in their lairs.
I am too absent-spirited to count;
The loneliness includes me unawares. 
	
And lonely as it is, that loneliness
Will be more lonely ere it will be less -
A blanker whiteness of benighted snow
With no expression, nothing to express. 
	
They cannot scare me with their empty spaces
Between stars - on stars where no human race is.
I have it in me so much nearer home
To scare myself with my own desert places. 
____


===== The Road Not Taken by Robert Frost
[verse]
____ 
Two roads diverged in a yellow wood, 
And sorry I could not travel both 
And be one traveler, long I stood 
And looked down one as far as I could 
To where it bent in the undergrowth; 
	
Then took the other, as just as fair, 
And having perhaps the better claim, 
Because it was grassy and wanted wear; 
Though as for that the passing there 
Had worn them really about the same, 
	
And both that morning equally lay 
In leaves no step had trodden black. 
Oh, I kept the first for another day! 
Yet knowing how way leads on to way, 
I doubted if I should ever come back. 

I shall be telling this with a sigh 
Somewhere ages and ages hence: 
Two roads diverged in a wood, and I— 
I took the one less traveled by, 
And that has made all the difference.
____


===== Girder by Nan Cohen 
[verse]
____
The simplest of bridges, a promise
that you will go forward,

that you can come back.
So you cross over.

It says you can come back.
So you go forward.

But even if you come back
then you must go forward.

I am always either going back
or coming forward. There is always

something I have to carry,
something I leave behind.

I am a figure in a logic problem,
standing on one shore

with the things I cannot leave,
looking across at what I cannot have. 
____


===== What if you slept ... by Samuel Coleridge
[verse]
____
What if you slept 
And what if 
In your sleep 
You dreamed 
And what if 
In your dream 
You went to heaven 
And there plucked a strange and beautiful flower 
And what if 
When you awoke 
You had that flower in you hand 
Ah, what then? 
____


===== about competition by Charles Bukowski
[verse]
____
the higher you climb
the greater the pressure.

those who manage to
endure
learn
that the distance
between the 
top and the 
bottom
is 
obscenely
great.

and those who
succeed
know 
this secret:
there isn't
one.
____


===== Nothing is Lost by Noel Coward
[verse]
____
Deep in our sub-conscious, we are told
Lie all our memories, lie all the notes
Of all the music we have ever heard
And all the phrases those we loved have spoken,
Sorrows and losses time has since consoled,
Family jokes, out-moded anecdotes
Each sentimental souvenir and token
Everything seen, experienced, each word
Addressed to us in infancy, before
Before we could even know or understand
The implications of our wonderland.
There they all are, the legendary lies
The birthday treats, the sights, the sounds, the tears
Forgotten debris of forgotten years
Waiting to be recalled, waiting to rise
Before our world dissolves before our eyes
Waiting for some small, intimate reminder,
A word, a tune, a known familiar scent
An echo from the past when, innocent
We looked upon the present with delight
And doubted not the future would be kinder 
And never knew the loneliness of night. 
____

	
===== Ars Poetica with Bacon by Terrence Hayes
[verse]
____
Fortunately, the family, anxious about its diminishing 
food supply, encountered a small, possibly hostile pig
along the way. The daughter happened upon it first
pushing its scuffed snout against something hidden 
at the base of a thornbush: a blood-covered egg, maybe, 
or small rubber ball exactly like the sort that snapped
from the paddle my mother used to beat me with 
when I let her down. At the time the father and mother 
were tangled in some immemorial dispute about cause 
and effect: who’d harmed whom first, how jealousy
did not, in fact, begin as jealousy but as desperation. 
When the daughter called out to them, they turned 
to see her lift the pig, it was no heavier than an orphan,
from the bushes and then set it down in their path. 
They waited to see whether the pig might idle forward 
with them until they made camp or wander back toward 
the home they’d abandoned to war. Night, enclosed 
in small drops of rain, began to fall upon them. 
“Consequence” is the word that splintered my 
mind.Walking a path in the dark is about something 
the way a family is about something. Like the pig, 
I too, wanted to reach through the thorns for the egg 
or ball, believing it was a symbol of things to come. 
I wanted to roll it in my palm like the head 
of a small redbird until it sang to me. I wanted 
to know how my mother passed her days having 
never touched her husband’s asshole, for example. 
Which parts of your body have never been touched, 
I wanted to ask. I’d been hired to lead the family 
from danger to a territory full of more seeds than bullets, 
but, truth was, in the darkness there was no telling 
what was rooting in the soil. Plots of complete silence, 
romantics posing in a field bludgeoned by shame. 
The heart, biologically speaking, is ugly as it pumps 
its passion and fear down the veins. Which is to say, 
starting out we have no wounds to speak of 
beyond the ways our parents expressed their love. 
We were never sure what the pig was after or whether 
it was, in fact, not a pig but some single-minded soul 
despair turned into a pig, some devil worthy of mercy. 
Without giving away the enigmatic ending, I will say, 
when we swallowed the flesh, our eyes were closed. 
____


===== Part One: Life, XXII by Emily Dickinson
[verse]
____
I had no time to hate, because
The grave would hinder me,
And life was not so ample I
Could finish enmity.

Nor had I time to love; but since            
Some industry must be,
The little toil of love, I thought,
Was large enough for me.
____


===== Part Four: Time and Eternity XXIII by Emily Dickinson
[verse]
____
I reason, earth is short,
And anguish absolute.
And many hurt;
But what of that?

I reason, we could die:        
The best vitality
Cannot excel decay;
But what of that?

I reason that in heaven
Somehow, it will be even,           
Some new equation given;
But what of that?
____


===== Part One: Life, XXVII, Compensation by Emily Dickinson
[verse]
____
For each ecstatic instant
We must an anguish pay
In keen and quivering ratio
To the ecstasy.

For each beloved hour
Sharp pittances of years,
Bitter contested farthings
And coffers heaped with tears.
____


===== Part Two: Life, XXXIII by Emily Dickinson
[verse]
____
I took my power in my hand.
And went against the world;
'T was not so much as David had,
But I was twice as bold.
I aimed my pebble, but myself
Was all the one that fell.
Was it Goliath was too large,
Or only I too small?
____


===== The Author Observes His Birthday by John Updike
[verse]
____
My life, my life with children, was a sluice
that channeled running water to my pan;
by tilting it, and swirling lightly, I
at end of day might find a fleck of gold.
____


===== Manfred by Lord George Gordon Byron
[verse]
____
Sorrow is knowledge: they who know the most
Must mourn the deepest o’er the fatal truth,
The Tree of Knowledge is not that of Life.
____


===== Childe Harold’s Pilgrimage by Lord George Gordon Byron
[verse]
____
There is a rapture on the lonely shore,
There is society, where none intrudes,
By the deep Sea, and music in its roar:
I love not Man the less, but Nature more,
From these our interviews, in which I steal
From all I may be, or have been before,
To mingle with the Universe and feel
What I can ne’er express, yet can not all conceal.
____


===== To Those Who Follow in Our Wake by Bertolt Brecht
[verse]
____
I
Truly, I live in dark times!
An artless word is foolish. A smooth forehead
Points to insensitivity. He who laughs
Has not yet received
The terrible news.

What times are these, in which
A conversation about trees is almost a crime
For in doing so we maintain our silence about so much wrongdoing!
And he who walks quietly across the street,
Passes out of the reach of his friends
Who are in danger?

It is true: I work for a living
But, believe me, that is a coincidence. Nothing
That I do gives me the right to eat my fill.
By chance I have been spared. (If my luck does not hold,
I am lost.)

They tell me: eat and drink. Be glad to be among the haves!
But how can I eat and drink
When I take what I eat from the starving
And those who thirst do not have my glass of water?
And yet I eat and drink.

I would happily be wise.
The old books teach us what wisdom is:
To retreat from the strife of the world
To live out the brief time that is your lot
Without fear
To make your way without violence
To repay evil with good —
The wise do not seek to satisfy their desires,
But to forget them.
But I cannot heed this:
Truly I live in dark times!

II

I came into the cities in a time of disorder
As hunger reigned.
I came among men in a time of turmoil
And I rose up with them.
And so passed
The time given to me on earth.

I ate my food between slaughters.
I laid down to sleep among murderers.
I tended to love with abandon.
I looked upon nature with impatience.
And so passed
The time given to me on earth.

In my time streets led into a swamp.
My language betrayed me to the slaughterer.
There was little I could do. But without me
The rulers sat more securely, or so I hoped.
And so passed
The time given to me on earth.

The powers were so limited. The goal
Lay far in the distance
It could clearly be seen although even I
Could hardly hope to reach it.
And so passed
The time given to me on earth.

III

You, who shall resurface following the flood
In which we have perished,
Contemplate —
When you speak of our weaknesses,
Also the dark time
That you have escaped.

For we went forth, changing our country more frequently than our shoes
Through the class warfare, despairing
That there was only injustice and no outrage.

And yet we knew:
Even the hatred of squalor
Distorts one’s features.
Even anger against injustice
Makes the voice grow hoarse. We
Who wished to lay the foundation for gentleness
Could not ourselves be gentle.

But you, when at last the time comes
That man can aid his fellow man,
Should think upon us
With leniency.
____


===== The black poet would love to say this century began by Terrence Hayes
[verse]
____
The black poet would love to say his century began
With Hughes or, God forbid, Wheatley, but actually
It began with all the poetry weirdos & worriers, warriors,
Poetry whiners & winos falling from ship bows, sunset
Bridges & windows. In a second I’ll tell you how little
Writing rescues. My hunch is that Sylvia Plath was not
Especially fun company. A drama queen, thin-skinned,
And skittery, she thought her poems were ordinary.
What do you call a visionary who does not recognize
Her vision? Orpheus was alone when he invented writing.
His manic drawing became a kind of writing when he sent
His beloved a sketch of an eye with an X struck through it.
He meant I am blind without you. She thought he meant
I never want to see you again. It is possible he meant that, too.
____


===== Sometimes the father almost sees looking by Terrence Hayes
[verse]
____
Sometimes the father almost sees looking
At the son, how handsome he'd be if half
His own face was made of the woman he loved.
He almost sees in his boy's face, an openness
Like a wound before it scars, who he was
Long before his name was lost, the trail
To his future on earth long before he arrived.
To be dead & alive at the same time.
A son finds his father handsome because
The son can almost see how he might
Become superb as the scar above a wound.
And because the son can see who he was
Long before he had a name, the trace of
His future on earth long before he arrived.
____


===== When Dean Young Talks About Wine by Tony Hoagland
[verse]
____
The worm thrashes when it enters the tequila.
The grape cries out in the wine vat crusher.

But when Dean Young talks about wine, his voice is strangely calm.
Yet it seems that wine is rarely mentioned.

He says, Great first chapter but no plot.
He says, Long runway, short flight.
He says, This one never had a secret.
He says, You can't wear stripes with that.

He squints as if recalling his childhood in France.
He purses his lips and shakes his head at the glass.

Eight-four was a naughty year, he says,
and for a second I worry that California has turned him
into a sushi-eater in a cravat.

Then he says,
This one makes clear the difference
between a thoughtless remark
and an unwarranted intrusion.

Then he says, In this one the pacific last light of afternoon
stains the wings of the seagull pink
at the very edge of the postcard.

But where is the Cabernet of rent checks and asthma medication?
Where is the Burgundy of orthopedic shoes?
Where is the Chablis of skinned knees and jelly sandwiches?
with the aftertaste of cruel Little League coaches?
and the undertone of rusty stationwagon?

His mouth is purple as if from his own ventricle
he had drunk.
He sways like a fishing rod.

When a beast is hurt it roars in incomprehension.
When a bird is hurt it huddles in its nest.

But when a man is hurt,
he makes himself an expert.
Then he stands there with a glass in his hand
staring into nothing
as if he were forming an opinion.
____


===== The Parable of Perfect Silence by Christian Wiman
[verse]
____
Today I woke and believed in nothing.
A grief at once intimate and unfelt,
like the death of a good friend’s dog.

Tired of the mind reaching back in the past for rescue
I praise the day.
I don’t mean merely some mythical, isolate instant
like the mindless mindfulness specialist
who at the terminal cancer convention
(not that it was called that)
exhorted the new year’s crop of slaughters
(ditto)
to “taste” the day, this one unreplicable instant of being alive.
(The chicken glistened.)
Nor do I mean a day devoid of past and future
as craved that great craze of minds and times Fernando Pessoa,
who wanted not “the present” but reality itself,
things in their thingness rather than the time that measures them.
Time is in the table at which I sit and in the words I type.
In the red-checked shirt my father’s mother used to wear
when she was gardening and which I kept
because it held her smell (though it does no longer)
there is still plenty of time.

Two murderers keep their minds alive
while they wait to die.
They talk through slots in their doors
of whatever mercy or misery
the magazine has ordained for the day — 
the resurgence of the Taliban in Afghanistan, say,
ten signs that a relationship is on the rocks.
When their communion flags, as communions will,
they rekindle it with personal revelations, philosophical digressions,
humor. This is a true story,
one of them says sometimes by way of preface,
as if that gave the moment more gravity,
asked of the listener a different attention,
at once resisted and reinforced an order
wherein every hour has its sound, every day its grace,
and every death is by design.

“Love is possible for anyone,” I hear the TV talk-show host say,
which is true in the way most things in this life are true,
which is to say, false,
unless and until the nullifying, catalyzing death is felt.
Love is possible for anyone
because it is equally impossible for everyone.
To be is to be confronted with a void,
a blankness, a blackness that both appeals and appalls.
Once known — known by the void, I mean — one has three choices.
Walk away, and unlearn the instinct of awe.
Walk along, and learn to believe that awe asks nothing of you.
Are you with me, love?

(For love read faith.)

Naked once and after a rat, my father cried, “Die, vermin, die!”
banging the broomstick over and over on the floor
so incorrigibly dirty it might as well have been the earth itself.
This is my mother’s story, though I was there, I’m told,
and no small part of the pandemonium.
We were five souls crammed into one life,
and so incorrigibly poor — or was that fear? — we all slept in one room
and shared one great big chester drawers, as we called it,
and not with irony but in earnest ignorance,
just as like meant lack, as in
“How much do you like bein’ done with your chemo?”
and just as I and every other child I knew,
before we tucked into our lemon meringue pie,
solemnly wiped the calf slobbers off.
Ah, local color, peasant levity, the language fuming and steaming
rich as the mist of rot that rises off the compost heap
(“kitchen midden,” you might hear an old Scot still say).
When do we first know? That there’s a world
to which we’ve been, not oblivious, exactly,
but so inside we couldn’t see it, who now see nothing else?
Heaven is over. Or hell.
Did you forget the rat?
It thumps and thrashes like a poltergeist inside
the chest of drawers but somehow, though my father is fast,
and though his rage is becoming real, every drawer he opens
is empty. What happens when we die,
every child of every father eventually asks.
What happens when we don’t
is the better question.

To kill a wasp on water is the peak of speed.
My brother who is other has a mind of lead.
I with my stinging griefs watch from away.
How can it be there are no adults left?
What matters here is timing, not time.
His hand is high and white above the blue.
A wasp is also atom and urge, hover and touch.
Even wings are not a clean distinction.
Down comes the slap like a rifle shot.
What vengeance can there be on blank necessity?
My brother who is other has a way.
His hand is high and white. And then it’s not.

Once when my father’s mother’s health was failing
and she found it more and more difficult to tend
to the tiny family plot at Champion, Texas,
which is less town than time at this point,
a blink of old buildings and older longings the rare driver
flashes past, I took it upon myself to salt the graves
as I must have read somewhere would work for unwanted growths.
As indeed it did.
In the months after, every Sunday when we spoke,
she thanked me for the blankness, the blackness,
(my words, of course)
this new ease I had allowed her mind.
Until one day leaning over with flowers the leached earth
opened and my eighty-year-old grandmother
tumbled right down among the bones
of the woman from whom she’d first emerged.
To see that image you have to be that sky.
It has to happen in you, that crushing calling viewless blue
that is so deeply in you that it is not you.
“O, Law’, honey, I like to died.”

You don’t climb out of poverty so much as carry it with you.
Some shell themselves with wealth.
Some get and spend, get and spend, skimming existence like a Jesus lizard.
But for those whose souls have known true want
— whose souls perhaps are true want — 
money remains, in some sense, permanently inert,
like an erotic thought that flashes through a eunuch’s brain.
In 1980 my father bought his first airplane,
a scream-proof four-seater we crammed five inside,
which he considerately slammed into a sorghum field alone.
Unkillable, he killed the next ten years with work and wives,
then bought another, and brought it down in the solitary fire
that was his aspect and atmosphere. Homes, schemes,
thirty years of savings plowed into a sign company (!)
that did not, it turned out, exist.
A hole is hard to carry.

People ask if I believe in God and the verb is tedious to me.
Not wrong, not offensive, not intrusive, not embarrassing.
Tedious.
Today I saw a hawk land on Elizabeth’s chimney.
It sat with its bone frown and banker’s breast
above the proud houses of Hamden.
Are you with me? Then see,
too, a lump of animate ash rising from the flue
(or so it seems) to be a pigeon
fluttering dumbly down
next to that implacable raptor,
suddening a world of strange relations
wherein there is no need for fear, or far,
or meat.

There was a man made of airplane parts,
one of which was always missing.
He wandered the hospital grounds in search of a rudder,
an aileron, or some other fragment
that would let him fly from this place
where he was not meant to be.
There was a woman who emitted invective
ceaselessly, dispassionately, an obscenity machine.
One timid gentleman saved Saran wrap for five full years
and every night wrought an ever-more-solid ball
with which, it turned out, he planned to bash the skull
of the first soul he saw the dawn God blessed his weapon.
(A success story, alas.)
Another man with anvil hands sat six months of nights in faith
that there would come occasion of darkness, unguardedness, and vision
sufficient to rip from its socket one of my father’s bright blue eyes.
(Ditto.)
My father moved among them like a father.
He attended and pacified, he instructed and consoled.
Late to the trade, he worked too much,
and trusted his heart, no doubt, more than he should,
but was, by all accounts, at this one thing, and despite the end, good.

For love read faith
into these lines that so obviously lack it.
For love let words turn to life
in the way life turns to world
under the observer’s eye, the swirl
of particles with their waves and entanglements,
their chance and havoc, resolving
into some one thing:
a raptor on a rooftop, say.
No power on earth can make it stay.
But is it lost or released into formlessness
when we look away?

To be is to believe
that the man or woman
who inscribed with an idiosyncratic but demanding calligraphy
Fuck da money — Trust no one
on the rough blanket of the residential motel
where my father spent the last two years of his rough residential life
intended the note of defiant, self-conscious (da!) humor
that left my father, whom I had not seen in years,
and I, whom years had seen grow sere, far even from myself,
erupting in laughter until we cried.

Before my good friend’s good dog died
ten times a day she pressed her forehead to his
“to confirm the world and her place in it.”
Now she won’t even say his name.
Strange how the things that burn worst in one heart
one must keep silent to keep.

Ten to one you thought of men.
The murderers, I mean.
But no. This is a true story.
There is another cell, you see,
in which a woman I have known since childhood,
and since childhood have known to be
suspended on a wire of time but nimble-witted nonetheless,
lies on the cold stone floor.
She is even more naked than they have made her.
She has killed no one not even herself.
Punishment, perhaps, or some contagion of fate, finds her here,
her hair shorn, both wrists wrapped, her eyes open,
pondering the parable of perfect silence.

Remember, he said, memory is a poor man’s prison.
Make to have and to love one live infinitive,
then blessed my brow with the sign of the cross.
I woke without a chance to ask the obvious:
But what if all our songs are songs of loss?

I felt nothing when you died, Father.
(As if I ever called you that.)
It is a long cold seep, this grief.
The day itself was hot enough to make the devil sweat,
as more than one person, with less than one mind, muttered to me.
What I remember: two children, too tan
and “clad in famine” (Dahlberg), look up
from their parched front yard,
their sad little sprinkler like a flower of hell.
I don’t mean I saw them, though I did.
I mean they are what I remember, fleshed.
That town. A hint of new prison business,
and the Square’s been rewhitened,
but mostly it’s beastly, a blast site,
our old house less house than nest,
and even the undertaker, a friend
from high school, has graduated to heroin.
You would have been right at home,
and I guess in a ghoulish way you were,
overdressed, overdosed, over.
Hard wind at the graveside. Hard lives hardly there.
The canopy whipped and flapped.
A bouquet skipped over the graves like a strange elation.
Something stuck, and an ageless Indian
(he might have been Mom’s long-dead granddad)
nimbled over the casket’s contraptions to make it go. You go
into the ground again, and the silence assaults
like heat, and the clumps of would-be grievers unclump
and head for cars, and Mom cracks
a tallboy and two jokes before we’re on the highway.
The first I forget, and of the second I recall only a nakedness, and wild crying,
and a rat.

When the doctor said I’d likely die I thought of my father
telling me he’d learned to read a cancer look,
that some people had it before they had it, so to speak.
When the young guard demanded to unwrap the Snickers
I’d bought for my sister my father scoffed:
“All this energy expended on candy when you could take this can”
— he held her Coke up in front of our eyes — “and cut a throat.”
When my sister, chewing her chocolate with ravenous indifference,
paused and stared balefully off at the even more baleful brown
beyond the barbed wire, it did not occur to me
that it was inspiration. When I began writing these lines
it was not, to be sure, inspiration but desperation,
to be alive, to believe again in the love of God.
The love of God is not a thing one comprehends
but that by which — and only by which — one is comprehended.
It is like the child’s time of pre-reflective being,
and like that time, we learn it by its lack.
Flashes and fragments, flashes and fragments,
these images are not facets of some unknowable whole
but entire existences in themselves, like worlds
that under God’s gaze shear and shear and, impossibly, are:
untouching, entangled, sustained, free.
If all love demands imagination, all love demands withdrawal.
We must create the life creating us, and must allow that life to be — 
and to be beyond, perhaps, whatever we might imagine.
I, too, am more (and less)
than anything I imagine myself to be.
“To know this,” says Simone Weil, “is forgiveness.”

It is an air you enter, not an act you make.
It is the will’s frustration, and is the will’s fruition.
It is to wade a blaze one night that I once crossed
— a young man, and lost — 
to find a woman made of weather
sweeping the street in front of her shack.
It is another country.
It is a language I don’t know.
La por allá, la por allá, I repeat in my sleep.
The over there.

Tired of the mind reaching back in the past for rescue
I praise the day
my father woke in the motel room where all five of us were sleeping,
which is not even past but a flame as I say it,
and see it, the little lighter now he is using to find his clothes.
I who have not slept in forty-five years am awake for the first time
rising carefully out of my pallet on the floor
and feeling my way beyond the bodies of my brother and sister
toward the shade that is my father
to stand in this implausible light where to whisper would be too much,
and anyway what’s next is known, Dad, and near,
the nowhere diner, hot chocolate and the funny pages,
and the consolation that comes when there is nothing to console.
____


===== Childhood’s Retreat by Robert Duncan
[verse]
____
It’s in the perilous boughs of the tree
out of blue sky    the wind
sings loudest surrounding me.

And solitude,   a wild solitude
’s reveald,   fearfully,   high     I’d climb
into the shaking uncertainties,

part out of longing,   part     daring my self,
part to see that
widening of the world,   part

to find my own, my secret
hiding sense and place, where from afar
all voices and scenes come back

—the barking of a dog,   autumnal burnings,
far calls,   close calls—   the boy I was
calls out to me
here the man where I am   “Look!

I’ve been where you
most fear to be.”
____


===== As Planned by Frank O'Hara
[verse]
____
After the first glass of vodka
you can accept just about anything
of life even your own mysteriousness
you think it is nice that a box
of matches is purple and brown and is called
La Petite and comes from Sweden
for they are words that you know and that
is all you know words not their feelings
or what they mean and you write because
you know them not because you understand them
because you don't you are stupid and lazy
and will never be great but you do
what you know because what else is there?
____


===== Comfort Animal by Joy Ladin
[verse]
____
A voice says, “Your punishment has ended.”
You never listen to that voice. You really suck
at being comforted.

Another voice says, “Cry.”
That voice always gets your attention,
keeps you thinking

about withered flowers and withering grass
and all the ways you’re like them.
Hard to argue with that.

Death tramples you, an un-housebroken pet
trailing prints and broken stems,
pooping anxiety, PTSD, depression.

It’s better to be animal than vegetable
but best of all is to be spirit
flying first or maybe business class

with your emotional support animal, your body,
curled in your lap, soaring with you
above the sense of loss you’ve mistaken

for the closest to God you can get.
You want to cry? Cry about that.
Who do you think created

the animals to whom you turn for comfort,
dogs, miniature horses, monkeys, ferrets,
hungers you know how to feed,

fears you know how to quiet?
I form them, fur them,
it’s my warmth radiating from their bodies,

my love that answers
the love you lavish upon them.
Your deserts and desolations

are highways I travel,
smoothing your broken places,
arranging stars and constellations

to light your wilderness.
Sometimes I play the shepherd;
sometimes I play the lamb;

sometimes I appear as death,
which makes it hard to remember
that I am the one who assembled your atoms,

who crowned your dust with consciousness.
I take you everywhere,
which is why, wherever you go, I’m there,

keeping you hydrated, stroking your hair,
laughing when you chase your tail,
gathering you to my invisible breasts

more tenderly than any mother.
You’re right—you never asked for this. I’m the reason
your valleys are being lifted up,

the source of your life laid bare.
Mine is the voice that decrees—
that begs—your anguish to end.

When you suffer, I suffer.
Comfort me
by being comforted.
____


===== Thinking by Rocket Caleshu
[verse]
____
I am thinking that
to make thinking new again
is torch-lit work, subterranean

and exalted. Antarctica, Goethe,
Methuselah. Seven hills of Rome.
An advertisement for a summer farming gig

on a homestead in Alaska puzzles me:
imagine harvesting kale through days
of unrepentant 24-hour sunlight,

covered in mosquitoes. How do you do
the things in the dark when there is no dark?
I want now to tell you abt my love

for my whip, for killing the engine and sitting
in the garage. This is also an ancient
practice.
____


===== Silhouettes by Kien Lam
[verse]
____
A crow perches inside me.

Actually, it is a whale. It is hard to tell
by touch alone. Nothing I own ever looks
me properly in the eye. Sometimes

a loud caw at dusk feels
like the largest mammal on Earth.

A deep breath out the blowhole

into my stomach. One second it swims
and the next it is a small extension
of a tree. This is a kind of beginning—

a finger puppet show. The light
dancing around my hands.

Me dancing alone on a stem.

A persimmon blooms.
A boy learns a song and plants it
in an orchard. Inside of me

the large creatures change their shapes
to fit. A blackbird. An organ.

Animals with no names. I send them off
into the world daily. Little sadness
takes flight. Love is a brave child.

These things take the shape
of their containers.

I don’t have to do anything
to hold them.
____


===== Honeymoon by Brenda Shaughnessy
[verse]
____
It’s so flat here you can see everything. It’s not romantic. Nobody can slip in or out in secret, and who among us has pumped the last worry through her heart?

Collapsing into shade, I wish for more sons, endless daughters: a higher ratio of my people to other people. Why not want what I want; since we used all the air conditioning it’s become impossible to think things through.

Can you believe your ears? All the electric music in the world has been turned into handbells. I wish I had a cushion for my knees instead of gloves to keep the handbells pure. We can get used to anything. That doesn’t mean we should.

I went to a wedding where everything was outrageous but trying to act modest by including very goofy elements, such as people in bear costumes and gold nuggets descending from the ceiling, only to be jerked back up out of reach when people tried to grab them.

Long ago, a matrimonial family collected a few eggs from each household in the village to contribute to the wedding cake. A pig for the dinner: a gift from a rich great-uncle. Shortly after, there was a period of department store gift services and electro-synth harps for hire.

But now we pick dandelions to make wine, and pluck chickens to make fine the groom’s cloak. He wants large brown wings; he wants wolf pelt for his loins. He wants he wants he wants. There is no end to that.

The bride is someone who has only ever served. No use asking someone who’s once had a true taste of freedom, whose eyes widened and whose pelvis thrust up unbidden. Better she be someone who might never know what she lost.

It is as it ever was. How many centuries have brides been made and used in this way?

How few centuries have let women be girls first, swirling as long as they wanted into their sweetness and sharpening to ripeness, only becoming women once full heavy love was their desire inside and out. Maybe one. Maybe not quite one full century.
____


===== Among Every Three Fathers, One Will by Jennifer Tseng
[verse]
____
It is a hall of patience. For eyes. For ears. Now it is dark and the urge I have had so often to turn the pictures toward the wall has vanished. The dark takes care of everything. I am a girl who plays piano for seven hours with a metronome clacking behind the tune like a clock, so that when at last the dark comes, I am tired. My back is tired of straightening, my feet are tired of pedaling, and my hands, my tiny horses, have galloped for miles. If I said  hall  I meant tunnel. If I said  play I meant  pray. If I said  father  I meant memory. If I said God  I meant world, I meant will.
____


===== The Snow Man by Wallace Stevens
[verse]
____
One must have a mind of winter
To regard the frost and the boughs
Of the pine-trees crusted with snow;

And have been cold a long time
To behold the junipers shagged with ice,
The spruces rough in the distant glitter

Of the January sun; and not to think
Of any misery in the sound of the wind,
In the sound of a few leaves,

Which is the sound of the land
Full of the same wind
That is blowing in the same bare place

For the listener, who listens in the snow,
And, nothing himself, beholds
Nothing that is not there and the nothing that is.
____


===== Let America Be America Again by Langston Hughes
[verse]
____
Let America be America again.
Let it be the dream it used to be.
Let it be the pioneer on the plain
Seeking a home where he himself is free.
 
(America never was America to me.)
 
Let America be the dream the dreamers dreamed—
Let it be that great strong land of love
Where never kings connive nor tyrants scheme
That any man be crushed by one above.
 
(It never was America to me.)
 
O, let my land be a land where Liberty
Is crowned with no false patriotic wreath,
But opportunity is real, and life is free,
Equality is in the air we breathe.
 
(There's never been equality for me,
Nor freedom in this "homeland of the free.")
 
Say, who are you that mumbles in the dark?
And who are you that draws your veil across the stars?
 
I am the poor white, fooled and pushed apart,
I am the Negro bearing slavery's scars.
I am the red man driven from the land,
I am the immigrant clutching the hope I seek—
And finding only the same old stupid plan
Of dog eat dog, of mighty crush the weak.
 
I am the young man, full of strength and hope,
Tangled in that ancient endless chain
Of profit, power, gain, of grab the land!
Of grab the gold! Of grab the ways of satisfying need!
Of work the men! Of take the pay!
Of owning everything for one's own greed!
 
I am the farmer, bondsman to the soil.
I am the worker sold to the machine.
I am the Negro, servant to you all.
I am the people, humble, hungry, mean—
Hungry yet today despite the dream.
Beaten yet today—O, Pioneers!
I am the man who never got ahead,
The poorest worker bartered through the years.
 
Yet I'm the one who dreamt our basic dream
In the Old World while still a serf of kings,
Who dreamt a dream so strong, so brave, so true,
That even yet its mighty daring sings
In every brick and stone, in every furrow turned
That's made America the land it has become.
O, I'm the man who sailed those early seas
In search of what I meant to be my home—
For I'm the one who left dark Ireland's shore,
And Poland's plain, and England's grassy lea,
And torn from Black Africa's strand I came
To build a "homeland of the free."
 
The free?
 
Who said the free?  Not me?
Surely not me?  The millions on relief today?
The millions shot down when we strike?
The millions who have nothing for our pay?
For all the dreams we've dreamed
And all the songs we've sung
And all the hopes we've held
And all the flags we've hung,
The millions who have nothing for our pay—
Except the dream that's almost dead today.
 
O, let America be America again—
The land that never has been yet—
And yet must be—the land where every man is free.
The land that's mine—the poor man's, Indian's, Negro's, ME—
Who made America,
Whose sweat and blood, whose faith and pain,
Whose hand at the foundry, whose plow in the rain,
Must bring back our mighty dream again.
 
Sure, call me any ugly name you choose—
The steel of freedom does not stain.
From those who live like leeches on the people's lives,
We must take back our land again,
America!
 
O, yes,
I say it plain,
America never was America to me,
And yet I swear this oath—
America will be!
 
Out of the rack and ruin of our gangster death,
The rape and rot of graft, and stealth, and lies,
We, the people, must redeem
The land, the mines, the plants, the rivers.
The mountains and the endless plain—
All, all the stretch of these great green states—
And make America again! 
____


===== Friendship After Love by Ella Wheeler Wilcox
[verse]
____
After the fierce midsummer all ablaze 
    Has burned itself to ashes, and expires 
    In the intensity of its own fires, 
There come the mellow, mild, St. Martin days 
Crowned with the calm of peace, but sad with haze. 
    So after Love has led us, till he tires 
    Of his own throes, and torments, and desires, 
Comes large-eyed friendship: with a restful gaze, 
He beckons us to follow, and across 
    Cool verdant vales we wander free from care. 
    Is it a touch of frost lies in the air? 
Why are we haunted with a sense of loss? 
We do not wish the pain back, or the heat; 
And yet, and yet, these days are incomplete.
____


===== Solitude by Ella Wheeler Wilcox
[verse]
____
Laugh, and the world laughs with you;
Weep, and you weep alone;
For the sad old earth must borrow its mirth,
But has trouble enough of its own.
Sing, and the hills will answer;
Sigh, it is lost on the air;
The echoes bound to a joyful sound,
But shrink from voicing care.

Rejoice, and men will seek you;
Grieve, and they turn and go;
They want full measure of all your pleasure,
But they do not need your woe.
Be glad, and your friends are many;
Be sad, and you lose them all,—
There are none to decline your nectared wine,
But alone you must drink life’s gall.

Feast, and your halls are crowded;
Fast, and the world goes by.
Succeed and give, and it helps you live,
But no man can help you die.
There is room in the halls of pleasure
For a large and lordly train,
But one by one we must all file on
Through the narrow aisles of pain.
____


===== Dilemma by David Budbill
[verse]
____
I want to be
         famous
 so I can be
         humble
 about being
         famous.

 What good is my
         humility
 when I am
         stuck
 in this
         obscurity?
____


===== Marriage by Lawrence Raab
[verse]
____
Years later they find themselves talking   
about chances, moments when their lives   
might have swerved off
for the smallest reason.
                                     What if
I hadn’t phoned, he says, that morning?   
What if you’d been out,
as you were when I tried three times   
the night before?
                           Then she tells him a secret.   
She’d been there all evening, and she knew   
he was the one calling, which was why   
she hadn’t answered.
                               Because she felt—
because she was certain—her life would change   
if she picked up the phone, said hello,   
said, I was just thinking
of you.
            I was afraid,
she tells him. And in the morning   
I also knew it was you, but I just   
answered the phone
                            the way anyone
answers a phone when it starts to ring,   
not thinking you have a choice.
____


===== What We Miss by Sarah Manguso
[verse]
____
Who says it's so easy to save a life? In the middle of an interview for
the job you might get you see the cat from the window of the seven-
teenth floor just as he's crossing the street against traffic, just as
you're answering a question about your worst character flaw and lying
that you are too careful. What if you keep seeing the cat at every
moment you are unable to save him? Failure is more like this than like 
duels and marathons. Everything can be saved, and bad timing pre-
vents it. Every minute, you are answering the question and looking 
out the window of the church to see your one great love blinded by
the glare, crossing the street, alone. 
____


===== Advice To A Girl by Sarah Tessdale
[verse]
____
No one worth possessing
Can be quite possessed;
Lay that on your heart,
My young angry dear;
This truth, this hard and precious stone,
Lay it on your hot cheek,
Let it hide your tear.
Hold it like a crystal
When you are alone
And gaze in the depths of the icy stone.
Long, look long and you will be blessed:
No one worth possessing
Can be quite possessed.
____


===== [My brother's in Wyoming . . .] by Gary Young
[verse]
____
My brother's in Wyoming, and I've had that dream again. We're fishing. The trout rise, take our bait, and keep rising. In love once with a woman, and with my own capacity for pain, I fell in with some cowboys, and broke my neck riding bulls in a little rodeo. That night, drunk in the bunkhouse, not knowing how badly I'd been hurt, I thought it can't get worse than this, but I was wrong. That was twenty years ago. Thunder rolls down South Fork Canyon. The Milky Way is a great river overhead. My brother is in Wyoming. I miss him more than ever when he's there.
____


===== In My Craft or Sullen Art by Dylan Thomas
[verse]
____
In my craft or sullen art
Exercised in the still night
When only the moon rages
And the lovers lie abed
With all their griefs in their arms,
I labour by singing light
Not for ambition or bread
Or the strut and trade of charms
On the ivory stages
But for the common wages
Of their most secret heart.
Not for the proud man apart
From the raging moon I write
On these spindrift pages
Nor for the towering dead
With their nightingales and psalms
But for the lovers, their arms
Round the griefs of the ages,
Who pay no praise or wages
Nor heed my craft or art.
____


===== What We Want by Linda Pastan
[verse]
____
What we want
is never simple.
We move among the things
we thought we wanted:
a face, a room, an open book
and these things bear our names--
now they want us.
But what we want appears
in dreams, wearing disguises.
We fall past,
holding out our arms
and in the morning
our arms ache.
We don't remember the dream,
but the dream remembers us.
It is there all day
as an animal is there
under the table,
as the stars are there
even in full sun. 
____


===== Those Winter Sundays by Robert Hayden
[verse]
____
Sundays too my father got up early
and put his clothes on in the blueblack cold,
then with cracked hands that ached
from labor in the weekday weather made
banked fires blaze. No one ever thanked him.

I’d wake and hear the cold splintering, breaking.
When the rooms were warm, he’d call,
and slowly I would rise and dress,
fearing the chronic angers of that house,

Speaking indifferently to him,
who had driven out the cold
and polished my good shoes as well.
What did I know, what did I know
of love’s austere and lonely offices?
____


===== Hailstorm, 1965 by Twyla Hansen
[verse]
____
     Q: What is the largest hailstone in the US?
     A: There have been six reports of hailstones eight inches in diameter.
         -The Weather Channel 

It was the summer I turned sixteen, one brother
was soon to be married and we'd sold the farm.
I remember wanting desperately to be kissed.

Everything wavered on some kind of edge, elm trees
a graceful dome over the dusty streets. Nothing to warn,
only cumulonimbus clouds in the afternoon, intense up—

drafts, sky hazed sulfur-green, hail starting as crystalline
seeds that grew to marble-size, geometrically then,
to the size of softballs, clattering heavy against metal,

wood, glass, against the only small world we knew.
All the west windows in the high school, every roof, 
field corn stripped down to stubs, lives shattered

that day by crop failure, gouges, even holes in the ground.
There had never been any guarantee. Always there is
a risk, a gamble, hard choices to make. My oldest brother

and I scooped out stones that ripped through
the ragtop of his '62 Impala. I can't imagine hail the size
of a melon. Somehow that day I sensed that youth

had dissipated, that through the vapor of downed leaves
and broken branches, there would always be another crisis,
and another close call, and yet there was something more out there

circling, the open road where I drove west—my oldest brother dozing 
in the passenger's seat, my learners permit in tow—eighty on I-90
toward Missoula, toward the end of what we know now as innocence.
____


===== The Undeniable Pressure of Existence by Patricia Fargnoli
[verse]
____

I saw the fox running by the side of the road
past the turned-away brick faces of the condominiums
past the Citco gas station with its line of cars and trucks
and he ran, limping, gaunt, matted dull haired
past Jim's Pizza, past the Wash-O-Mat,
past the Thai Garden, his sides heaving like bellows
and he kept running to where the interstate
crossed the state road and he reached it and he ran on
under the underpass and beyond it past the perfect
rows of split-levels, their identical driveways
their brookless and forestless yards,
and from my moving car, I watched him,
helpless to do anything to help him, certain he was beyond
any aid, any desire to save him, and he ran loping on,
far out of his element, sick, panting, starving,
his eyes fixed on some point ahead of him, 
some possible salvation
in all this hopelessness, that only he could see.
____


===== Ah Poverties, Wincings, and Sulky Retreats by Walt Whitman
[verse]
____
Ah poverties, wincings, and sulky retreats,
Ah you foes that in conflict have overcome me,
(For what is my life or any man's life but a conflict with foes,
    the old, the incessant war?)
You degredations, you tussle with passions and appetites,
You smarts from dissatisfied friendships, (ah wounds the 
    sharpest of all!)
You toil of painful and choked articulations, you meannesses,
You shallow tongue-talks at tables, (my tongue the shallowest of
    any;)
You broken resolutions, you racking angers, you smother'd
    ennuis!
Ah think not you finally triumph, my real self has yet to come
    forth,
It shall yet march forth o'ermastering, till all lies beneath me,
It shall yet stand up the soldier of ultimate victory.
____


===== Birches by Robert Frost
[verse]
____
When I see birches bend to left and right
Across the lines of straighter darker trees,
I like to think some boy's been swinging them.
But swinging doesn't bend them down to stay
As ice-storms do. Often you must have seen them
Loaded with ice a sunny winter morning
After a rain. They click upon themselves
As the breeze rises, and turn many-colored
As the stir cracks and crazes their enamel.
Soon the sun's warmth makes them shed crystal shells
Shattering and avalanching on the snow-crust—
Such heaps of broken glass to sweep away
You'd think the inner dome of heaven had fallen.
They are dragged to the withered bracken by the load,
And they seem not to break; though once they are bowed
So low for long, they never right themselves:
You may see their trunks arching in the woods
Years afterwards, trailing their leaves on the ground
Like girls on hands and knees that throw their hair
Before them over their heads to dry in the sun.
But I was going to say when Truth broke in
With all her matter-of-fact about the ice-storm
I should prefer to have some boy bend them
As he went out and in to fetch the cows—
Some boy too far from town to learn baseball,
Whose only play was what he found himself,
Summer or winter, and could play alone.
One by one he subdued his father's trees
By riding them down over and over again
Until he took the stiffness out of them,
And not one but hung limp, not one was left
For him to conquer. He learned all there was
To learn about not launching out too soon
And so not carrying the tree away
Clear to the ground. He always kept his poise
To the top branches, climbing carefully
With the same pains you use to fill a cup
Up to the brim, and even above the brim.
Then he flung outward, feet first, with a swish,
Kicking his way down through the air to the ground.
So was I once myself a swinger of birches.
And so I dream of going back to be.
It's when I'm weary of considerations,
And life is too much like a pathless wood
Where your face burns and tickles with the cobwebs
Broken across it, and one eye is weeping
From a twig's having lashed across it open.
I'd like to get away from earth awhile
And then come back to it and begin over.
May no fate willfully misunderstand me
And half grant what I wish and snatch me away
Not to return. Earth's the right place for love:
I don't know where it's likely to go better.
I'd like to go by climbing a birch tree,
And climb black branches up a snow-white trunk
Toward heaven, till the tree could bear no more,
But dipped its top and set me down again.
That would be good both going and coming back.
One could do worse than be a swinger of birches.
____


===== In Praise of Imperfect Love by Jessica Goodfellow
[verse]
____
Courtesans of tenth century Japan knew
the keening of the caged copper pheasant,
solo double-note aria for a missing mate,
could be silenced with a mirror

The ideal of a love that completes 
masks a yearning for homeostasis,
a second umbilical, island fever,
harmony tighter than unison —

dull as a solved equation;
like the ex-lover who said,
"Being with you is like being alone."
He meant it as a compliment.
____


===== Failing and Flying by Jack Gilbert
[verse]
____
Everyone forgets that Icarus also flew.
It's the same when love comes to an end,
or the marriage fails and people say
they knew it was a mistake, that everybody
said it would never work. That she was
old enough to know better. But anything
worth doing is worth doing badly.
Like being there by that summer ocean
on the other side of the island while
love was fading out of her, the stars
burning so extravagantly those nights that
anyone could tell you they would never last.
Every morning she was asleep in my bed
like a visitation, the gentleness in her
like antelope standing in the dawn mist.
Each afternoon I watched her coming back
through the hot stony field after swimming,
the sea light behind her and the huge sky
on the other side of that. Listened to her
while we ate lunch. How can they say
the marriage failed? Like the people who
came back from Provence (when it was Provence)
and said it was pretty but the food was greasy.
I believe Icarus was not failing as he fell,
but just coming to the end of his triumph.
____


===== Tell Me by Anne Pierson Wiese
[verse]
____
There are many people who spend their nights
on the subway trains. Often one encounters
them on the morning commute, settled in corners, 
coats over their heads, ragged possessions heaped 
around themselves, trying to remain in their own night.

This man was already up, bracing himself against
the motion of the train as he folded his blanket
the way my mother taught me, and donned his antique blazer, 
his elderly, sleep-soft eyes checking for the total effect.

Whoever you are-tell me what unforgiving series 
of moments has added up to this one: a man 
making himself presentable to the world in front 
of the world, as if life has revealed to him the secret 
that all our secrets from one another are imaginary. 
____


===== Loss and Gain by Henry Wadsworth Longfellow
[verse]
____
When I compare
What I have lost with what I have gained,
What I have missed with what attained,
  Little room do I find for pride.

     I am aware
How many days have been idly spent;
How like an arrow the good intent
  Has fallen short or been turned aside. 

     But who shall dare
To measure loss and gain in this wise?
Defeat may be victory in disguise;
  The lowest ebb is the turn of the tide. 
____


===== Pity the Elderly Gray Translator by Vladimir Nabokov
[verse]
____
Pity the elderly gray translator
Who lends to beauty his hollow voice
And - choosing sometimes a second-rater -
Mimes the song-fellow of this choice.
To sacred sense for the sake of meter
His is seldom traitor as traitors go,
But pity him when he quakes with Peter
And waits for the terza rima to crow.

It is not the head of the verse line that'll
Cause him trouble, nor is it the spine:
What he really minds is the cursed rattle
That must be found for the tail of the line.
Some words by nature are sort of singlish,
Others have harems of rimes. The word
"Elephant," for example, walks alone in English
But its Slavic equivalent goes about in a herd.
"Woman" is another famous poser
For none can seriously contemplate
An American president or a German composer
In a viable context with the word for mate.
Since rime is a national repercussion
(And a local holiday), how bizarre
That "skies-eyes" should twin in French and Russian:
"Cieux-yeux," "nebesa-glaza."

Such boons are irrelevant. Sooner or later
The gentle person, the mime sublime,
The incorruptible translator
Is betrayed by lady rime.
And the poem from the Persian
And the sonnet spun in Spain
Perish in the person's version
And the person dies insane.
____


===== The Long Meadow by Vijay Seshadri
[verse]
____
Near the end of one of the old poems, the son of righteousness,
the source of virtue and civility,
on whose back the kingdom is carried
as on the back of the tortoise the earth is carried,
passes into the next world.
The wood is dark. The wood is dark,
and on the other side of the wood the sea is shallow, warm, endless.
In and around it, there is no threat of life—
so little is the atmosphere charged with possibility that
he might as well be wading through a flooded basement.
He wades for what seems like forever,
and never stops to rest in the shade of the metal raintrees
springing out of the water at fixed intervals.
Time, though endless, is also short,
so he wades on, until he walks out of the sea and into the mountains,
where he burns on the windward slopes and freezes in the valleys.
After unendurable struggles,
he finally arrives at the celestial realm.
The god waits there for him. The god invites him to enter.
But looking through the glowing portal,
he sees on that happy plain not those he thinks wait eagerly for him—
his beloved, his brothers, his companions in war and exile,
all long since dead and gone—
but, sitting pretty and enjoying the gorgeous sunset,
his cousin and bitter enemy, the cause of that war, that exile,
whose arrogance and vicious indolence
plunged the world into grief.
The god informs him that, yes, those he loved have been carried down
the river of fire. Their thirst for justice
offended the cosmic powers, who are jealous of justice.
In their place in the celestial realm, called Alaukika in the ancient texts,
the breaker of faith is now glorified.
He, at least, acted in keeping with his nature.
Who has not felt a little of the despair the son of righteousness now feels,
staring wildly around him?
The god watches, not without compassion and a certain wonder.
This is the final illusion,
the one to which all the others lead.
He has to pierce through it himself, without divine assistance.
He will take a long time about it,
with only his dog to keep him company,
the mongrel dog, celebrated down the millennia,
who has waded with him,
shivered and burned with him,
and never abandoned him to his loneliness.
That dog bears a slight resemblance to my dog,
a skinny, restless, needy, overprotective mutt,
who was rescued from a crack house by Suzanne.
On weekends, and when I can shake free during the week,
I take her to the Long Meadow, in Prospect Park, where dogs
are allowed off the leash in the early morning.
She’s gray-muzzled and old now, but you can’t tell that by the way she runs.
____


===== The Loneliest Job in the World by Tony Hoagland
[verse]
____
As soon as you begin to ask the question, Who loves me?
you are completely screwed, because
the next question is How Much?

and then it is hundreds of hours later,
and you are still hunched over
your flowcharts and abacus,

trying to decide if you have gotten enough.
This is the loneliest job in the world:
to be an accountant of the heart.

It is late at night. You are by yourself,
and all around you, you can hear
the sounds of people moving

in and out of love,
pushing the turnstiles, putting
their coins in the slots,

paying the price which is asked,
which constantly changes.
No one knows why.
____


===== The More Loving One by W. H. Auden
[verse]
____
Looking up at the stars, I know quite well
That, for all they care, I can go to hell,
But on earth indifference is the least
We have to dread from man or beast.

How should we like it were stars to burn
With a passion for us we could not return?
If equal affection cannot be,
Let the more loving one be me.

Admirer as I think I am
Of stars that do not give a damn,
I cannot, now I see them, say
I missed one terribly all day.

Were all stars to disappear or die,
I should learn to look at an empty sky
And feel its total dark sublime,
Though this might take me a little time.
____


===== One of the Butterflies by W.S. Merwin
[verse]
____
The trouble with pleasure is the timing
it can overtake me without warning
and be gone before I know it is here
it can stand facing me unrecognized
while I am remembering somewhere else
in another age or someone not seen
for years and never to be seen again
in this world and it seems I cherish
only now a joy I was not aware of
when it was here although it remains
out of reach and will not be caught or named
or called back and if I could make it stay
as I want to it would turn into pain
____


===== Driving at Night by Sheila Packa
[verse]
____
Up north, the dashboard lights of the family car
gleam in memory, the radio
plays to itself as I drive
my father plied the highways
while my mother talked, she tried to hide
that low lilt, that Finnish brogue,
in the back seat, my sisters and I
our eyes always tied to the Big Dipper
I watch it still
on summer evenings, as the fireflies stream
above the ditches and moths smack
into the windshield and the wildlife’s
red eyes bore out from the dark forests
we flew by, then scattered like the last bit of star
light years before.
It’s like a different country, the past
we made wishes on unnamed falling stars
that I’ve forgotten, that maybe were granted
because I wished for love.
____


===== Sentimental Education by Tony Hoagland
[verse]
____
And when we were eight, or nine,
our father took us back into the Alabama woods,
found a rotten log, and with his hunting knife

pried off a slab of bark
to show the hundred kinds of bugs and grubs
that we would have to eat in a time of war.

"The ones who will survive," he told us,
looking at us hard,
"are the ones who are willing to do anything."
Then he popped one of those pale slugs
into his mouth and started chewing.

And that was Lesson Number 4
in The Green Beret Book of Childrearing.

I looked at my pale, scrawny, knock-kneed, bug-eyed brother,
who was identical to me,
and saw that, in a world that ate the weak,
we didn't have a prayer,

and next thing I remember, I'm working for a living
at a boring job
that I'm afraid of losing,

with a wife whose lack of love for me
is like a lack of oxygen,
and this dead thing in my chest
that used to be my heart.

Oh, if he were alive, I would tell him, "Dad,
you were right! I ate a lot of stuff
far worse than bugs."

And I was eaten, I was eaten,
I was picked up
and chewed
and swallowed

down into the belly of the world.
____


===== When the Horses Gallop Away from Us, It’s a Good Thing by Charles Wright
[verse]
____
I always find it strange—though I shouldn’t—how creatures don’t
care for us the way we care for them.
Horses, for instance, and chipmunks, and any bird you’d name.
Empathy’s only a one-way street.
And that’s all right, I’ve come to believe.
It sets us up for ultimate things,
  and penultimate ones as well.
It’s a good lesson to have in your pocket when the 
  Call comes to call.
____


===== Oil & Steel by Henri Cole
[verse]
____
My father lived in a dirty-dish mausoleum,
watching a portable black-and-white television,
reading the Encyclopaedia Britannica,
which he preferred to Modern Fiction.
One by one, his schnauzers died of liver disease,
except the one that guarded his corpse
found holding a tumbler of Bushmills.
"Dead is dead," he would say, an antipreacher.
I took a plaid shirt from the bedroom closet
and some motor oil—my inheritance.
Once I saw him weep in a courtroom—
neglected, needing nursing—this man who never showed
me much affection but gave me a knack
for solitude, which has been mostly useful.
____


===== The Flood by Robert Frost
[verse]
____
Blood has been harder to dam back than water.
Just when we think we have it impounded safe 
Behind new barrier walls (and let it chafe!),
It breaks away in some new kind of slaughter.
We choose to say it is let loose by the devil;
But power of blood itself releases blood.
It goes by might of being such a flood
Held high at so unnatural a level.
It will have outlet, brave and not so brave.
weapons of war and implements of peace
Are but the points at which it finds release.
And now it is once more the tidal wave
That when it has swept by leaves summits stained.
Oh, blood will out. It cannot be contained.
____


===== Her Kid Brother Ran Beside the Car by Marjorie Saiser
[verse]
____
After phoning her father
she caught a ride from the depot.
Her kid brother waited at the bridge
and then ran, grinning, beside the car
all the way to the house.
He was taller and bonier than the day she left,
bib overalls hanging on his shirtless shoulders,
thick dark hair shaking with his running.

He clammed up and backed off when she
got out. She held her squirming baby
and stood at the driver's window to thank
the neighbor who had given her a ride,
a long thanks protocol called for.
Neither father nor mother came to the door,
one reading the county paper
and one peeling an extra potato, and it was
her kid brother who reached for the suitcase
and ran ahead over the cedar needles
to open the heavy door.
____


===== Acquainted with the Night by Robert Frost
[verse]
____
I have been one acquainted with the night.
I have walked out in rain—and back in rain.
I have outwalked the furthest city light.

I have looked down the saddest city lane.
I have passed by the watchman on his beat
And dropped my eyes, unwilling to explain.

I have stood still and stopped the sound of feet
When far away an interrupted cry
Came over houses from another street,

But not to call me back or say good-bye;
And further still at an unearthly height,
One luminary clock against the sky

Proclaimed the time was neither wrong nor right. 
I have been one acquainted with the night.
____


===== Brown Penny by William Butler Yeats
[verse]
____
I whispered, 'I am too young,'
And then, 'I am old enough';
Wherefore I threw a penny
To find out if I might love.
'Go and love, go and love, young man,
If the lady be young and fair.'
Ah, penny, brown penny, brown penny,
I am looped in the loops of her hair.

O love is the crooked thing,
There is nobody wise enough
To find out all that is in it,
For he would be thinking of love
Till the stars had run away
And the shadows eaten the moon.
Ah, penny, brown penny, brown penny,
One cannot begin it too soon.
____


===== Shoulders by Naomi Shihab Nye
[verse]
____
A man crosses the street in rain,
stepping gently, looking two times north and south,
because his son is asleep on his shoulder.

No car must splash him.
No car drive too near to his shadow.

This man carries the world’s most sensitive cargo
but he’s not marked.
Nowhere does his jacket say FRAGILE,
HANDLE WITH CARE.

His ear fills up with breathing.
He hears the hum of a boy’s dream
deep inside him.

We’re not going to be able
to live in this world
if we’re not willing to do what he’s doing
with one another.

The road will only be wide.
The rain will never stop falling.
____


===== Ode I. 11 by Horace
[verse]
____
Do not inquire, we may not know, what end 
the Gods will give, Leuconoe, do not attempt 
Babylonian calculations. The better course is 
to bear whatever will be, whether Jove allot 
more winters or this is the last which exhausts 
the Tuscan sea with pumice rocks opposed. 
Be wise, decant the wine, prune back 
your long-term hopes. Life ebbs as I speak– 
so seize each day, and grant the next no credit. 
____


===== Robert Wilson by Michael Collier 
[verse]
____
Though he is dead now and his miracle
will do us no good, I must remind myself
of what he gave, plainly,
and without guile, to all of us on the crumbling
flood-gutted bank of the Verde River
as we watched him, the fat boy,
the last one to cross, ford the violent shallows.
And how we provided him the occasion for his grace
tying his black tennis shoes to a bamboo fishing pole
and dangling them, like a simple bait,
out of reach, jerking them higher each time he rose
from his terrified crouch in the middle
of the shin-high rapids churning beneath him,
like an anger he never expressed.
And yet what moved us was not his earnestness
in trying to retrieve his shoes, nor his willingness
to be the butt of our jokes. What moved us
was how the sun struck the gold attendance star
pinned on the pocket flap of his uniform
as he fell head first
into the water and split his face,
a gash he quickly hid with his hands,
though blood leaked through his fingers as he stood
straight in the river and walked deftly toward us
out of the water to his shoes
that lay abandoned at our feet.
____


===== Staying at Grandma's by Jane Kenyon
[verse]
____
Sometimes they left me for the day
while they went — what does it matter 
where — away. I sat and watched her work
the dough, then turn the white shape 
yellow in a buttered bowl.

A coleus, wrong to my eye because its leaves
were red, was rooting on the sill
in a glass filled with water and azure
marbles. I loved to see the sun
pass through the blue.

"You know," she'd say, turning
her straight and handsome back to me,
"that the body is the temple 
of the Holy Ghost."

The Holy Ghost, the oh, oh ... the uh
oh, I thought, studying the toe of my new shoe,
and glad she wasn't looking at me.

Soon I'd be back in school. No more mornings
at Grandma's side while she swept the walk
or shook the dust mop by the neck.

If she loved me why did she say that
two women would be grinding at the mill,
that God would come out of the clouds
when they were least expecting him,
choose one to be with him in heaven
and leave the other there alone?
____


===== Shackleton's Decision by Faith Shearin
[verse]
____
At a certain point he decided they could not afford
the dogs. It was someone's job to take them one by one
behind a pile of ice and shoot them. I try to imagine
the arctic night which descended and would not lift,

a darkness that clung to their clothes. Some men objected
because the dogs were warmth and love, reminders
of their previous life where they slept in soft beds,
their bellies warm with supper. Dog tails were made

of joy, their bodies were wrapped in a fur of hope.
I had to put the book down when I read about the dogs
walking willingly into death, following orders,
one clutching an old toy between his teeth. They trusted

the men who led them into this white danger,
this barren cold. My God, they pulled the sleds
full of provisions and barked away the Sea Leopards.
Someone was told to kill the dogs because supplies

were running low and the dogs, gathered around
the fire, their tongues wet with kindness, knew
nothing of betrayal; they knew how to sit and come,
how to please, how to bow their heads, how to stay.
____


===== The courage that my mother had Edna St. Vincent Millay
[verse]
____
The courage that my mother had
Went with her, and is with her still:
Rock from New England quarried;
Now granite in a granite hill.

The golden brooch my mother wore
She left behind for me to wear;
I have no thing I treasure more:
Yet, it is something I could spare.

Oh, if instead she’d left to me
The thing she took into the grave!—
That courage like a rock, which she
Has no more need of, and I have.
____


===== Stop all the clocks, cut off the telephone by W.H. Auden
[verse]
____
Stop all the clocks, cut off the telephone, 
Prevent the dog from barking with a juicy bone, 
Silence the pianos and with muffled drum 
Bring out the coffin, let the mourners come. 

Let aeroplanes circle moaning overhead 
Scribbling on the sky the message He Is Dead, 
Put crepe bows round the white necks of the public doves, 
Let the traffic policemen wear black cotton gloves. 

He was my North, my South, my East and West, 
My working week and my Sunday rest, 
My noon, my midnight, my talk, my song; 
I thought that love would last for ever: I was wrong. 

The stars are not wanted now: put out every one; 
Pack up the moon and dismantle the sun; 
Pour away the ocean and sweep up the wood; 
For nothing now can ever come to any good. 
____


===== The Story of Ferdinand the Bull by Matt Mason
[verse]
____
Dad would come home after too long at work
and I’d sit on his lap to hear
the story of Ferdinand the Bull; every night,
me handing him the red book until I knew
every word, couldn’t read,
just recite along with drawings
of a gentle bull, frustrated matadors,
the all-important bee, and flowers—
flowers in meadows and flowers
thrown by the Spanish ladies.
Its lesson, really,
about not being what you’re born into
but what you’re born to be,
even if that means
not caring about the capes they wave in your face
or the spears they cut into your shoulders.
And Dad, wonderful Dad, came home
after too long at work
and read to me
the same story every night
until I knew every word, couldn’t read,
                                                                              just recite.
____


===== The Last Swim of Summer by Jonathan Galassi
[verse]
____
ought to be swum
without knowing it,
afternoon lost to
re-finding the rock
you can stand on
way out past the
raft, the flat one
that lines up four-
square with the door
of the boathouse.

Freestyle and back-
stroke and hours on
the dock nattering
on while the low sun
keeps setting fin-
gers and toes getting
number and number …
how could we know
we were swimming the
last swim of summer?
____


===== One Good Thing by Edwin Romond
[verse]
____
It's been a dead parade
of hours since 5 AM
a march of the bland
with the meaningless and
I can think of nothing
I have done to merit
mentioning or
remembering.

But now, at 8 pm,
I am bathing my son
in a tub filled with bubbles
and blue battleships,
the soapy water over
his Irish white skin
makes him glisten
like a glazed doughnut

and I should tell him
to stop splashing
but this is the first time
all day I have felt like living
so how can I scold
my boy who's found joy
in something ordinary
as water? And when

I wash his hair
with Buzz Lightyear
shampoo, Liam
closes his eyes and
smiles like a puppy
being petted as I massage 
the sweet lotion into 
his red curls and I know

this is one good thing
I have done with my life
this day that has waited
for this moment
of water on my sleeve
and soap on my nose
to turn emptiness
into ecstasy.
____


===== Choose Something Like a Star by Robert Frost
[verse]
____
O Star (the fairest one in sight),
We grant your loftiness the right
To some obscurity of cloud—
It will not do to say of night,
Since dark is what brings out your light.
Some mystery becomes the proud.
But to be wholly taciturn
In your reserve is not allowed.
Say something to us we can learn
By heart and when alone repeat.
Say something! And it says, ‘I burn.’
But say with what degree of heat.
Talk Fahrenheit, talk Centigrade.
Use language we can comprehend.
Tell us what elements you blend.
It gives us strangely little aid,
But does tell something in the end.
And steadfast as Keats’ Eremite,
Not even stooping from its sphere,
It asks a little of us here.
It asks of us a certain height,
So when at times the mob is swayed
To carry praise or blame too far,
We may choose something like a star
To stay our minds on and be staid.
____


===== First Skating Party by Joseph Mills
[verse]
____
Dozens of kids circle
the worn wooden floor
on old rental skates,
and none of them wear
helmets or pads,
so when they collide
or fall or stop themselves
by the simple technique
of steering straight
into the cinder-block barrier,
you can feel the pain
of the parents
who watch from booths
by the concession stand;
they know their children
have bones of balsa
and skin that tears
as easily as a napkin,
but they can do nothing
except yell, Be Careful!
and make hand gestures
to slow down
                             —Slow Down!—
as the ones they love
strobe past them
faster and faster
just beyond their reach.
____


===== The Tuft of FLowers by Robert Frost
[verse]
____
I went to turn the grass once after one
Who mowed it in the dew before the sun.
 
The dew was gone that made his blade so keen
Before I came to view the levelled scene.
 
I looked for him behind an isle of trees;
I listened for his whetstone on the breeze.
 
But he had gone his way, the grass all mown,
And I must be, as he had been,—alone,
 
'As all must be,’ I said within my heart,
'Whether they work together or apart.’
 
But as I said it, swift there passed me by
On noiseless wing a ‘wildered butterfly,
 
Seeking with memories grown dim o’er night
Some resting flower of yesterday’s delight.
 
And once I marked his flight go round and round,
As where some flower lay withering on the ground.
 
And then he flew as far as eye could see,
And then on tremulous wing came back to me.
 
I thought of questions that have no reply,
And would have turned to toss the grass to dry;
 
But he turned first, and led my eye to look
At a tall tuft of flowers beside a brook,
 
A leaping tongue of bloom the scythe had spared
Beside a reedy brook the scythe had bared.
 
I left my place to know them by their name,
Finding them butterfly weed when I came.
 
The mower in the dew had loved them thus,
By leaving them to flourish, not for us,
 
Nor yet to draw one thought of ours to him.
But from sheer morning gladness at the brim.
 
The butterfly and I had lit upon,
Nevertheless, a message from the dawn,
 
That made me hear the wakening birds around,
And hear his long scythe whispering to the ground,
 
And feel a spirit kindred to my own;
So that henceforth I worked no more alone;
 
But glad with him, I worked as with his aid,
And weary, sought at noon with him the shade;
 
And dreaming, as it were, held brotherly speech
With one whose thought I had not hoped to reach.
 
'Men work together,’ I told him from the heart,
'Whether they work together or apart.’
____


===== Song of the Shattering Vessles by Peter Cole
[verse]
____
Either the world is coming together,
or else the world is falling apart —
     here — now — along these letters,
     against the walls of every heart. 

Today, tomorrow, within its weather,
the end or beginning’s about to start —
     the world impossibly coming together
     or very possibly falling apart.

Now the lovers’ mouths are open —
maybe the miracle’s about to start:
      the world within us coming together,
      because all around us it’s falling apart. 

Even as they speak, he wonders,
even as the fear departs:
     Is that the world coming together?
     Can they keep it from falling apart?

The image, gradually, is growing sharper;
now the sound is like a dart:
     It seemed their world was coming together,
     but in fact it was falling apart.

That’s the nightmare, that’s the terror,
that’s the Isaac of this art —
     which sees that the world might come together
      if only we’re willing to take it apart. 

The dream, the lure, is the prayer’s answer,
which can’t be plotted on any chart —
    as we know the world that’s coming together
    without our knowing is falling apart.
____

===== Divorced Fathers and Pizza Crusts by Mark Halliday
[verse]
____
The connection between divorced fathers and pizza crusts
is understandable. The divorced father does not cook
confidently. He wants his kid to enjoy dinner.
The entire weekend is supposed to be fun. Kids love
pizza. For some reason involving soft warmth and malleability
 
kids approve of melted cheese on pizza
years before they will tolerate cheese in other situations.
So the divorced father takes the kid and the kid's friend
out for pizza. The kids eat much faster than the dad.
Before the dad has finished his second slice,
 
the kids are playing a video game or being Ace Ventura
or blowing spitballs through straws, making this hail
that can't quite be cleaned up. There are four slices left
and the divorced father doesn't want them wasted,
there has been enough waste already; he sits there
 
in his windbreaker finishing the pizza. It's good
except the crust is actually not so great—
after the second slice the crust is basically a chore—
so you leave it. You move on to the next loaded slice.
Finally there you are amid rims of crust.
 
All this is understandable. There's no dark conspiracy.
Meanwhile the kids are having a pretty good time
which is the whole point. So the entire evening makes
clear sense. Now the divorced father gathers
the sauce-stained napkins for the trash and dumps them
 
and dumps the rims of crust which are not
corpses on a battlefield. Understandability
fills the pizza shop so thoroughly there's no room
for anything else. Now he's at the door summoning the kids
and they follow, of course they do, he's a dad.
____

===== Waves and Wet Kisses by Ann Iverson
[verse]
____
I had only seen my parents kiss twice.
The first time after my father’s ear surgery.
I was seven or so, don’t recall the nature of the kiss
but only that his hearing was bad
from his youthful years of lifeguarding.
Or was it after he tore the cartilage around his ribs
from lifting heavy glass bottles of milk?
I don’t recall.

The second time was after my mother’s mastectomy.
They rolled her out of recovery.
She looked sad without her glasses —
eyes, small and watery.
He bent over and touched his lips to hers
then turned away and shook his head.

So that is it; that is all.
Two small kisses
for me to coast on like a wave.
____

===== My Father, Dying by Joyce Sutphen
[verse]
____
It was hard work, dying, harder
than anything he’d ever done.

Whatever brutal, bruising, back-
breaking chore he’d forced himself

to endure—it was nothing
compared to this. And it took

so long. When would the job
be over? Who would call him

home for supper? And it was
hard for us (his children)—

all of our lives we’d heard
my mother telling us to go out,

help your father, but this
was work we could not do.

He was way out beyond us,
in a field we could not reach.
____

===== Ode to My Sister by Sharon Olds
[verse]
____
I know why they say the heart is in
the heart. When you think about people you love,
you get warm there. I want to thank
my sister for loving me, which taught me
to love. I’m not sure what she loved in me,
besides my love for her—maybe
that I was a copy of her, half-size—
then three-quarters, then size. In the snapshots, you see her
keeping an eye on me, I was a little wild
and I said silly things, and she would laugh her serious
laugh. My sister knew things,
sometimes she knew everything,
as if she’d been born knowing. And I
so did not know—my wonder went
along with me wherever we’d go,
as if I had it on a tool belt—
I understood almost nothing, and I
loved pertinding, and I loved to go into the
garden and dance with the flowers, which danced
with me without hardly moving their green
legs, I was like a music box
dropped on my head. And I was bad—
but I don’t think my sister thought I was actually
bad, I was her somewhat smaller
littermate—nor did she need
my badness to establish her goodness. And she
was beautiful, with a moral beauty, she would
glide by, in the hall, like a queen
on a barge on the Nile, she had straight black hair
that moved like a black waterfall, as
one thing, like a black silk skirt.
She was the human. I aspired to her.
And she stood        between        the god        and me.
And her hair (pertind) was like a wing
of night, and in my dreams she could hold it
over me, and hide me. Of course,
by day, if the god wanted you for something,
she took you. I think if the god had known how to
take my curly hair from my head,
she would have. And I think there was nothing my sister
wanted to take from me. Why would
she want to, she had everything—
in our room she had control of the door,
closed, or open, and the light switch,
dark, or bright. And if anything
had happened to me, I think my sister
would not have known who she was, I was almost
essential to her, as she to me.
If anything had happened to her,
I think I would not be alive today,
and no one would remember me,
as if I had not lived.
____


===== Musee des Beaux Arts by W. H. Auden
[verse]
____
About suffering they were never wrong,
The old Masters: how well they understood
Its human position: how it takes place
While someone else is eating or opening a window or just walking dully along;
How, when the aged are reverently, passionately waiting
For the miraculous birth, there always must be
Children who did not specially want it to happen, skating
On a pond at the edge of the wood:
They never forgot
That even the dreadful martyrdom must run its course
Anyhow in a corner, some untidy spot
Where the dogs go on with their doggy life and the torturer's horse
Scratches its innocent behind on a tree.

In Breughel's Icarus, for instance: how everything turns away
Quite leisurely from the disaster; the ploughman may
Have heard the splash, the forsaken cry,
But for him it was not an important failure; the sun shone
As it had to on the white legs disappearing into the green
Water, and the expensive delicate ship that must have seen
Something amazing, a boy falling out of the sky,
Had somewhere to get to and sailed calmly on.
____


===== Photograph from September 11 by Wisława Szymborska
[verse]
____
They jumped from the burning floors—
one, two, a few more,
higher, lower.

The photograph halted them in life,
and now keeps them
above the earth toward the earth.

Each is still complete,
with a particular face
and blood well hidden.

There’s enough time
for hair to come loose,
for keys and coins
to fall from pockets.

They’re still within the air’s reach,
within the compass of places
that have just now opened.

I can do only two things for them—
describe this flight
and not add a last line.
____


===== From As One Put Drunk into the Pocket-Boat, by John Ashbery
[verse]
____
But the summer
Was well along, not yet past the mid-point
But full and dark with the promise of that fullness,
That time when one can no longer wander away
And even the least attentive fall silent
To watch the thing that is prepared to happen.
____

[verse]
____
The summer demands and takes away too much,
But night, the reserved, the reticent, gives more than it takes.
____

===== From As You Came from the Holy Land, by John Ashbery
[verse]
____
out of night the token emerges
its leaves like birds alighting all at once under a tree
taken up and shaken again
put down in weak rage
knowing as the brain does it can never come about
not here not yesterday in the past
only in the gap of today filling itself
as emptiness is distributed
in the idea of what time it is
when that time is already past
____


===== From Lithuanian Dance Band, by John Ashbery
[verse]
____
Yet we are alone too and that's sad isn't it 
Yet you are meant to be alone at least part of the time 
You must be in order to work and yet it always seems so unnatural 
As though seeing people were intrinsic to life which it just might be 
And then somehow the loneliness is more real and more human 
You know not just the scarecrow but the whole landscape 
And the crows peacefully pecking where the harrow has passed 
____


===== Figure, by Robert Wrigley
[verse]
____
You want a piece of me
to see, from the flesh of me,
a flesh from within me
no one’s ever seen, not me,
nor the mother or the lovers of me.
A piece that will have been me
but then no longer me,
instead a synecdoche of me,

or possibly metonymy,
a figure of speech of me,
in contiguity or association with me,
a part for the whole of me,
a sliver that once was me,
so you might perceive the end of me.
____


===== ted talk, by Jenny Zhang
[verse]
____
money will build anywhere
there’s a view or a coastline
all those tangled shrubs and thorny bushes
your ancestors cut through centuries ago
to claim in the name of a queen
and a king with foul smelling hair
these days even the ecotone
between the living and the dying
has to be privatized & sold at auction
all the steps between next year
and the first human year ever recorded
melted so flagrantly it became stylish to be poetic
for the end of the world
everyone’s collecting coins on every interface
a thousand identical posts about 2019
being the year of paper straws
and reusable cups
indigo dyeing from Kyoto
is the new 36 hours in Tbilisi
all the people with phones
don’t think twice about buying onboard wifi
on their way to the latest Caribbean island
still recovering from last year’s hurricanes
would it be so wrong to wish
everyone with global entry be grounded
until extinction is off the table
I don’t think I can date another
digital nomad or a normie with a dog
who doesn’t know what it’s like
to be too poor to buy their way
out of disaster
why do the rich treat blame
like it’s obscenity
or a fossil
is it because they hate seeing blood
think they are noble for taking
quick little showers
and using silicone at the farmer’s market
I have never seen someone forgive themselves
as elaborately as the wealthy
everyone who paid for their wellness
is infecting the rest of us
yes I am sick sick sick
and want to sterilize all the ruinous overseers
though it is not like me to dream so much
I have managed to hoard something
that cannot be replicated
it will die when I die
let no one say we didn’t try
to let a different kind of  life bloom
and let no one say we didn’t touch
what was there from the beginning
____


===== Mild Dry Lines: An Exchange, by Christian Wiman
[verse]
____
You prick too liberal into alien pains,
and read too readily a grief  you need to see
in order for the world to be the world
that ratifies the choices you’ve made.
You talk of callings, but a calling should
enlarge the life that it refines,
not grind its spice into some same mustard.

If  we could see the grief of any one life
it would be slag enough to crust a world
and any feeling being buried within.
But grief’s a craft like any other, it seems,
if only indirectly ours:
our skin’s inscripted with what nature knows.
The dead child chiseled in that woman’s cheek,
the battle smoldering off that old man’s brow,
our very mirrors, friend, these aging faces
with their lines of  loneliness like pressured ice:
you would have them silenced?

I would have them whole.

As would I. As would anyone
whose life is lit, however dimly, by the light
of survival.

I fear that by survival what you mean
is resignation, or, worse, a fictioned oblivion,
like the bull elephant that has outgrown
the stake that it was tied to as a calf:
it can’t break the rope that it could break
with ease.

And I fear by wholeness what you mean
is merely the will to leaven fate with will,
that constipated sorrow called good cheer.
I won’t relapse from these mild dry lines
whose only consolation is their dryness,
that one might utter calmly utter blood.
____

===== Daedal by A.E. Stallings
[verse]
____
To build a labyrinth it takes
A twisted mind, a puzzled art,
A fractal branching of mistakes.

Drag out the shovels and the rakes,
The spirit level, sacred chart.
To build a labyrinth it takes

Shadows, stones, a way that snakes
And ladders to its shaky start;
An average mazing of mistakes,

The kind that everybody makes,
Set random intervals apart.
To build a labyrinth it takes

Dead ends that seem like lucky breaks,
The paths of bats that weave and dart
Through limestone caverns of mistakes.

The shaken Etch A Sketch awakes
A lost child buried in its heart.
To build a labyrinth it takes
Some good intentions, some mistakes.
____


===== Dissociation by Ricki Cummings
[verse]
____
I sit with another version
of myself eating this apple
and this apple. I see
myself bite, chew,
and swallow as I bite,
chew, and swallow. I cannot
read me, my other face
consumed in eating this apple.
In my sinus there is a buzzing
like a dying fluorescent light
that drowns this apple I’m eating.
I cannot tell if this other me
hears it, if I see me
seeing me chewing and lost.
I would be fine if I stayed confined
to this, to sitting and eating.
I grow concerned when I see me
on the train and getting
off at the wrong stop, leaving me
bewildered in the tunnel. Worried
when I see myself driving my car
and veering it into traffic. Alarmed
at the beach when I watch me
walk into the water calm with
stones in my pockets when there
are no stones in my pockets.
Curious when I sit and write
when I’ve had no pen in hand in weeks.
And every time I try to ask me
I’m gone before I get there.
____


===== Fuck / Time by Inua Ellams
[verse]
____
Once upon a time / Yo-Yo Ma / traveling through Botswana searching for music / crosses a local shaman singing / into the savannah / He rushes to notate the melody / Please Sing Again he requests / to which the shaman sings something else and explains / to the baffled Yo-Yo Ma that earlier / clouds had covered the sun and wild antelope grazed in the distance / But the dial of the world had twirled since / The antelopes had cantered into some other future / The clouds had gone / so the song had to change / had to slough off the chains us mortals clasp everything with / even our fluid wrists / The universe in fact is monstrously indifferent to the presence of man / We are small as moth wing fall / in an orchestra broad as galaxies / playing a symphony Time isn’t bothered to fathom / It respects no constant and is always moving on
____


===== Unrest by Emily Fragos
[verse]
____
At the shelter, the cats are kept in glass-enclosed cases with just enough room to stand, walk a few steps, and eat; but strangers come on weekends to adopt them, take them to larger rooms and give them new names: James, Tabitha, Snowball, Molière, so you would never know how they began their lives, in abuse, grave hunger, and deprivation, or what strange turbulence lies coiled up inside their bodies, as they flo
____



===== The Sea Shell by Marin Sorescu
[verse]
____
I have hidden inside a sea shell
but forgotten in which.

Now daily I dive,
filtering the sea through my fingers,
to find myself.
Sometimes I think
a giant fish has swallowed me.
Looking for it everywhere I want to make sure
it will get me completely.

The sea-bed attracts me, and
I’m repelled by millions
of sea shells that all look alike.
Help, I am one of them.
If only I knew, which.

How often I’ve gone straight up
to one of them, saying: That’s me.
Only, when I prised it open
it was empty.
____


===== To the Swimmer by Countee Cullen
[verse]
____
Now as I watch you, strong of arm and endurance, battling and struggling
With the waves that rush against you, ever with invincible strength returning
Into my heart, grown each day more tranquil and peaceful, comes a fierce longing
Of mind and soul that will not be appeased until, like you, I breast yon deep and boundless expanse of blue.

With an outward stroke of power intense your mighty arm goes forth,
Cleaving its way through waters that rise and roll, ever a ceaseless vigil keeping
Over the treasures beneath.

My heart goes out to you of dauntless courage and spirit indomitable,
And though my lips would speak, my spirit forbids me to ask,
“Is your heart as true as your arm?”
____


===== Making a Fist by Naomi Shihab Nye
[verse]
____
    We forget that we are all dead men conversing with dead men.
                                                                  —Jorge Luis Borges

For the first time, on the road north of Tampico,
I felt the life sliding out of me,
a drum in the desert, harder and harder to hear.
I was seven, I lay in the car
watching palm trees swirl a sickening pattern past the glass.
My stomach was a melon split wide inside my skin.

“How do you know if you are going to die?”
I begged my mother.
We had been traveling for days.
With strange confidence she answered,
“When you can no longer make a fist.”

Years later I smile to think of that journey,
the borders we must cross separately,
stamped with our unanswerable woes.
I who did not die, who am still living,
still lying in the backseat behind all my questions,
clenching and opening one small hand.
____


===== Leave-Taking by Louise Bogan
[verse]
____
I do not know where either of us can turn
Just at first, waking from the sleep of each other.
I do not know how we can bear
The river struck by the gold plummet of the moon,
Or many trees shaken together in the darkness.
We shall wish not to be alone
And that love were not dispersed and set free—
Though you defeat me,
And I be heavy upon you.

But like earth heaped over the heart
Is love grown perfect.
Like a shell over the beat of life
Is love perfect to the last.
So let it be the same
Whether we turn to the dark or to the kiss of another;
Let us know this for leavetaking,
That I may not be heavy upon you,
That you may blind me no more.
____


===== Sad Steps by Philip Larkin
[verse]
____
Groping back to bed after a piss
I part thick curtains, and am startled by   
The rapid clouds, the moon’s cleanliness.

Four o’clock: wedge-shadowed gardens lie   
Under a cavernous, a wind-picked sky.   
There’s something laughable about this,

The way the moon dashes through clouds that blow   
Loosely as cannon-smoke to stand apart   
(Stone-coloured light sharpening the roofs below)

High and preposterous and separate—   
Lozenge of love! Medallion of art!
O wolves of memory! Immensements! No,

One shivers slightly, looking up there.
The hardness and the brightness and the plain   
Far-reaching singleness of that wide stare

Is a reminder of the strength and pain   
Of being young; that it can’t come again,   
But is for others undiminished somewhere.
____



===== On Leaving the Bachelorette Brunch by Rachel Wetzsteon
[verse]
____
Because I gazed out the window at birds
doing backflips when the subject turned
to diamonds, because my eyes glazed over
with the slightly sleepy sheen your cake will wear,

never let it be said that I’d rather be
firing arrows at heart-shaped dartboards
or in a cave composing polyglot puns.
I crave, I long for transforming love

as surely as leaves need water and mouths seek bread.
But I also fear the colder changes
that lie in wait and threaten to turn
moons of honey to pools of molasses,

broad front porches to narrow back gardens,
and tight rings of friendship to flimsy things
that break when a gold band brightly implies
Leave early, go home, become one with the one

the world has told you to tend and treasure
above all others. You love, and that’s good;
you are loved, that’s superb; you will vanish
and reap some happy rewards. But look at the birds.
____



===== To converse with the greats by Vera Pavlova Translated by Steven Seymour
[verse]
____
To converse with the greats
by trying their blindfolds on;
to correspond with books
by rewriting them;
to edit holy edicts,
and at the midnight hour
to talk with the clock by tapping a wall
in the solitary confinement of the universe.
____



===== Such Simple Love by Thomas Mcgrath
[verse]
____
All night long I hear the sleepers toss
Between the darkened window and the wall.
The madman’s whimper and the lover’s voice,
The worker’s whisper and the sick child’s call—
Knowing them all

I’d walk a mile, maybe, hearing some cat
Crying its guts out, to throttle it by hand,
Such simple love I had. I wished I might—
Or God might—answer each call in person and
Each poor demand.

Well, I’d have been better off sleeping myself.
These fancies had some sentimental charm,
But love without direction is a cheap blanket
And even if it did no one any harm,
No one is warm.
____


===== The Lotos-eaters by Alfred, Lord Tennyson
[verse]
____
"Courage!" he said, and pointed toward the land, 
"This mounting wave will roll us shoreward soon."
In the afternoon they came unto a land
In which it seemed always afternoon.
All round the coast the languid air did swoon,
Breathing like one that hath a weary dream.
Full-faced above the valley stood the moon;
And like a downward smoke, the slender stream
Along the cliff to fall and pause and fall did seem.

A land of streams! some, like a downward smoke,
Slow-dropping veils of thinnest lawn, did go;
And some thro' wavering lights and shadows broke,
Rolling a slumbrous sheet of foam below.
They saw the gleaming river seaward flow
From the inner land: far off, three mountain-tops,
Three silent pinnacles of aged snow,
Stood sunset-flush'd: and, dew'd with showery drops,
Up-clomb the shadowy pine above the woven copse.

The charmed sunset linger'd low adown
In the red West: thro' mountain clefts the dale
Was seen far inland, and the yellow down
Border'd with palm, and many a winding vale
And meadow, set with slender galingale;
A land where all things always seem'd the same!
And round about the keel with faces pale,
Dark faces pale against that rosy flame,
The mild-eyed melancholy Lotos-eaters came.

Branches they bore of that enchanted stem,
Laden with flower and fruit, whereof they gave
To each, but whoso did receive of them,
And taste, to him the gushing of the wave
Far far away did seem to mourn and rave
On alien shores; and if his fellow spake,
His voice was thin, as voices from the grave;
And deep-asleep he seem'd, yet all awake,
And music in his ears his beating heart did make.

They sat them down upon the yellow sand,
Between the sun and moon upon the shore;
And sweet it was to dream of Fatherland,
Of child, and wife, and slave; but evermore
Most weary seem'd the sea, weary the oar,
Weary the wandering fields of barren foam.
Then some one said, "We will return no more";
And all at once they sang, "Our island home
Is far beyond the wave; we will no longer roam."

CHORIC SONG
I
There is sweet music here that softer falls
Than petals from blown roses on the grass,
Or night-dews on still waters between walls
Of shadowy granite, in a gleaming pass;
Music that gentlier on the spirit lies,
Than tir'd eyelids upon tir'd eyes;
Music that brings sweet sleep down from the blissful skies.
Here are cool mosses deep,
And thro' the moss the ivies creep,
And in the stream the long-leaved flowers weep,
And from the craggy ledge the poppy hangs in sleep."

II
Why are we weigh'd upon with heaviness,
And utterly consumed with sharp distress,
While all things else have rest from weariness?
All things have rest: why should we toil alone,
We only toil, who are the first of things,
And make perpetual moan,
Still from one sorrow to another thrown:
Nor ever fold our wings,
And cease from wanderings,
Nor steep our brows in slumber's holy balm;
Nor harken what the inner spirit sings,
"There is no joy but calm!"
Why should we only toil, the roof and crown of things?

III
Lo! in the middle of the wood,
The folded leaf is woo'd from out the bud
With winds upon the branch, and there
Grows green and broad, and takes no care,
Sun-steep'd at noon, and in the moon
Nightly dew-fed; and turning yellow
Falls, and floats adown the air.
Lo! sweeten'd with the summer light,
The full-juiced apple, waxing over-mellow,
Drops in a silent autumn night.
All its allotted length of days
The flower ripens in its place,
Ripens and fades, and falls, and hath no toil,
Fast-rooted in the fruitful soil.

IV
Hateful is the dark-blue sky,
Vaulted o'er the dark-blue sea.
Death is the end of life; ah, why
Should life all labour be?
Let us alone. Time driveth onward fast,
And in a little while our lips are dumb.
Let us alone. What is it that will last?
All things are taken from us, and become
Portions and parcels of the dreadful past.
Let us alone. What pleasure can we have
To war with evil? Is there any peace
In ever climbing up the climbing wave?
All things have rest, and ripen toward the grave
In silence; ripen, fall and cease:
Give us long rest or death, dark death, or dreamful ease.

V
How sweet it were, hearing the downward stream,
With half-shut eyes ever to seem
Falling asleep in a half-dream!
To dream and dream, like yonder amber light,
Which will not leave the myrrh-bush on the height;
To hear each other's whisper'd speech;
Eating the Lotos day by day,
To watch the crisping ripples on the beach,
And tender curving lines of creamy spray;
To lend our hearts and spirits wholly
To the influence of mild-minded melancholy;
To muse and brood and live again in memory,
With those old faces of our infancy
Heap'd over with a mound of grass,
Two handfuls of white dust, shut in an urn of brass!

VI
Dear is the memory of our wedded lives,
And dear the last embraces of our wives
And their warm tears: but all hath suffer'd change:
For surely now our household hearths are cold,
Our sons inherit us: our looks are strange:
And we should come like ghosts to trouble joy.
Or else the island princes over-bold
Have eat our substance, and the minstrel sings
Before them of the ten years' war in Troy,
And our great deeds, as half-forgotten things.
Is there confusion in the little isle?
Let what is broken so remain.
The Gods are hard to reconcile:
'Tis hard to settle order once again.
There is confusion worse than death,
Trouble on trouble, pain on pain,
Long labour unto aged breath,
Sore task to hearts worn out by many wars
And eyes grown dim with gazing on the pilot-stars.

VII
But, propt on beds of amaranth and moly,
How sweet (while warm airs lull us, blowing lowly)
With half-dropt eyelid still,
Beneath a heaven dark and holy,
To watch the long bright river drawing slowly
His waters from the purple hill—
To hear the dewy echoes calling
From cave to cave thro' the thick-twined vine—
To watch the emerald-colour'd water falling
Thro' many a wov'n acanthus-wreath divine!
Only to hear and see the far-off sparkling brine,
Only to hear were sweet, stretch'd out beneath the pine.

VIII
The Lotos blooms below the barren peak:
The Lotos blows by every winding creek:
All day the wind breathes low with mellower tone:
Thro' every hollow cave and alley lone
Round and round the spicy downs the yellow Lotos-dust is blown.
We have had enough of action, and of motion we,
Roll'd to starboard, roll'd to larboard, when the surge was seething free,
Where the wallowing monster spouted his foam-fountains in the sea.
Let us swear an oath, and keep it with an equal mind,
In the hollow Lotos-land to live and lie reclined
On the hills like Gods together, careless of mankind.
For they lie beside their nectar, and the bolts are hurl'd
Far below them in the valleys, and the clouds are lightly curl'd
Round their golden houses, girdled with the gleaming world:
Where they smile in secret, looking over wasted lands,
Blight and famine, plague and earthquake, roaring deeps and fiery sands,
Clanging fights, and flaming towns, and sinking ships, and praying hands.
But they smile, they find a music centred in a doleful song
Steaming up, a lamentation and an ancient tale of wrong,
Like a tale of little meaning tho' the words are strong;
Chanted from an ill-used race of men that cleave the soil,
Sow the seed, and reap the harvest with enduring toil,
Storing yearly little dues of wheat, and wine and oil;
Till they perish and they suffer—some, 'tis whisper'd—down in hell
Suffer endless anguish, others in Elysian valleys dwell,
Resting weary limbs at last on beds of asphodel.
Surely, surely, slumber is more sweet than toil, the shore
Than labour in the deep mid-ocean, wind and wave and oar;
O, rest ye, brother mariners, we will not wander more.
____


===== Figs from Thistles: First Fig by Edna St. Vincent Millay
[verse]
____
My candle burns at both ends;
   It will not last the night;
But ah, my foes, and oh, my friends—
   It gives a lovely light!
____


===== sorrow song by Lucille Clifton
[verse]
____
for the eyes of the children,
the last to melt,
the last to vaporize,
for the lingering
eyes of the children, staring,
the eyes of the children of
buchenwald,
of viet nam and johannesburg,
for the eyes of the children
of nagasaki,
for the eyes of the children
of middle passage,
for cherokee eyes, ethiopian eyes,
russian eyes, american eyes,
for all that remains of the children,
their eyes,
staring at us, amazed to see
the extraordinary evil in
ordinary men.
____

===== The Vacation by Wendell Berry
[verse]
____
Once there was a man who filmed his vacation.
He went flying down the river in his boat
with his video camera to his eye, making
a moving picture of the moving river
upon which his sleek boat moved swiftly
toward the end of his vacation. He showed
his vacation to his camera, which pictured it,
preserving it forever: the river, the trees,
the sky, the light, the bow of his rushing boat
behind which he stood with his camera
preserving his vacation even as he was having it
so that after he had had it he would still
have it. It would be there. With a flick
of a switch, there it would be. But he
would not be in it. He would never be in it.
____


===== Dear Life by Maya C. Popa
[verse]
____
I can’t undo all I have done unto myself,
what I have let an appetite for love do to me.

I have wanted all the world, its beauties
and its injuries; some days,
I think that is punishment enough.

Often, I received more than I’d asked,

which is how this works—you fish in open water
ready to be wounded on what you reel in.

Throwing it back was a nightmare.
Throwing it back and seeing my own face

as it disappeared into the dark water.

Catching my tongue suddenly on metal,
spitting the hook into my open palm.

Dear life: I feel that hook today most keenly.

Would you loosen the line—you’ll listen

if   I ask you,

if   you are the sort of  life I think you are.
____


===== Omnicide by Maurya Simon
[verse]
____
And when our children ask,
       Why did  you do nothing as the world
             was dying?   what will we tell them?

Will we say, We didn’t know how
       sick it was, or admit that We gathered
             our rosebuds while we could,

Old  Time was still a-flying—?
       It’s now the end of  everything,
             our children will say, go crawl

into your arks and sail off  destitute into
       your doom, and leave us only
             your shadows. And our children

will light candles across seven continents
       empty now of  lions, kangaroos, ravens,
             squirrels, javelinas, pelicans—

devoid of praying mantises, koalas, ants,
       cobras, snails, Doberman pinschers, pigs,
             vultures, lizards, and alley cats.

Our children will hide in caves with blind
       cockroaches, together feeding on the algae
             glowing in neon greens and blues

across dolomite and limestone walls.
       They’ll leave no pictographs behind,
             no sprayed handprints, no artful gods.

Such silence now, they’ll say, this  you’ve
       bequeathed us, this human indifference.
             And we’ll beg them, Survive.
____


===== Laudation by Maurice Riordan
[verse]
____
Of  all sights, a new moon. Of  all smells, bread. Of  all surfaces, skin.
Of  all sweet sounds, the mourning dove and the sleeping child.
Of  all my journeys, the shortcut from school through Buckley’s Glen.
Of  all other journeys, the Greyhound bus at night into Manhattan.
Of  cities, Jerusalem. Of  modes of  transport, the pony and car.
Of   the neglected virtues, shyness. Of   the celebrated, hospitality.
Of   the harmless vices ... the lie-in, the painted toe, the keepsake.
Of  solitary vices, the night out and a piss in moonlight.
Of   the social pastimes, gossip among cultivated friends.
Of   the cultivars, either the grape or the apple.
Of   the apples, the Wyken Pippin. Of  cults, the Eleusinian.
Of  all that delights the cultivated mind, letter-writing.
Of  all jokes, the one about the two thieves.
Of  practical jokes, the shoulder-tap (oldest and most cruel).
Of  all of  Job’s afflictions, maybe the boils.
Of   beverages, tea. Of  all that coarsens the palate, eating beef.
Of  ingenious devices, the search engine and the zipper.
Of  all that thrives among Satan’s noisome progeny, the rock drill and mosquito.
Of   the proofs of God’s love, the crow.
Of  all that testifies to the sway of evil, the white lie.
Of   the forgotten sins, calumny (which thrives).
Of   the erotic side-pleasures, the smile. And the text.
Of  rare and elusive flavors, sweet cicely and the chanterelle.
Of  domesticated creatures, the pig or goose.
Of  all times, the hour before sunrise. Of  all fears, the lump.
Of  all places, here and now. Of  sweet sounds to wake to, the mourning dove.
____


===== in love as in tourism by Xiao Yue Shan
[verse]
____
cartography seems the strangest science today
as morning alters the fittings of the hour to form
shapes wholly new. wishing I did not know that, to leave,
it is down and right past the neighbor’s potted palm,
across the street to meet the river, then ahead until
the train station crowds into view—I search the infinity
enclosed here, for any time that the future could spare.
between the words lost and losing entire worlds change
hands. where the latter informs negation the other is
duplicitous with potentialities—becoming something
even desired. suddenly one is alert to all the colors
returned to sight by merely looking, a lack of familiarity
striking the common into curiosity, just as in the folktales
in which death plays detective, the wanderer is the one
who evades the blade. it is so wonderful to not be found
but to be finding, as I discover in tokyo—whose streets
resemble labyrinth, pierced with rhododendron in spring
and thundering gingko in autumn—and remember again
when you laugh and I do not ask why. and I do not want
to know either, to whom this room belonged to before us,
or where that smell of fruit is coming from, or why a fog
rises to challenge the knowledge of places once intimately
kept. I am grateful that within you only the unknown lives,
that even as what passes between us is frail and limited
and human, we still dream of things resembling the eternal.
____


===== details     escape by Xiao Yue Shan
[verse]
____
returning to the place where memory goes
which resembles most closely the stagger of stones
needling the hem of land at minoura’s feet
water work of the inland sea interlocking past

I think I had to take more than one deep breath
to commiserate with the animal we named silence
beaten under depths rest good fruit car crashes
invented grandmothers more sunrises than reality

who is the owner of unremembered moments
would they open their great book
if  I stood
at the door
and begged? 
____



===== Ours by Iliana Rocha
[verse]
____
After Bill Olsen’s “Our Heron”

You know wonder by its silence. Pinsky’s ineffable this evening. A field that isn’t quite ours, darkness, clusters of lightning bugs. Get your camera out. I can’t catch anything, too dark. This isn’t ours to take with us. A lesson we’re told over & over but haven’t quite learned because of the delicacy of the reminder. We move the night as the strangers we are in that we leave the quiet to, finally, do its great work.
     Some nights our walk precedes dusk & there is just the waiting. The twilight’s generous pinks & baby blues. An exercise in loneliness, & once you’ve let it be still, a reward. Lightning bugs, fireflies, depending on the region. Nomenclature in & of itself a way to divide, but we’re brought together through observation, a swarm of conclusions bright in the way they forgive the darkness.
     We tell everyone we know about the field & the lightning bugs, & how we wouldn’t dare try writing them into a poem because we’d fail. A poem, just a series of failures broken down into lines, a series of attempts to assuage the self scattered about & glowing. Lightning bugs pulse, pulsate, beat, throb—all the glorious verbs we usually reserve for the human heart.
     They don’t vanish, it is we who leave them, as if that isn’t the first movement in loss. We leave because we’ll never understand their intimacy, because in understanding there is a slowing that would keep us from our lives.
     For a few singular minutes we watch the lightning bugs while we brush mosquitoes away from ourselves. & how many more sentences have we made with that preposition that keeps things at arm’s length, that ending of from ourselves, from ourselves.
____


===== Ode to the West Wind by Percy Bysshe Shelley
[verse]
____
I
O wild West Wind, thou breath of Autumn's being,
Thou, from whose unseen presence the leaves dead
Are driven, like ghosts from an enchanter fleeing,

Yellow, and black, and pale, and hectic red,
Pestilence-stricken multitudes: O thou,
Who chariotest to their dark wintry bed

The winged seeds, where they lie cold and low,
Each like a corpse within its grave, until
Thine azure sister of the Spring shall blow

Her clarion o'er the dreaming earth, and fill
(Driving sweet buds like flocks to feed in air)
With living hues and odours plain and hill:

Wild Spirit, which art moving everywhere;
Destroyer and preserver; hear, oh hear!

II
Thou on whose stream, mid the steep sky's commotion,
Loose clouds like earth's decaying leaves are shed,
Shook from the tangled boughs of Heaven and Ocean,

Angels of rain and lightning: there are spread
On the blue surface of thine aëry surge,
Like the bright hair uplifted from the head

Of some fierce Maenad, even from the dim verge
Of the horizon to the zenith's height,
The locks of the approaching storm. Thou dirge

Of the dying year, to which this closing night
Will be the dome of a vast sepulchre,
Vaulted with all thy congregated might

Of vapours, from whose solid atmosphere
Black rain, and fire, and hail will burst: oh hear!

III
Thou who didst waken from his summer dreams
The blue Mediterranean, where he lay,
Lull'd by the coil of his crystalline streams,

Beside a pumice isle in Baiae's bay,
And saw in sleep old palaces and towers
Quivering within the wave's intenser day,

All overgrown with azure moss and flowers
So sweet, the sense faints picturing them! Thou
For whose path the Atlantic's level powers

Cleave themselves into chasms, while far below
The sea-blooms and the oozy woods which wear
The sapless foliage of the ocean, know

Thy voice, and suddenly grow gray with fear,
And tremble and despoil themselves: oh hear!

IV
If I were a dead leaf thou mightest bear;
If I were a swift cloud to fly with thee;
A wave to pant beneath thy power, and share

The impulse of thy strength, only less free
Than thou, O uncontrollable! If even
I were as in my boyhood, and could be

The comrade of thy wanderings over Heaven,
As then, when to outstrip thy skiey speed
Scarce seem'd a vision; I would ne'er have striven

As thus with thee in prayer in my sore need.
Oh, lift me as a wave, a leaf, a cloud!
I fall upon the thorns of life! I bleed!

A heavy weight of hours has chain'd and bow'd
One too like thee: tameless, and swift, and proud.

V
Make me thy lyre, even as the forest is:
What if my leaves are falling like its own!
The tumult of thy mighty harmonies

Will take from both a deep, autumnal tone,
Sweet though in sadness. Be thou, Spirit fierce,
My spirit! Be thou me, impetuous one!

Drive my dead thoughts over the universe
Like wither'd leaves to quicken a new birth!
And, by the incantation of this verse,

Scatter, as from an unextinguish'd hearth
Ashes and sparks, my words among mankind!
Be through my lips to unawaken'd earth

The trumpet of a prophecy! O Wind,
If Winter comes, can Spring be far behind?
____


===== what can a poem do? by Darius V. Daughtry
[verse]
____
a poem cannot save a life
cannot Luke Cage your skin
fend off a dark alley attack
cannot make you less woman
or less poor
or less Black
and
thus
treated equally

a poem cannot stop a bullet
stop a bomb
stop terror on your doorstep
your step
even with poem in hand
could be your last
a blast would turn the paper poem is written on into dust
particles
           simile up in smoke
metaphors
           just molecules forgotten

a poem cannot turn back time’s hand
erase mistakes made
or cut, copy, paste memories
a poem cannot delete history’s horrors

but a poem can love
           like hold you and scold you at the same time
a poem can rip away the untruths that have cocooned us
a poem can make you butterfly
           not fly
                      you already fly
but a poem can make you float
no need to watch your step

quiet as kept
a poem can introduce you to yourself
help you discover those hidden
           forbidden parts
a poem be like a mirror sometimes
help you see the crust in your eyes
and the plank

on second thought
a poem can save a life
like wise words granddaddy whispered
like the layer of truth just below the scriptures

a poem cannot stop a bullet
but can swallow the hate and spit back
           a sonnet
that sonic booms
a room till
quotes
float like balloons
goblins and goons
soon just nod their heads
snap their fingers
to what’s written and said

isn’t it ironic

they say the pen is mightier than the sword
but there were few writers on my block
mostly fighters on my block
dropouts that pulled all-nighters on my block
they’d blue and red light us on my block
then indict us on my block
what if there were more writers on my block

on your block
in every barrio and borough
conclave and commonwealth
courtroom and capitol hill
what if they all spilled ink
on pages
allowed the innerworkings of their hearts
to scribble a poem or two

I wonder where we’d be if the masses knew
just what a poem could do.
____


===== Miss you. Would like to take a walk with you. by Gabrielle Calvocoressi
[verse]
____
Do not care if  you just arrive in your skeleton.
Would love to take a walk with you. Miss you.
Would love to make you shrimp saganaki.
Like you used to make me when you were alive.
Love to feed you. Sit over steaming
bowls of pilaf. Little roasted tomatoes
covered in pepper and nutmeg. Miss you.
Would love to walk to the post office with you.
Bring the ghost dog. We’ll walk past the waterfall
and you can tell me about the after.
Wish you. Wish you would come back for a while.
Don’t even need to bring your skin sack. I’ll know
you. I know you will know me even though. I’m
bigger now. Grayer. I’ll show you my garden.
I’d like to hop in the leaf pile you raked but if you
want to jump in? I’ll rake it for you. Miss you
standing looking out at the river with your rake
in your hand. Miss you in your puffy blue jacket.
They’re hip now. I can bring you a new one
if you’ll only come by. Know I told you
it was okay to go. Know I told you
it was okay to leave me. Why’d you believe me?
You always believed me. Wish you would
come back so we could talk about truth.
Miss you. Wish you would walk through my
door. Stare out from the mirror. Come through
the pipes.
____


===== Photograph from September 11 by Wisława Szymborska
[verse]
____
They jumped from the burning floors—
one, two, a few more,
higher, lower.

The photograph halted them in life,
and now keeps them   
above the earth toward the earth.

Each is still complete,
with a particular face
and blood well hidden.

There’s enough time
for hair to come loose,
for keys and coins
to fall from pockets.

They’re still within the air’s reach,
within the compass of places
that have just now opened.

I can do only two things for them—
describe this flight
and not add a last line.
____


===== Ashes of Life by Edna St. Vincent Millay
[verse]
____
Love has gone and left me and the days are all alike;
Eat I must, and sleep I will,  and would that night were here!
But ah!  lie awake and hear the slow hours strike!
Would that it were day again!  with twilight near!

Love has gone and left me and I don't know what to do;
This or that or what you will is all the same to me;
But all the things that I begin I leave before I'm through,
There's little use in anything as far as I can see.

Love has gone and left me,  and the neighbors knock and borrow,
And life goes on forever like the gnawing of a mouse, 
And to-morrow and to-morrow and to-morrow and to-morrow
There's this little street and this little house.
____


===== Leaves by Ursula K. Le Guin
[verse]
____
Years do odd things to identity.
What does it mean to say
I am that child in the photograph
at Kishamish in 1935?
Might as well say I am the shadow
of a leaf of the acacia tree
felled seventy years ago
moving on the page the child reads.
Might as well say I am the words she read
or the words I wrote in other years,
flicker of shade and sunlight
as the wind moves through the leaves.
____

Forgetfulness by Billy Collins
[verse]
____
The name of the author is the first to go
followed obediently by the title, the plot,
the heartbreaking conclusion, the entire novel
which suddenly becomes one you have never read, never even heard of,

as if, one by one, the memories you used to harbor
decided to retire to the southern hemisphere of the brain,
to a little fishing village where there are no phones.

Long ago you kissed the names of the nine muses goodbye
and watched the quadratic equation pack its bag,
and even now as you memorize the order of the planets,

something else is slipping away, a state flower perhaps,
the address of an uncle, the capital of Paraguay.

Whatever it is you are struggling to remember,
it is not poised on the tip of your tongue
or even lurking in some obscure corner of your spleen.

It has floated away down a dark mythological river
whose name begins with an L as far as you can recall

well on your own way to oblivion where you will join those
who have even forgotten how to swim and how to ride a bicycle.

No wonder you rise in the middle of the night
to look up the date of a famous battle in a book on war.
No wonder the moon in the window seems to have drifted   
out of a love poem that you used to know by heart.
____


===== Breaking [News] by Noor Hindi
[verse]
____
We'll wake up, Sunday morning, and read the paper. Read each other. Become
consumers
of each other's stories, a desperate reaching
for another body's warmth—its words buoying us through a world. We carry
graveyards on our backs and I'm holding a lightning bug
hostage in one hand, its light dimming in the warmth
of my fist, and in the other, a pen, to document its death. Isn't that terrible?
I'll ask you, shutting my fist once more.
In interviews, I frame my subject's stories through a lens to make them digestible
to consumers.
I become a machine. A transfer of information. They become a plea for empathy,
an oversaturation of feelings we'll fail at transforming into action.
What’s lost is incalculable.
          And at the end of summer, the swimming pools will be gutted of water.
          And it'll be impossible to swim.
____


===== From “Couplets” by Maggie Millner
[verse]
____
I tried to stay away. Could not. I’d turn to  J
    or T and say: Today’s the day

it stops. Nothing right should feel
    this dirty, nothing real

this quicksilver and fanged. I kept thinking
    of  that show My Strange Addiction,

which was enjoying a comeback among my peers
    in those months, despite its cancellation years

before, conceptual depravity,
    and total exploitation of  its cast. Reality

TV seemed newly relevant, I guess,
    as life itself grew ever more fictitious,

perpendicular to time. Obsession was a subject
    that obsessed me, regardless of  its object,

but I hated to watch strangers being hurt
    by theirs: doll-collecting, surgery, ingesting dirt

and glass. There was no joy depicted—
    just decrepitude, abjection, musty rooms. If  I directed

one, my show would air the pleasures
    of compulsion, and be named Screw It, I’m Going to Text Her,

or  Nothing’s Wrong, You’re  Just in Love Again,
    or True  Life: Turning  Twenty-Eight  in  Brooklyn.
____


===== The Leaves by Austin Smith
[verse]
____
The leaves lived behind the dining room doors.
They only came out when company came out.
Dad would lift one end of the table, my brothers
And I the other. Then we’d shuffle a few steps
Backward, pulling the table apart.
Turned out that, like the loaves and fishes,
The table wasn’t finite.
We could make it as long as we needed it to be.
Did we need one leaf, two leaves, three?
It depended on who all was coming.
I loved the nights we needed all the leaves.
They meant there were still too many
Of  us to fit around the leafless table.
But I knew one day there’d be no need for them.
Then what would we do with the leaves?
I thought how it would be better for a few of us
To sit at too long a table that had three leaves in it
And have to raise our voices
Than to sit whispering around the leafless one.
____


===== Happiness by Jane Kenyon
[verse]
____
There’s just no accounting for happiness,
or the way it turns up like a prodigal
who comes back to the dust at your feet
having squandered a fortune far away.

And how can you not forgive?
You make a feast in honor of what
was lost, and take from its place the finest
garment, which you saved for an occasion
you could not imagine, and you weep night and day
to know that you were not abandoned,
that happiness saved its most extreme form
for you alone.

No, happiness is the uncle you never
knew about, who flies a single-engine plane
onto the grassy landing strip, hitchhikes
into town, and inquires at every door
until he finds you asleep midafternoon
as you so often are during the unmerciful
hours of your despair.

It comes to the monk in his cell.
It comes to the woman sweeping the street
with a birch broom, to the child
whose mother has passed out from drink.
It comes to the lover, to the dog chewing
a sock, to the pusher, to the basketmaker,
and to the clerk stacking cans of carrots
in the night.
                     It even comes to the boulder
in the perpetual shade of pine barrens,
to rain falling on the open sea,
to the wineglass, weary of holding wine.
____


===== Wild nights - Wild nights! (269) by Emily Dickinson
[verse]
____
Wild nights - Wild nights!
Were I with thee
Wild nights should be
Our luxury!

Futile - the winds -
To a Heart in port -
Done with the Compass -
Done with the Chart!

Rowing in Eden -
Ah - the Sea!
Might I but moor - tonight -
In thee!
____



===== Nothing Is Far by Robert Francis
[verse]
____
Though I have never caught the word
Of God from any calling bird,
I hear all that the ancients heard.
 
Though I have seen no deity
Enter or leave a twilit tree,
I see all that the seers see.
 
A common stone can still reveal
Something not stone, not seen, yet real.
What may a common stone conceal?
 
Nothing is far that once was near.
Nothing is hid that once was clear.
Nothing was God that is not here.
 
Here is the bird, the tree, the stone.
Here in the sun I sit alone
Between the known and the unknown.
____



===== Sonnet 73: That time of year thou mayst in me behold by William Shakespeare
[verse]
____
That time of year thou mayst in me behold
When yellow leaves, or none, or few, do hang
Upon those boughs which shake against the cold,
Bare ruin'd choirs, where late the sweet birds sang.
In me thou see'st the twilight of such day
As after sunset fadeth in the west,
Which by and by black night doth take away,
Death's second self, that seals up all in rest.
In me thou see'st the glowing of such fire
That on the ashes of his youth doth lie,
As the death-bed whereon it must expire,
Consum'd with that which it was nourish'd by.
This thou perceiv'st, which makes thy love more strong,
To love that well which thou must leave ere long.
____


===== If For Each Of Us by James Ragan
[verse]
____
a rope could swing us
long and light across a widening trough
of all that fails us in our lives,
I woult tant to land upon the Isle of Echo,
lush with repetition, green with being
original in brith and twice the twin
a wave might dance along the skerry.
I would want a canyon tall for hawks to carry
long the deep tattoo of voices on the air.
I would want an ear to hear
what words to read again to memory,
what verse to carol, thoughts to root
before the sparrow's flight the mind has taken
comes to rest on truth.
And should the landing fail its footing,
I would want to know what inpsiration
in shorter light one syllable might repeat 
as in the swash the flat-stone makes
to skip across the light in water
or the voice a wind gives to birch and linden.
I would want the distance to all understanding
to narrow just enough to fail at failure.
I would want a meoldy of chances
to learn to love again what first I dreamed,
free as wonder, soft as touch,
and of all things simple
to care again for them as much.
____

===== My Therapist Wants to Know about My Relationship to Work by Tiana Clark
[verse]
____
I hustle
upstream.
I grasp.
I grind.
I control & panic. Poke
balloons in my chest,
always popping there,
always my thoughts thump,
thump. I snooze — wake & go
boom. All day, like this I short
my breath. I scroll & scroll.
I see what you wrote — I like.
I heart. My thumb, so tired.
My head bent down, but not
in prayer, heavy from the looking.
I see your face, your phone-lit
faces. I tap your food, two times
for more hearts. I retweet.
I email: yes & yes & yes.
Then I cry & need to say: no-no-no.
Why does it take so long to reply?
I FOMO & shout. I read. I never
enough. New book. New post.
New ping. A new tab, then another.
Papers on the floor, scattered & stacked.
So many journals, unbroken white spines,
waiting. Did you hear that new new?
I start to text back. Ellipsis, then I forget.
I balk. I lazy the bed. I wallow when I write.
I truth when I lie. I throw a book
when a poem undoes me. I underline
Clifton: today we are possible. I start
from image. I begin with Phillis Wheatley.
I begin with Phillis Wheatley. I begin
with Phillis Wheatley reaching for coal.
I start with a napkin, receipt, or my hand.
I muscle memory. I stutter the page. I fail.
Hit delete — scratch out one more line. I sonnet,
then break form. I make tea, use two bags.
Rooibos again. I bathe now. Epsom salt.
No books or phone. Just water & the sound
of water filling, glory — be my buoyant body,
bowl of me. Yes, lavender, more bubbles
& bath bomb, of course some candles too.
All alone with Coltrane. My favorite, “Naima,”
for his wife, now for me, inside my own womb.
Again, I child back. I float. I sing. I simple
& humble. Eyes close. I low my voice,
was it a psalm? Don’t know. But I stopped.
____



The Infirmament by Dean Young
[verse]
____
An end is always punishment for a beginning.
If you’re Catholic, sadness is punishment
for happiness, you become the bug you squash
if you’re Hindu, a flinty space opens
in your head after a long night of laughter
and wine. For waking there are dreams,
from French poetry, English poetry,
for light fire although sometimes
fire must be punished by light
which is why psychotherapy had to be invented.
A father may say nothing to a son for years.
A wife may keep something small folded deep
in her underwear drawer. Clouds come in
resembling the terrible things we believe
about ourselves, a rock comes loose
from a ledge, the baby just cries
and cries. Doll in a chair,
windshield wipers, staring off
into the city lights. For years
you may be unable to hear the word monkey
without a stab in the heart because
she called you that the summer she thought
she loved you and you thought you loved
someone else and everyone loved
your salad dressing. And the daffodils
come up in the spring and the snow covers
the road in winter and the water covers
the deep trenches in the sea where all the time
the inner stuff of this earth surges up
which is how the continents are made
and broken.
____


===== Golden Hour by Kimberly Casey
[verse]
____
When you caught one to keep,
we took it home and I asked you to teach me.
You showed me how to spike the brain—
I thanked the fish, looked away, pressed down.
We bled it, shaved away the scales,
severed meat from bone.

I’m afraid of leaving my loved ones alone.
Flying into an endless sunset the next day,
a soft glow through the window,
and every passenger is glazed
a smooth bronze. Every other seat empty,
each face masked, some with simple fabric, others
medical-grade filtration set beneath serious eyes.

No one here talks much.
Bodies pull away from the aisle
each time a passenger scurries by.
If a plane crashes in the middle of a pandemic,
would the world make a sound?
How do we grieve
one loss among so many?

Yesterday the breeze caught the water
making waves beneath the boat,
and you swayed staring out
toward the setting sun.
Your skin slick with sweat
bronzed in the light bouncing
under the bridge where you waited
for something to bite—

I told you I didn’t understand
the need to maim something
just to send it swimming back below
with a taste of blood.
You said we are all violent.
It’s about finding the way out
that does the least damage.
____



===== Trouble with Math in a One-Room Country School by Jane Kenyon
[verse]
____
The others bent their heads and started in.
Confused, I asked my neighbor
to explain—a sturdy, bright-cheeked girl
who brought raw milk to school from her family’s
herd of Holsteins. Ann had a blue bookmark,
and on it Christ revealed his beating heart,
holding the flesh back with His wounded hand.
Ann understood division. . . .

Miss Moran sprang from her monumental desk
and led me roughly through the class
without a word. My shame was radical
as she propelled me past the cloakroom
to the furnace closet, where only the boys
were put, only the older ones at that.
The door swung briskly shut.

The warmth, the gloom, the smell
of sweeping compound clinging to the broom
soothed me. I found a bucket, turned it
upside down, and sat, hugging my knees.
I hummed a theme from Haydn that I knew
from my piano lessons. . . .
and hardened my heart against authority.
And then I heard her steps, her fingers
on the latch. She led me, blinking
and changed, back to the class.
____



=====Moss-Gathering by Theodore Roethke
[verse]
____
To loosen with all ten fingers held wide and limber
And lift up a patch, dark-green, the kind for lining cemetery baskets,
Thick and cushiony, like an old-fashioned doormat, 
The crumbling small hollow sticks on the underside mixed with roots, 
And wintergreen berries and leaves still stuck to the top, —
That was moss-gathering. 
But something always went out of me when I dug loose those carpets 
Of green, or plunged to my elbows in the spongy yellowish moss of the marshes:
And afterwards I always felt mean, jogging back over the logging road, 
As if I had broken the natural order of things in that swampland;
Disturbed some rhythm, old and of vast importance,
By pulling off flesh from the living planet;
As if I had committed, against the whole scheme of life, a desecration. 
____




===== Praise Song for the Day by Elizabeth Alexander
[verse]
____
A Poem for Barack Obama’s Presidential Inauguration

Each day we go about our business,
walking past each other, catching each other’s
eyes or not, about to speak or speaking.

All about us is noise. All about us is
noise and bramble, thorn and din, each
one of our ancestors on our tongues.

Someone is stitching up a hem, darning
a hole in a uniform, patching a tire,
repairing the things in need of repair.

Someone is trying to make music somewhere,
with a pair of wooden spoons on an oil drum,
with cello, boom box, harmonica, voice.

A woman and her son wait for the bus.
A farmer considers the changing sky.
A teacher says, Take out your pencils. Begin.

We encounter each other in words, words
spiny or smooth, whispered or declaimed,
words to consider, reconsider.

We cross dirt roads and highways that mark
the will of some one and then others, who said
I need to see what’s on the other side.

I know there’s something better down the road.
We need to find a place where we are safe.
We walk into that which we cannot yet see.

Say it plain: that many have died for this day.
Sing the names of the dead who brought us here,
who laid the train tracks, raised the bridges,

picked the cotton and the lettuce, built
brick by brick the glittering edifices
they would then keep clean and work inside of.

Praise song for struggle, praise song for the day.
Praise song for every hand-lettered sign,
the figuring-it-out at kitchen tables.

Some live by love thy neighbor as thyself,
others by first do no harm or take no more
than you need. What if the mightiest word is love?

Love beyond marital, filial, national,
love that casts a widening pool of light,
love with no need to pre-empt grievance.

In today’s sharp sparkle, this winter air,
any thing can be made, any sentence begun.
On the brink, on the brim, on the cusp,

praise song for walking forward in that light.
____



===== In November by Lisel Mueller
[verse]
____
Outside the house the wind is howling
and the trees are creaking horribly.
This is an old story
with its old beginning,
as I lay me down to sleep.
But when I wake up, sunlight
has taken over the room.
You have already made the coffee
and the radio brings us music
from a confident age. In the paper
bad news is set in distant places.
Whatever was bound to happen
in my story did not happen.
But I know there are rules that cannot be broken.
Perhaps a name was changed.
A small mistake. Perhaps
a woman I do not know
is facing the day with the heavy heart
that, by all rights, should have been mine.
____


===== Invisible Children by Mariana Llanos
[verse]
____
Invisible children fall
through the cracks of the system
like Alice in the rabbit hole.
But these children won’t find
an eat-me cake or a drink-me bottle.
They won’t wake up on the lap
of a loving sister.
They’ll open their eyes on the hand
of a monster called Negligence
who’ll poke them with its sharp teeth
and bait them with its heartless laughter,
like a wild thing in a wild rumpus.
But the children won’t awake
to the smell of a warm supper,
nor will they find a purple crayon
to draw an escape door or a window.
Instead they’ll make a mirror
of a murky puddle on the city street
which won’t tell them they’re beautiful
but it’ll show their scars, as invisible to others
as these children are.
____


===== The Line of Fire by Mariana Llanos
[verse]
____
our children in the line of fire
scrambling for their lives
while we dreamily polish our guns
reminders of the good old days
when we lived in the wild west
when war was a synonym of greatness
when guns didn’t fire eight hundred rounds a minute
we cherish the smell of red brass and gunpowder
as our children practice hiding in closets
learning to shiver and cry in silence
instead of multiplication facts
we pat our sweet babies’ heads
and send them off to the line of fire
____

===== The Only Me by Pat Mora
[verse]
____
Spinning through space for eons,
our earth—oceans, rivers, mountains,
glaciers, tigers, parrots, redwoods—
        evolving wonders.

And our vast array, generations
of humans—all shapes, colors, languages.

        Can I be the only me?

Our earth: so much beauty, hate,
        goodness, greed.

“Study. Cool the climate,” advises my teacher.
                      “Grow peace.”

        Can I be the only me,
                      become all my unique complexity?
____

===== Summer by Chen Chen
[verse]
____
You are the ice cream sandwich connoisseur of your generation.
Blessed are your floral shorteralls, your deeply pink fanny pack with  travel-size lint roller just in case.
Level of splendiferous in your outfit: 200.
Types of invisible pain stemming from adolescent disasters in classrooms, locker rooms, & quite often Toyota Camrys: at least 10,000.
You are not a jigglypuff, not yet a wigglytuff.
Reporters & fathers call your generation “the worst.”
Which really means “queer kids who could go online & learn that queer doesn’t have to mean disaster.”
Or dead.
Instead, queer means, splendiferously, you.
& you means someone who knows that common flavors for ice cream  sandwiches in Singapore include red bean, yam, & honeydew.
Your powers are great, are growing.
One day you will create an online personality quiz that also freshens the breath.
The next day you will tell your father, You were wrong to say that I had to change.
To make me promise I would. To make me promise.
& promise.
____


===== Who Will Tell Them? by Michael Simms
[verse]
____
It turns out you can kill the earth,
Crack it open like an egg.
It turns out you can murder the sea,
Poison your own children
Without even thinking about it.

Goodbye passenger pigeon, once
So numerous men threw nets over trees
And fed you to pigs. Goodbye
Cuckoo bird who lays eggs
In the nests of strangers.

Goodbye elephant bird
Who frightened Sinbad.
Goodbye wigeon,
Curlew, lapwing, crake.
Goodbye Mascarene coot.
Sorry we never had a chance to meet.

Who knew you could wipe out
Everything? Who knew
You could crack the earth open
Like an egg? Who knew
The endless ocean
Was so small?

Right now, there are children playing on the shore.
There are children lying in hospital beds.
There are children trusting us.
Who will tell them what we’ve done?
____


===== White Apples by Donald Hall
[verse]
____
when my father had been dead a week
I woke
with his voice in my ear
                                           I sat up in bed
and held my breath
and stared at the pale closed door

white apples and the taste of stone

if he called again
I would put on my coat and galoshes
____



===== Alone by Jack Gilbert
[verse]
____
I never thought Michiko would come back
after she died. But if she did, I knew
it would be as a lady in a long white dress.
It is strange that she has returned
as somebody's dalmatian. I meet
the man walking her on a leash
almost every week. He says good morning
and I stoop down to calm her. He said
once that she was never like that with
other people. Sometimes she is tethered
on their lawn when I go by. If nobody
is around, I sit on the grass. When she
finally quiets, she puts her head in my lap
and we watch each other's eyes as I whisper
in her soft ears. She cares nothing about
the mystery. She likes it best when
I touch her head and tell her small
things about my days and our friends.
That makes her happy the way it always did.
____



===== Good Bones by Maggie Smith
[verse]
____
Life is short, though I keep this from my children.
Life is short, and I’ve shortened mine
in a thousand delicious, ill-advised ways,
a thousand deliciously ill-advised ways
I’ll keep from my children. The world is at least
fifty percent terrible, and that’s a conservative
estimate, though I keep this from my children.
For every bird there is a stone thrown at a bird.
For every loved child, a child broken, bagged,
sunk in a lake. Life is short and the world
is at least half terrible, and for every kind
stranger, there is one who would break you,
though I keep this from my children. I am trying
to sell them the world. Any decent realtor,
walking you through a real shithole, chirps on
about good bones: This place could be beautiful,
right? You could make this place beautiful.
____


===== Plastic: A Personal History by Elizabeth Bradfield
[verse]
____
How can I find a way to praise
it? Do the early inventors & embracers
churn with regret? I don’t think my parents
—born in the swing toward ubiquity—chew
& chew & chew on plastic. But of course they
do. Bits in water, food-flesh, air.
And their parents? I remember Dad
mocking his mother’s drawer of saved
rubber bands and his father-in-law’s red,
corroded jerry can, patched and patched,
never replaced for new, for never-
rusting.
             Cash or plastic? Plastic. Even
for gum. We hate the $5 minimum.
Bills paperless, automatic, almost
unreal.
           My toys were plastic, castle
and circus train and yo-yo. Did my lunches
ever get wrapped in waxed paper or
was it all Saran, Saran, Saran?
                                                Sarah’s mom
was given, in Girl Scouts, a blue sheet
of plastic to cut, sew, and trim with white piping
into pouches for camping. Sarah has it still,
brittle but useful. Merit badge for waterproofing.
For everlasting.
                         You, too, must have heard stories,
now quaint as carriages, of first plastic, pre-plastic.
Eras of glass, waxed cloth, and tin.
Of shared syringes.

All our grocery bags, growing up,
were paper. Bottom hefted on forearm, top
crunched into grab. We used them
to line the kitchen garbage pail.
                                                  Not that long
ago, maybe a decade, I made purses for my sisters
out of putty-colored, red-lettered plastic Safeway
bags. I’d snag a stack each time I went, then fold
and sew, quilt with bright thread, line with thrift store
blouses. They were sturdy and beautiful. Rainproof
and light. Clever. So clever.
                                           I regret them.
And the plastic toothpicks, folders, shoes that seemed
so cheap, so easy, so use-again and thus
less wasteful, then. What did we do before
to-go lids? Things must have just spilled
and spilled.
                      Do you know
what I mean? I mean, what pearl forms
around a grain of plastic in an oyster?
Is it as beautiful? Would you wear it?
Would you buy it for your daughter
so she in turn could pass it down and
pass it down and pass it down?
____


===== About Suffering by Elisa Gabbert
[verse]
____
Part of suffering is the useless urge to announce that you’re suffering.
 
There is no other way to say it: I’m suffering. Just to say “I suffer”
helps.
 
I read somewhere, “we become lyrical when we suffer.”
 
Happiness is suffering for the right reasons.
 
First-order suffering is second-order happiness.
 
You have to suffer for beauty? Because you have to suffer.
 
We pride ourselves on a high quality of suffering.
 
Turgenev was born in 1818 in the Province of Orel, and suffered
during his childhood from a tyrannical mother.
 
In the past their suffering was less absurd.
 
The problem is, everything’s worse. Like, paper or plastic? We’re all
still going to die suffering.
 
I value being alone with my thoughts, but it’s weird to say, “This
thing that makes us suffer less, we have to stop doing it.”
 
Isn’t it kind of the point of culture to assuage our feeling needless
and alone?
 
How does one suffer “gladly,” exactly?
 
At least the rich get to suffer in comfort.
 
It makes the life feel longer. Live to suffer another day.
 
One’s past suffering can be a great source of comfort. A torturous
luxury. Velvet upholstery.
 
Suffering is happiness, after forty minutes of desolate shuffling. The
point is, life is suffering.
 
About suffering, no one is ever wrong.
____



===== Freedom by Langston Hughes
[verse]
____
Freedom will not come
Today, this year
            Nor ever
Through compromise and fear.
 
I have as much right
As the other fellow has
            To stand
On my two feet
And own the land.
 
I tire so of hearing people say,
Let things take their course.
Tomorrow is another day.
I do not need my freedom when I’m dead.
I cannot live on tomorrow’s bread.
            Freedom
            Is a strong seed
            Planted
            In a great need.
            I live here, too.
            I want my freedom
            Just as you.   
____



===== Destruction by Charles Baudelaire translated by c. F. Macintyre
[verse]
____
At my side the Demon writhes forever,
Swimming around me like impalpable air;
As I breathe, he burns my lungs like fever
And fills me with an eternal guilty desire.

Knowing my love of Art, he snares my senses,
Apearing in woman's most seductive forms,
And, under the sneak's plausible pretenses,
Lips grow accustomed to his lewd love-charms.

He leads me thus, far from the sight of God,
Panting and broken with fatigue into
The wilderness of Ennui, deserted and broad,

And into my bewildered eyes he throws
Visions of festering wounds and filthy clothes,
And all Destruction's bloody retinue.
____



===== Try to Praise the Mutilated World by Adam Zagajewski translated by Clare Cavanagh
[verse]
____
Try to praise the mutilated world.
Remember June's long days,
and wild strawberries, drops of rosé wine.
The nettles that methodically overgrow
the abandoned homesteads of exiles.
You must praise the mutilated world.
You watched the stylish yachts and ships;
one of them had a long trip ahead of it,
while salty oblivion awaited others.
You've seen the refugees going nowhere,
you've heard the executioners sing joyfully.
You should praise the mutilated world.
Remember the moments when we were together
in a white room and the curtain fluttered.
Return in thought to the concert where music flared.
You gathered acorns in the park in autumn
and leaves eddied over the earth's scars.
Praise the mutilated world
and the gray feather a thrush lost,
and the gentle light that strays and vanishes
and returns.
____



===== The Great Tsunami by Michele Wolf
[verse]
____
She recognizes its crest in the way he looks at her. 
The wave is as vast as the roiling mass in the Japanese
Print they had paused in front of at the museum,
Capped with ringlets of foam, all surging sinew.
That little village along the shore would be
Totally lost. There is no escaping this.
The wave is flooding his heart,
And he is sending the flood
Her way. It rushes
Over her.

Can you look at one face
For the whole of a life?

Does the moon peer down
At the tides and hunger for home?
____




===== A Plague of Poets by C. D. Wright
[verse]
____
A question posed to Flannery O'Connor, as to whether writing programs stifled writers, drew the famous, tart rejoinder that in her opinion they didn't stifle nearly enough.

Even if, as it is often said, there are too many of us—poets, that is—that the field is too crowded (as opposed to too many hedge-fund managers or too many pharmaceutical lobbyists or too many fundamentalists), time, rejection, discouragement, and the inevitable practicalities and detours (some of them fortuitous), as well as wasted energy, the slow seepage or sudden shift of interest, premature death, burdensome debt or better offers, usually cure the problem of overpopulation. In other words, there are plenty of natural predators
____



===== A Litany for Survival by Audre Lorde
[verse]
____
For those of us who live at the shoreline
standing upon the constant edges of decision
crucial and alone
for those of us who cannot indulge
the passing dreams of choice
who love in doorways coming and going
in the hours between dawns
looking inward and outward
at once before and after
seeking a now that can breed
futures
like bread in our children’s mouths
so their dreams will not reflect
the death of ours;
 
For those of us
who were imprinted with fear
like a faint line in the center of our foreheads
learning to be afraid with our mother’s milk
for by this weapon
this illusion of some safety to be found
the heavy-footed hoped to silence us
For all of us
this instant and this triumph
We were never meant to survive.
 
And when the sun rises we are afraid
it might not remain
when the sun sets we are afraid
it might not rise in the morning
when our stomachs are full we are afraid
of indigestion
when our stomachs are empty we are afraid
we may never eat again
when we are loved we are afraid
love will vanish
when we are alone we are afraid
love will never return
and when we speak we are afraid
our words will not be heard
nor welcomed
but when we are silent
we are still afraid
 
So it is better to speak
remembering
we were never meant to survive.
____


===== When I have Fears That I May Cease to Be by John Keats
[verse]
____
When I have fears that I may cease to be
   Before my pen has gleaned my teeming brain,
Before high-pilèd books, in charactery,
   Hold like rich garners the full ripened grain;
When I behold, upon the night’s starred face,
   Huge cloudy symbols of a high romance,
And think that I may never live to trace
   Their shadows with the magic hand of chance;
And when I feel, fair creature of an hour,
   That I shall never look upon thee more,
Never have relish in the faery power
   Of unreflecting love—then on the shore
Of the wide world I stand alone, and think
Till love and fame to nothingness do sink.
____


===== [Enemies] by Wendell Berry
[verse]
____
If you are not to become a monster,
you must care what they think.
If you care what they think,
 
how will you not hate them,
and so become a monster
of the opposite kind? From where then
 
is love to come—love for your enemy
that is the way of liberty?
From forgiveness. Forgiven, they go
 
free of you, and you of them;
they are to you as sunlight
on a green branch. You must not
 
think of them again, except
as monsters like yourself,
pitiable because unforgiving.
____


===== To the Swimmer by Countee Cullen
[verse]
____
Now as I watch you, strong of arm and endurance, battling and struggling
With the waves that rush against you, ever with invincible strength returning
Into my heart, grown each day more tranquil and peaceful, comes a fierce longing
Of mind and soul that will not be appeased until, like you, I breast yon deep and boundless expanse of blue.

With an outward stroke of power intense your mighty arm goes forth,
Cleaving its way through waters that rise and roll, ever a ceaseless vigil keeping
Over the treasures beneath.

My heart goes out to you of dauntless courage and spirit indomitable,
And though my lips would speak, my spirit forbids me to ask,
“Is your heart as true as your arm?”
____



===== Beginning by James Wright
[verse]
____
The moon drops one or two feathers into the field.   
The dark wheat listens.
Be still.
Now.
There they are, the moon's young, trying
Their wings.
Between trees, a slender woman lifts up the lovely shadow
Of her face, and now she steps into the air, now she is gone
Wholly, into the air.
I stand alone by an elder tree, I do not dare breathe
Or move.
I listen.
The wheat leans back toward its own darkness,
And I lean toward mine.
____



===== After Filing for Divorce by Chelsea Rathburn
[verse]
____
Your paperwork in, it’s like the morning after
a party, the shaken survey of damage,
a waste of bottles where there was laughter.
It all seems so much more than you can manage:
the accusing cups and stubbed-out cigarettes,
the sun assaulting the window, your throbbing head.
It’s not enough to face your own regrets
(though they’re coming back fast, the things you said)
because someone’s trailed bean dip across the table,
someone’s ground salsa in the rug with his shoe.
So you start to clean, as much as you are able,
and think how far those hours have fled from you,
before the hangover and your sour tongue,
when you felt lovely, and infinite, and young.
____



===== In Passing by Lisel Mueller
[verse]
____
How swiftly the strained honey
of afternoon light
flows into darkness

and the closed bud shrugs off
its special mystery
in order to break into blossom

as if what exists, exists
so that it can be lost
and become precious
____



Song: “Blow, blow, thou winter wind” by William Shakespeare
[verse]
____
Blow, blow, thou winter wind,
   Thou art not so unkind
      As man’s ingratitude;
   Thy tooth is not so keen,
Because thou art not seen,
      Although thy breath be rude.
Heigh-ho! sing, heigh-ho! unto the green holly:
Most friendship is feigning, most loving mere folly:
   Then, heigh-ho, the holly!
      This life is most jolly.

   Freeze, freeze, thou bitter sky,
   That dost not bite so nigh
      As benefits forgot:
   Though thou the waters warp,
      Thy sting is not so sharp
      As friend remembered not.
Heigh-ho! sing, heigh-ho! unto the green holly...
____



===== New Year’s Day by Kim Addonizio
[verse]
____
The rain this morning falls   
on the last of the snow

and will wash it away. I can smell   
the grass again, and the torn leaves

being eased down into the mud.   
The few loves I’ve been allowed

to keep are still sleeping
on the West Coast. Here in Virginia

I walk across the fields with only   
a few young cows for company.

Big-boned and shy,
they are like girls I remember

from junior high, who never   
spoke, who kept their heads

lowered and their arms crossed against   
their new breasts. Those girls

are nearly forty now. Like me,   
they must sometimes stand

at a window late at night, looking out   
on a silent backyard, at one

rusting lawn chair and the sheer walls   
of other people’s houses.

They must lie down some afternoons   
and cry hard for whoever used

to make them happiest,   
and wonder how their lives

have carried them
this far without ever once

explaining anything. I don’t know   
why I’m walking out here

with my coat darkening
and my boots sinking in, coming up

with a mild sucking sound   
I like to hear. I don’t care

where those girls are now.   
Whatever they’ve made of it

they can have. Today I want   
to resolve nothing.

I only want to walk
a little longer in the cold

blessing of the rain,   
and lift my face to it.
____


===== Q & A by Kenneth Fearing
[verse]
____
Where analgesia may be found to ease the infinite, minute scars of the day;
What final interlude will result, picked bit by bit from the morning's hurry, the lunch-hour boredom, the fevers of the night;
Why this one is cherished by the gods, and that one not;
How to win, and win again, and again, staking wit alone against a sea of time;
Which man to trust and, once found, how far—

Will not be found in Matthew, Mark, Luke, or John,
Nor Blackstone, nor Gray's, nor Dun & Bradstreet, nor Freud, nor Marx,
Nor the sage of the evening news, nor the corner astrologist, nor in any poet,

Nor what sort of laughter should greet the paid pronouncements of the great,
Nor what pleasure the mulitudes have, brining lunch and the children to watch the condemned to be plunged into death,

Nor why the sun should rise tomorrow,
Nor how the moon still weaves upon the ground, through the leaves, so much silence and so much peace.
____




===== From a Window By Christian Wiman
[verse]
____
Incurable and unbelieving
in any truth but the truth of grieving,

I saw a tree inside a tree
rise kaleidoscopically

as if the leaves had livelier ghosts.
I pressed my face as close

to the pane as I could get
to watch that fitful, fluent spirit

that seemed a single being undefined
or countless beings of one mind

haul its strange cohesion
beyond the limits of my vision

over the house heavenwards.
Of course I knew those leaves were birds.

Of course that old tree stood
exactly as it had and would

(but why should it seem fuller now?)
and though a man's mind might endow

even a tree with some excess
of life to which a man seems witness,

that life is not the life of men.
And that is where the joy came in.
____


===== The World Is Too Much With Us BY WILLIAM WORDSWORTH
[verse]
____
The world is too much with us; late and soon,
Getting and spending, we lay waste our powers;—
Little we see in Nature that is ours;
We have given our hearts away, a sordid boon!
This Sea that bares her bosom to the moon;
The winds that will be howling at all hours,
And are up-gathered now like sleeping flowers;
For this, for everything, we are out of tune;
It moves us not. Great God! I’d rather be
A Pagan suckled in a creed outworn;
So might I, standing on this pleasant lea,
Have glimpses that would make me less forlorn;
Have sight of Proteus rising from the sea;
Or hear old Triton blow his wreathèd horn.
____

===== Insomnia by Elizabeth Bishop
[verse]
____
The moon in the bureau mirror
looks out a million miles
(and perhaps with pride, at herself,
but she never, never smiles)
far and away beyond sleep, or
perhaps she's a daytime sleeper.

By the Universe deserted,
she'd tell it to go to hell,
and she'd find a body of water,
or a mirror, on which to dwell.
So wrap up care in a cobweb
and drop it down the well

into that world inverted
where left is always right,
where the shadows are really the body,
where we stay awake all night,
where the heavens are shallow as the sea
is now deep, and you love me.
____


==== Quotations


===== From Little Gidding by T.S. Elliot
[verse]
____
We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
____


===== From Citizenship in a Republic by Theodore Roosevelt
[verse]
____
It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat.
____


===== From Walden by Henry David Thoreau
[verse]
____
The mass of men lead lives of quiet desperation. What is called resignation is confirmed desperation. From the desperate city you go into the desperate country, and have to console yourself with the bravery of minks and muskrats. A stereotyped but unconscious despair is concealed even under what are called the games and amusements of mankind. There is no play in them, for this comes after work. But it is a characteristic of wisdom not to do desperate things.”
____


===== From Self-Reliance by Ralph Waldo Emerson
[verse]
____
A man should learn to detect and watch that gleam of light which flashes across his mind from within, more than the lustre of the firmament of bards and sages.
____

[verse]
____
There is a time in every man’s education when he arrives at the conviction that envy is ignorance; that imitation is suicide; that he must take himself for better, for worse, as his portion; that though the wide universe is full of good, no kernel of nourishing corn can come to him but through his toil bestowed on that plot of ground which is given to him to till.
____

[verse]
____
It is easy in the world to live after the world’s opinion; it is easy in solitude to live after our own; but the great man is he who in the midst of the crowd keeps with perfect sweetness the independence of solitude. 

The objection to conforming to usages that have become dead to you is that it scatters your force. It loses your time and blurs the impression of your character. If you maintain a dead church, contribute to a dead Bible-society, vote with a great party either for the government or against it, spread your table like base housekeepers—under all these screens I have difficulty to detect the precise man you are: and of course so much force is withdrawn from your proper life. But do your work, and I shall know you.
____

[verse]
____
We want men and women who shall renovate life and our social state, but we see that most natures are insolvent, cannot satisfy their own wants, have an ambition out of all proportion to their practical force and do lean and beg day and night continually. Our housekeeping is mendicant, our arts, our occupations, our marriages, our religion we have not chosen, but society has chosen for us. We are parlor soldiers. We shun the rugged battle of fate, where strength is born.
____

[verse]
____
Insist on yourself; never imitate. Your own gift you can present every moment with the cumulative force of a whole life’s cultivation; but of the adopted talent of another you have only an extemporaneous half possession. That which each can do best, none but his Maker can teach him. No man yet knows what it is, nor can, till that person has exhibited it. Where is the master who could have taught Shakspeare? Where is the master who could have instructed Franklin, or Washington, or Bacon, or Newton? Every great man is a unique. The Scipionism of Scipio is precisely that part he could not borrow. Shakspeare will never be made by the study of Shakspeare. Do that which is assigned you, and you cannot hope too much or dare too much. There is at this moment for you an utterance brave and grand as that of the colossal chisel of Phidias, or trowel of the Egyptians, or the pen of Moses or Dante, but different from all these. Not possibly will the soul, all rich, all eloquent, with thousand-cloven tongue, deign to repeat itself; but if you can hear what these patriarchs say, surely you can reply to them in the same pitch of voice; for the ear and the tongue are two organs of one nature. Abide in the simple and noble regions of thy life, obey thy heart, and thou shalt reproduce the Foreworld again.
____


===== From Portrait of an Artist as a Young Man by James Joyce
[verse]
____
You have asked me what I would do and what I would not do. I will tell you what I will do and what I will not do. I will not serve that in which I no longer believe whether it call itself my home, my fatherland or my church: and I will try to express myself in some mode of life or art as freely as I can and as wholly as I can, using for my defence the only arms I allow myself to use -- silence, exile, and cunning...You made me confess the fears that I have. But I will tell you also what I do not fear. I do not fear to be alone or to be spurned for another or to leave whatever I have to leave. And I am not afraid to make a mistake, even a great mistake, a lifelong mistake and perhaps as long as eternity too
____


===== From Juliet Ceasar by William Shakespeare
[verse]
____
There is a tide in the affairs of men.
Which, taken at the flood, leads on to fortune;
Omitted, all the voyage of their life
Is bound in shallows and in miseries.
On such a full sea are we now afloat,
And we must take the current when it serves,
Or lose our ventures.
____


===== From Richard II by William Shakespeare
[verse]
____
No matter where; of comfort no man speak:
Let’s talk of graves, of worms, and epitaphs;
Make dust our paper and with rainy eyes
Write sorrow on the bosom of the earth,
Let’s choose executors and talk of wills:
And yet not so, for what can we bequeath
Save our deposed bodies to the ground?
Our lands, our lives and all are Bolingbroke’s,
And nothing can we call our own but death
And that small model of the barren earth
Which serves as paste and cover to our bones.
For God’s sake, let us sit upon the ground
And tell sad stories of the death of kings;
How some have been deposed; some slain in war,
Some haunted by the ghosts they have deposed;
Some poison’d by their wives: some sleeping kill’d;
All murder’d: for within the hollow crown
That rounds the mortal temples of a king
Keeps Death his court and there the antic sits,
Scoffing his state and grinning at his pomp,
Allowing him a breath, a little scene,
To monarchize, be fear’d and kill with looks,
Infusing him with self and vain conceit,
As if this flesh which walls about our life,
Were brass impregnable, and humor’d thus
Comes at the last and with a little pin
Bores through his castle wall, and farewell king!
Cover your heads and mock not flesh and blood
With solemn reverence: throw away respect,
Tradition, form and ceremonious duty,
For you have but mistook me all this while:
I live with bread like you, feel want,
Taste grief, need friends: subjected thus,
How can you say to me, I am a king?
____


===== From King James Bible
[verse]
____
Hebrews, Ch. 12, 1
Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,
____

[verse]
____
Corinthians 1, Ch. 13
Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.

And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.

And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.

Charity suffereth long, and is kind; charity envieth not;  charity vaunteth not itself, is not puffed up,

Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;

Rejoiceth not in iniquity, but rejoiceth in the truth;

Beareth all things, believeth all things, hopeth all things, endureth all things.

Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.

For we know in part, and we prophesy in part.

But when that which is perfect is come, then that which is in part shall be done away.

When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man,

I put away childish things.

For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.

And now abideth faith, hope, charity, these three; but the greatest of these is charity.
____

[verse]
____
Mark, Ch. 8, 35-37
For what shall it profit a man, if he shall gain the whole world, and lose his own soul?

Or what shall a man give in exchange for his soul?
____

[verse]
____
Matthew, Ch. 6 19-23
Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal:

But lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal:

For where your treasure is, there will your heart be also.

The light of the body is the eye: if therefore thine eye be single, thy whole body shall be full of light.

But if thine eye be evil, thy whole body shall be full of darkness. If therefore the light that is in thee be darkness, how great is that darkness!
____

[verse]
____
Matthew, Ch. 11, 28-30
Come unto me, all ye that labour and are heavy laden, and I will give you rest

Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.

For my yoke is easy, and my burden is light.
____

[verse]
____
Luke, Ch. 6, 37
Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:

Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom.  For with the same measure that ye mete withal it shall be measured to you again.
____

[verse]
____
Timothy, Ch. 6, 3-12
If any man teach otherwise, and consent not to wholesome words, even the words of our Lord Jesus Christ, and to the doctrine which is according to godliness;

He is proud, knowing nothing, but doting about questions and strifes of words, whereof cometh envy, strife, railings, evil surmisings,

Perverse disputings of men of corrupt minds, and destitute of the truth, supposing that gain is godliness: from such withdraw thyself.

But godliness with contentment is great gain.

For we brought nothing into this world, and it is certain we can carry nothing out.

And having food and raiment let us be therewith content.

But they that will be rich fall into temptation and a snare, and into many foolish and hurtful lusts, which drown men in destruction and perdition.

For the love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows.

But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness.

Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses.
____


===== From Notebooks (1951-1959) by Albert Camus
[verse]
____
Find meaning. Distinguish melancholy from sadness. Go out for a walk. It doesn’t have to be a romantic walk in the park, spring at its most spectacular moment, flowers and smells and outstanding poetical imagery smoothly transferring you into another world. It doesn’t have to be a walk during which you’ll have multiple life epiphanies and discover meanings no other brain ever managed to encounter. Do not be afraid of spending quality time by yourself. Find meaning or don’t find meaning but 'steal' some time and give it freely and exclusively to your own self. Opt for privacy and solitude. That doesn’t make you antisocial or cause you to reject the rest of the world. But you need to breathe. And you need to be.
____


===== From Second Spring by John Henry Newman
[verse]
____
WE have familiar experience of the order, the constancy, the perpetual renovation of the material world which surrounds us. Frail and transitory as is every part of it, restless and migratory as are its elements, never-ceasing as are its changes, still it abides. It is bound together by a law of permanence, it is set up in unity; and, though it is ever dying, it is ever coming to life again. Dissolution does but give birth to fresh modes of organization, and one death is the parent of a {164} thousand lives. Each hour, as it comes, is but a testimony, how fleeting, yet how secure, how certain, is the great whole. It is like an image on the waters, which is ever the same, though the waters ever flow. Change upon change—yet one change cries out to another, like the alternate Seraphim, in praise and in glory of their Maker. The sun sinks to rise again; the day is swallowed up in the gloom of the night, to be born out of it, as fresh as if it had never been quenched. Spring passes into summer, and through summer and autumn into winter, only the more surely, by its own ultimate return, to triumph over that grave, towards which it resolutely hastened from its first hour. We mourn over the blossoms of May, because they are to wither; but we know, withal, that May is one day to have its revenge upon November, by the revolution of that solemn circle which never stops—which teaches us in our height of hope, ever to be sober, and in our depth of desolation, never to despair.
____


===== From Religion of the Day by John Henry Newman
[verse]
____
Dare not to think you have got to the bottom of your hearts; you do not know what evil lies there.
____


[verse]
____
It is difficult to get the news from poems yet men die miserably every day for lack of what is found there.
____


===== Charlie Chaplin
[verse]
____
Life is a tragedy when seen in close-up, but a comedy in long shot.
____


===== Nikos Kazantzakis, 1946
[verse]
____
How simple a frugal a thing is happiness: a glass of wine, a roast chestnut, a wretched little brazier, the sound of the sea.
____

===== John Perry Barlow, 1977
[verse]
____
Principles Of Adult Behavior

1. Be patient. No matter what.
2. Don’t badmouth: Assign responsibility, never blame. Say nothing behind another’s back you’d be unwilling to say, in exactly the same tone and language, to his face.
3. Never assume the motives of others are, to them, less noble than yours are to you.
4. Expand your sense of the possible.
5. Don’t trouble yourself with matters you truly cannot change.
6. Expect no more of anyone than you yourself can deliver.
7. Tolerate ambiguity.
8. Laugh at yourself frequently.
9. Concern yourself with what is right rather than whom is right.
10. Never forget that, no matter how certain, you might be wrong.
11. Give up blood sports.
12. Remember that your life belongs to others as well. Do not endanger it frivolously. And never endanger the life of another.
13. Never lie to anyone for any reason.
14. Learn the needs of those around you and respect them.
15. Avoid the pursuit of happiness. Seek to define your mission and pursue that.
16. Reduce your use of the first personal pronoun.
17. Praise at least as often as you disparage.
18. Never let your errors pass without admission.
19. Become less suspicious of joy.
20. Understand humility.
21. Forgive.
22. Foster dignity.
23. Live memorably.
24. Love yourself.
25. Endure.
____

===== Thomas Szasz, 1973
[verse]
____
Happiness is an imaginary condition, formerly attributed by the living to the dead, now usually attributed by adults to children, and by children to adults. Except for the time when Christopher got punched in the stomach.
____

===== Boethius, c. 520
[verse]
____
For in every ill turn of fortune the most unhappy sort of unfortunate man is the one who has been happy
____

===== Aleksandr Solzhenitsyn, The Gulag Archipelago 1918–1956
[verse]
____
If only it were all so simple! If only there were evil people somewhere insidiously committing evil deeds, and it were necessary only to separate them from the rest of us and destroy them. But the line dividing good and evil cuts through the heart of every human being. And who is willing to destroy a piece of his own heart?
____

===== Jean Anouilh, 1934
[verse]
____
There will always be a lost dog somewhere that will prevent me from being happy.
____

===== Ralph Waldo Emerson, 1844
[verse]
____
Just to fill the hour -- that is happiness.
____

===== Clarice Lispector, from "State of Grace"
[verse]
____
It is better if the state of grace is short lived. Should it last too long, as I well know, familiar as I am with my almost childish ambitions.  I should end up trying to penetrate the enigmas of nature.  And that would be enough to banish all grace.  For grace is a gift that makes no demands, but it would disappear if we were to start demanding answers.  We must never forget that the state of grace is only a tiny aperture which allows us to glimpse a sort of tranquil paradise, but it is not an entrance, nor does it give us the right to eat the fruits of the orchards.

One emerges from a state of grace with slear skin and open, thoughtful eyes.  And even without a trace of happiness, it is as if one's whole body were bathed ina gentle smile.  And one comes away a better person that when one entered.  To have known grace is to have experienced something that appeasrs to redeem the human condition is revealed in all its wretched poverty, therevy teaching us to love more, to forgive more, and show greater faith.  One begins to have a certain confidence in suffering and its ways, which can so often become unbearable.  

Some days are so arid and empty that I would give years of my life in exchange for a few inutes of grace.
____

===== Laozi, c 550 BC
[verse]
____
There is no greater disaster than not to know contentment.
____

===== John Dryden, 1665
[verse]
____
For all the happiness mankind can gain
Is not in pleasure, but in reset from pain.
____

===== Moby Dick by Herman Melville
[verse]
____
Oh, grassy glades! oh ever vernal endless landscapes in the soul; in ye,—though long parched by the dead drought of the earthly life,— in ye, men yet may roll, like young horses in new morning clover; and for some few fleeting moments, feel the cool dew of the life immortal on them. Would to God these blessed calms would last. But the mingled, mingling threads of life are woven by warp and woof: calms crossed by storms, a storm for every calm. There is no steady unretracing progress in this life; we do not advance through fixed gradations, and at the last one pause:— through infancy’s unconscious spell, boyhood’s thoughtless faith, adolescence’ doubt (the common doom), then scepticism, then disbelief, resting at last in manhood’s pondering repose of If. But once gone through, we trace the round again; and are infants, boys, and men, and Ifs eternally. Where lies the final harbor, whence we unmoor no more? In what rapt ether sails the world, of which the weariest will never weary? Where is the foundling’s father hidden? Our souls are like those orphans whose unwedded mothers die in bearing them: the secret of our paternity lies in their grave, and we must there to learn it.
____

[verse]
____
Consider the subtleness of the sea; how its most dreaded creatures glide under water, unapparent for the most part, and treacherously hidden beneath the loveliest tints of azure. Consider also the devilish brilliance and beauty of many of its most remorseless tribes, as the dainty embellished shape of many species of sharks. Consider, once more, the universal cannibalism of the sea; all whose creatures prey upon each other, carrying on eternal war since the world began.

Consider all this; and then turn to the green, gentle, and most docile earth; consider them both, the sea and the land; and do you not find a strange analogy to something in yourself? For as this appalling ocean surrounds the verdant land, so in the soul of man there lies one insular Tahiti, full of peace and joy, but encompassed by all the horrors of the half-known life. God keep thee! Push not off from that isle, thou canst never return!
____

[verse]
____
Were this world an endless plain, and by sailing eastward we could for ever reach new distances, and discover sights more sweet and strange than any Cyclades or Islands of King Solomon, then there were promise in the voyage. But in pursuit of those far mysteries we dream of, or in tormented chase of the demon phantom that, some time or other, swims before all human hearts; while chasing such over this round globe, they either lead us on in barren mazes or midway leave us whelmed.
____

[verse]
____
All visible objects, man, are but as pasteboard masks. But in each event — in the living act, the undoubted deed — there, some unknown but still reasoning thing puts forth the mouldings of its features from behind the unreasoning mask. If man will strike, strike through the mask! How can the prisoner reach outside except by thrusting through the wall? To me, the white whale is that wall, shoved near to me. Sometimes I think there's naught beyond. But 'tis enough. He tasks me; he heaps me; I see in him outrageous strength, with an inscrutable malice sinewing it. That inscrutable thing is chiefly what I hate; and be the white whale agent, or be the white whale principal, I will wreak that hate upon him.
____

===== Laura Cereta, 1486
[verse]
____
By staying up all night, I become a thief of time, sequestering a space from the rest of the day.
____

===== Ernest Hemingway, 1929
[verse]
____
The things of the night cannot be explained in the day, because they do not exist.
____

===== Brihadaranyaka Upanishad, c. 700BC
[verse]
____
When one goes to sleep, he takes along the material of this all-containing world, himself tears it aprt, himself uilds it up, and dreams by his own brightness, by his own light.
____

===== John Milton, 1637
[verse]
____
What hath night to do with sleep?
____

===== Samantha Hunt, 2007
[verse]
____
THe uncertain position we all maintain in life asking when will violence strike, when will devastation occur, leaves us looking like the hapless swimmers at the beginning of each Jaws movie.  Innocent, tender, and delicious.  Our legs tread water, buoyed by all that is right and good and deserved in this world, a house, healthy children, clean food to eat, love.  While that animatronic shark, a beast without mercy, catches the scent of blood and locks in on his target.
____

===== Henry Beston, 1928
[verse]
____
Our fantastic civilization has fallen out of touch with many aspects of nature, and with none more completely than with night. Primitive folk, gathered at a cave mouth round a fire, do not fear night; they fear, rather, the energies and creatures to whom night gives power; we of the age of the machines, having delivered ourselves of nocturnal enemies, now have a dislike of night itself. With lights and ever more lights, we drive the holiness and beauty of night back to the forests and the sea; the little villages, the crossroads even, will have none of it. Are modern folk, perhaps, afraid of night? Do they fear that vast serenity, the mystery of infinite space, the austerity of stars? Having made themselves at home in a civilization obsessed with power, which explains its whole world in terms of energy, do they fear at night for their dull acquiescence and the pattern of their beliefs? Be the answer what it will, to-day's civilization is full of people who have not the slightest notion of the character or the poetry of night, who have never even seen night. Yet to live thus, to know only artificial night, is as absurd and evil as to know only artificial day.
____

[verse]
____
Learn to reverence night and to put away the vulgar fear of it, for, with the banishment of night from the experience of man, there vanishes as well a religious emotion, a poetic mood, which gives depth to the adventure of humanity. By day, space is one with the earth and with man — it is his sun that is shining, his clouds that are floating past; at night, space is his no more. When the great earth, abandoning day, rolls up the deeps of the heavens and the universe, a new door opens for the human spirit, and there are few so clownish that some awareness of the mystery of being does not touch them as they gaze. For a moment of night we have a glimpse of ourselves and of our world islanded in its stream of stars — pilgrims of mortality, voyaging between horizons across eternal seas of space and time. Fugitive though the instant be, the spirit of man is, during it, ennobled by a genuine moment of emotional dignity, and poetry makes its own both the human spirit and experience.
____

===== Loren Eiseley, 1956
[verse]
____
In a way, it is the fear of the tife, the night tide, I callit, because that is the way you come to feel it--invisible, imperceptible almost, unless it is looked for--and yet as your grow older, you realize that it is always there, swirling like vapor just beyond the edge of the map at evening and similarly out to the ends of the universe.  Or at least it gives you that kind of sensation--a need to huddle in somehwere with light.

Maybe that is the real reason why men string lamps far out into the country lanes and try to run down everything with red eyes that happens to waddle across the road in front of their headlights.  It is cruel but revelatory: we are insecure, and this is our warfare with the dark. It began when man first lit a fire at a cave mouth and the eyes he feared—very big eyes they were then—began to blink and draw back.  So he lights and lights in a passion for illumination that is insatiable—a poor day-born thing contending against one of the greatest powers in the universe.  Even man's own domestic animals, the creatures he has chosen to bring in to the fire beside him, grow suspect in the evening.  His cat hints alone through the weeds, and his dog whines and snuffles at the door.  They all have their allegiance to the dark.  They are never wholly his.
____
